/*
NOKIA MOBILE PHONES
R&D Oulu
My Audio Basics










            Accessory server ISI macro message definitions
            ----------------------------------------------

            SW include Document - ANSI C




Continuus Ref:
---------------
database:           ou1gif

project path:       global_interface/ISI/Core

name:               acc_shared_isi_m.h

version:            002.011

type:               incl

instance:           ou_pcms#4

Document code:      -


Copyright(c) Nokia Corporation. All rights reserved.

Change history:

VERSION         : 002.011     NON-DRAFT    18-Feb-2010  Paavo Salonen
REASON          : New feature
REFERENCE       : ACCEPT360: 398451, 424606
                  CR: SWAM DB / PS11021855568                   
DESCRIPTION     : Added new haptics effect id's.

VERSION         : 002.010     NON-DRAFT    14-Oct-2010  Juha Niemi
REASON          : New feature
REFERENCE       : REQ: 415-8546
                  CR: SWAM DB / JN10101436746                   
DESCRIPTION     : Added new values ACC_ENABLE_NAHJ_PIN_ORDER and ACC_DISABLE_NAHJ_PIN_ORDER to ACC_TEST_REQ_ACTION

VERSION         : 002.009     NON-DRAFT    14-May-2010  Paavo Salonen
REASON          : New feature
REFERENCE       : ACCEPT360: 398451, 424606
                  CR: SWAM DB / PS10051437840
DESCRIPTION     : New ISI messages for haptics.

VERSION         : 002.008     NON-DRAFT    15-Mar-2010  Jari Huhtamaki
REASON          : New feature
REFERENCE       : REQ: 428-1170
                  CR: SWAM DB / JH10031245916
DESCRIPTION     : Added support for automated testing.

VERSION         : 002.007     NON-DRAFT    04-Dec-2009  Janne Vimpari
REASON          : New feature
REFERENCE       : SCO: 014-543: Accessory Server: Wideband Bluetooth - Support for codec selection and supported codecs 
		              CR: SWAM DB / JV09120447813
DESCRIPTION     : Added new values ACC_BT_CVSD and ACC_BT_MSBC to SUPPORTED_FEATURES_BITMASK_TABLE

VERSION         : 002.006     NON-DRAFT    15-Sep-2009  Katja Knuutinen
REASON          : New feature
REFERENCE       : SCO: ISA RM / 9.1: 417-53825, MCL: 417-56193
		              CR: SWAM DB / JV09090458862
DESCRIPTION     : Added new value ACC_BT_REMOTE_VRA to SUPPORTED_FEATURES_BITMASK_TABLE bitfield (9.1 and MCL)

VERSION         : 002.005     NON-DRAFT    24-Feb-2009  Kari Merilainen
REASON          : HAPTICS ISI Interface CR
REFERENCE       : CR: SWM ADB / KM09022351713
DESCRIPTION     : Version updated
                    - ACC_SB_HAPTICSDATA -SUB_BLOCK change to be ISI protocol compliant

VERSION         : 002.004     NON-DRAFT    20-Nov-2008  Kari Merilainen
REASON          : HAPTICS ISI Interface
REFERENCE       : RM-RIM / 417-21271
                    CR: SWAM ADB / EK08010739070
DESCRIPTION     : Version updated

VERSION         : 002.003     NON-DRAFT    10-Apr-2008  Lasse Köngäs
REASON          : Error correction
REFERENCE       : CR: SWAM ADB / EK08041044788
DESCRIPTION     : Version updated

VERSION         : 002.002     NON-DRAFT    07-Feb-2008  Lasse Köngäs
REASON          : Improvement
REFERENCE       : SCO: ISA RM / 414-4130
		  CR: SWAM DB /EK08010739070
DESCRIPTION     : From now on acc_shared_isi.h file is generated by using this macro file.
		  Made some define fixes.

VERSION         : 002.001     NON-DRAFT    16-Nov-2007  Lasse Köngäs
REASON          : New feature
REFERENCE       : SCO: ISA RM / 414-2726 and 414-2747 for USB and
		  414-2928 and 414-2942 for Vibra     
		  CR: SWAM ADB / EK07111246286            
DESCRIPTION     : Added support to enable/disable USB from ACC point of view.
		  Added message to enable/disable normal vibra control.

VERSION         : 002.000     NON-DRAFT    20-Aug-2007  Jari Huhtamaki
REASON          : New feature
REFERENCE       : SCO: ISA RM / 402-1912
                  CR: SWAM ADB / JH0708213489
DESCRIPTION     : ACC Srv: Interface changes for vibra touch tactile feedback

VERSION         : 001.008     NON-DRAFT    08-May-2007  Sami Sutinen
REASON          : New feature
REFERENCE       : SCO: ISA RM / 402-1651
                  CR: SWAM ADB / SS07050838321
DESCRIPTION     : Interface changes for BT visibility and indicators improvements

VERSION         : 001.007     NON-DRAFT    12-Dec-2006  Sami Sutinen
REASON          : New feature
REFERENCE       : SCO: ISA RM / 009-28731
                  CR: SWAM ADB / SS06121341573
DESCRIPTION     : Field test display improvements

VERSION         : 001.006     NON-DRAFT    22-Nov-2006  Kari Merilainen
REASON          : New feature
REFERENCE       : SCO: ISA RM / 010-30443
                  CR: SWAM ADB / KM06112344292
DESCRIPTION     : New symbol added, ACC_ANSWER_END_DOUBLECLICK

VERSION         : 001.005     NON-DRAFT    28-Aug-2006  Jari Huhtamaki
REASON          : Error correction
REFERENCE       : PCP Errors / MN06062848806
                  CR: SWAM ADB / JH06082841031
DESCRIPTION     : New symbol added, ACC_MIC3.

VERSION         : 001.004     NON-DRAFT    22-Aug-2006  Jani Pellikka
REASON          : New features
REFERENCE       : SCO: ISA RM / 009-27330
DESCRIPTION     : Version updated

VERSION         : 001.003     NON-DRAFT    22-May-2006  Jari Huhtamaki
REASON          : New features
REFERENCE       : CR: SWAM ADB / JH06052265532
DESCRIPTION     : Version updated

VERSION         : 001.002     NON-DRAFT    08-May-2006  Kari Merilainen
REASON          : New C-Video calibration ACC_AV_CVIDEO_CALIBRATE_REQ
REFERENCE       : SCO: ISA RM / 010-23460
                  CR: SWAM ADB / KM06050836854
DESCRIPTION     : Version updated

VERSION         : 001.001     NON-DRAFT    04-May-2006  Kari Merilainen
REASON          : New TV-Out test parameter for ACC_TEST_REQ
REFERENCE       : SCO: ISA RM / 010-23033
                  CR: SWAM ADB / KM06050354784
DESCRIPTION     : New parameter ACC_ENABLE_AV_TVOUT & ACC_DISABLE_AV_TVOUT
                  for ACC_TEST_REQ

VERSION         : 001.000     NON-DRAFT    01-Mar-2006  Jari Huhtamaki
REASON          : ECI Features
REFERENCE       : SCO: ISA RM / 010-19044
                  CR: SWAM ADB / JH0603012833
DESCRIPTION     : New features and error corrections.

VERSION         : 000.052     NON-DRAFT    12-Dec-2005  Kari Merilainen
REASON          : NokiaAV Production tests
REFERENCE       : SCO: ISA RM / 010-17727
                  CR: SWAM ADB / KM05121256994
DESCRIPTION     : Version updated

VERSION         : 000.051     NON-DRAFT    1-Dec-2005  Kari Merilainen
REASON          : NokiaAV Audio MIC state change & DSP Hook polling
REFERENCE       : SCO: ISA RM / 010-19042
                  CR: SWAM ADB / KM05120156741
DESCRIPTION     : Version updated

VERSION         : 000.050     NON-DRAFT    21-Nov-2005  Kari Merilainen
REASON          : NokiaAV Field Test Display
REFERENCE       : SCO: ISA RM / 009-19843
                  CR: SWAM ADB / KM05112436446
DESCRIPTION     : Version updated

VERSION         : 000.049     NON-DRAFT    20-Oct-2005  Jari Huhtamaki
REASON          : NokiaAV
REFERENCE       : SCO: ISA RM /  009-19831 ACC Srv: NOKAV: ISI Interface
                  CR: SWAM ADB / JH05100336709
DESCRIPTION     : Version updated.

VERSION         : 000.048     NON-DRAFT    09-Aug-2005  Kari Merilainen
REASON          : TV-Out support
REFERENCE       : SCO: ISA RM / 010-12404: TV-Out support in ISA accessory SW
                  CR: SWAM ADB / KM050880938907                   
DESCRIPTION     : New subtype added: ACC_THWK_ADA_TVOUT

VERSION         : 000.047     NON-DRAFT    27-May-2005  Kari Merilainen
REASON          : Low power flash support
REFERENCE       : SCO: ISA RM / 009-18056: Camera PD-2 support
                  CR: SWAM ADB / KM05052740578: Accessory server: Low power support for PD-2 -flash accessory
DESCRIPTION     : New feature added for Pd-2 flash low power mode
                  ( ACC_THWK_FLASH_LOW_POWER_ON )

VERSION         : 000.046     NON-DRAFT    18-Apr-2005  Mika P. Kangas
REASON          : Error Fix.
REFERENCE       : 
DESCRIPTION     : No changes. (Version number updated)

VERSION         : 000.045     NON-DRAFT    01-Apr-2005  Mika P. Kangas
REASON          : Created to support shared subblocks
REFERENCE       : SCO: ISA RM / 009-17465: AUD Srv: Audio routing for S60 3.0
                  CR: SWAM ADB / MK05031647456
DESCRIPTION     : Sub blocks ACC_SB_THWK_INFO_FEATURE, ACC_SB_THWK_EXEC_FEATURE,
                  ACC_SB_THWK_AUDIO_BLOCK were reintroduced to enable sharing with
                  audio_isi.h. And a new message ID ACC_THWK_NO_INFORMATION created.

*/

/* ------------------------------------------------------------------------- */

#ifndef _ACC_SHARED_ISI_M_H
#define _ACC_SHARED_ISI_M_H

/*  1    ABSTRACT

    1.1    Module type

    Header file for the ISI Autogeneration Application
   

    1.2    Functional description

    This file is the message definition file for the Accessory Server


    1.3    Notes


    2    CONTENTS


    1    ABSTRACT
    1.1    Module type
    1.2    Functional description
    1.3    Notes

    2    CONTENTS

    3    CONSTANTS

    4    MACROS

    5    DATA TYPES

    6    CLASSES

    7    OBJECTS

    8    DATA STRUCTURES

    9    FUNCTION PROTOTYPES
*/

/*  3    CONSTANTS */

/* Shared sub block ID's */

/* Tomahawk specific sub blocks */

#define ACC_SB_THWK_INFO_FEATURE            0x01
#define ACC_SB_THWK_EXEC_FEATURE            0x02
#define ACC_SB_THWK_AUDIO_BLOCK             0x03

/*  4    MACROS */

#define ACC_SHARED_SB \
    REFERENCE(8, BE, sub_block_id, "Sub Block ID", SB_ID) \
    REFERENCE(8, BE, sub_block_length, "Sub Block Length", SB_LENGTH) 


#ifndef ACC_ISI_VERSION
#define ACC_ISI_VERSION
#define ACC_ISI_VERSION_Z   2
#define ACC_ISI_VERSION_Y   11
#endif

    /* --------------------------------------------------------------------- */
    /* Project / Document information */
    /* --------------------------------------------------------------------- */

    /* Project / Document properties */
    PROPERTY_STRING(PROPERTY_PROJECT_SITE_NAME,                 "Oulu")
    PROPERTY_STRING(PROPERTY_PROJECT_NAME,                      "My Audio Basics")
    PROPERTY_STRING(PROPERTY_PROJECT_OWNER_NAME,                "Jari Huhtamäki")
    PROPERTY_STRING(PROPERTY_PROJECT_CONFIDENTIALITY,           "CONFIDENTIAL")

    /* ISI header properties */
    PROPERTY_STRING(PROPERTY_ISIHDR_TITLE,                      "Accessory server ISI message definitions")
    PROPERTY_STRING(PROPERTY_ISIHDR_FILENAME,                   "acc_shared_isi.h")
    PROPERTY_STRING(PROPERTY_ISIHDR_FILENAME_16,                "")
    PROPERTY_STRING(PROPERTY_ISIHDR_CONTINUUS_PROJECT_DB,       "ou1gif")
    PROPERTY_STRING(PROPERTY_ISIHDR_CONTINUUS_PROJECT_PATH,     "global_interface/ISI/Core")
    PROPERTY_STRING(PROPERTY_ISIHDR_CONTINUUS_PROJECT_PATH_16,  "")
    PROPERTY_STRING(PROPERTY_ISIHDR_CONTINUUS_INSTANCE_NAME,    "")
    PROPERTY_STRING(PROPERTY_ISIHDR_CONTINUUS_INSTANCE_NAME_16, "")

    /* HTML properties */
    PROPERTY_STRING(PROPERTY_HTML_TITLE,                        "ACC Message Specification")
    PROPERTY_STRING(PROPERTY_HTML_FILENAME,                     "i_acc_shared_isi_m.html")
    PROPERTY_STRING(PROPERTY_HTML_DOCUMENT_NUMBER,              "-")
    PROPERTY_STRING(PROPERTY_HTML_CONTINUUS_PROJECT_DB,         "ou1gif")
    PROPERTY_STRING(PROPERTY_HTML_CONTINUUS_PROJECT_NAME,       "GIF_SPECS-ou1gif#browse")
    PROPERTY_STRING(PROPERTY_HTML_DIRECTORY_PATH,               "GIF_SPECS/CoreSW")
    /*PROPERTY(PROPERTY_HTML_INCLUDE_INTRODUCTION)*/

RES_BEGIN(RESOURCE_ISI_SHARED, PN_ACCESSORY, ACC, "Accessory Shared Sub Block Descriptions", 
    RES_VERSION_STRING(ACC_ISI_VERSION_Z, ACC_ISI_VERSION_Y), FALSE)


    /* --------------------------------------------------------------------- */
    /* ISI version history */
    /* --------------------------------------------------------------------- */

    /* ISI version history */
    
    PROPERTY_STRING(PROPERTY_CHANGE_REASON,    "New features")
    PROPERTY_STRING(PROPERTY_CHANGE_REFERENCE, "SWAM ADB / PS11021855568")
    PROPERTY_STRING(PROPERTY_CHANGE_STATUS,    "NON-DRAFT")
    PROPERTY_STRING(PROPERTY_CHANGE_DATE,      "18-Feb-2011")
    PROPERTY_STRING(PROPERTY_CHANGE_PERSON,    "Paavo Salonen")
    COMMENT(COMMENT_TEXT,                      "New effect id's for haptics interface.")
    ISI_VERSION_HISTORY("002.011")
    
    PROPERTY_STRING(PROPERTY_CHANGE_REASON,    "New features")
    PROPERTY_STRING(PROPERTY_CHANGE_REFERENCE, "SWAM ADB / JN10101436746")
    PROPERTY_STRING(PROPERTY_CHANGE_STATUS,    "NON-DRAFT")
    PROPERTY_STRING(PROPERTY_CHANGE_DATE,      "18-Oct-2010")
    PROPERTY_STRING(PROPERTY_CHANGE_PERSON,    "Juha Niemi")
    COMMENT(COMMENT_TEXT,             "Added new values ACC_ENABLE_NAHJ_PIN_ORDER and ACC_DISABLE_NAHJ_PIN_ORDER to ACC_TEST_REQ_ACTION")
    ISI_VERSION_HISTORY("002.010")
    
    PROPERTY_STRING(PROPERTY_CHANGE_REASON,    "New features")
    PROPERTY_STRING(PROPERTY_CHANGE_REFERENCE, "SWAM ADB / PS10051437840")
    PROPERTY_STRING(PROPERTY_CHANGE_STATUS,    "NON-DRAFT")
    PROPERTY_STRING(PROPERTY_CHANGE_DATE,      "14-May-2010")
    PROPERTY_STRING(PROPERTY_CHANGE_PERSON,    "Paavo Salonen")
    COMMENT(COMMENT_TEXT,             "Added support for new haptics interface.")
    ISI_VERSION_HISTORY("002.009")
    
    PROPERTY_STRING(PROPERTY_CHANGE_REASON,    "New features")
    PROPERTY_STRING(PROPERTY_CHANGE_REFERENCE, "SWAM ADB / JH10031245916")
    PROPERTY_STRING(PROPERTY_CHANGE_STATUS,    "NON-DRAFT")
    PROPERTY_STRING(PROPERTY_CHANGE_DATE,      "15-Mar-2010")
    PROPERTY_STRING(PROPERTY_CHANGE_PERSON,    "Jari Huhtamäki")
    COMMENT(COMMENT_TEXT,             "Added support for automated testing.")
    ISI_VERSION_HISTORY("002.008")
    
    PROPERTY_STRING(PROPERTY_CHANGE_REASON,    "New features")
    PROPERTY_STRING(PROPERTY_CHANGE_REFERENCE, "SWAM ADB / JV09120447813")
    PROPERTY_STRING(PROPERTY_CHANGE_STATUS,    "NON-DRAFT")
    PROPERTY_STRING(PROPERTY_CHANGE_DATE,      "04-Dec-2009")
    PROPERTY_STRING(PROPERTY_CHANGE_PERSON,    "Janne Vimpari")
    COMMENT(COMMENT_TEXT,             "Added new values ACC_BT_CVSD and ACC_BT_MSBC to SUPPORTED_FEATURES_BITMASK_TABLE")
    ISI_VERSION_HISTORY("002.007")
     
    PROPERTY_STRING(PROPERTY_CHANGE_REASON,    "New features")
    PROPERTY_STRING(PROPERTY_CHANGE_REFERENCE, "SWAM ADB / JV09090458862")
    PROPERTY_STRING(PROPERTY_CHANGE_STATUS,    "NON-DRAFT")
    PROPERTY_STRING(PROPERTY_CHANGE_DATE,      "15-Sep-2009")
    PROPERTY_STRING(PROPERTY_CHANGE_PERSON,    "Katja Knuutinen")
    COMMENT(COMMENT_TEXT,             "Added new value ACC_BT_REMOTE_VRA to SUPPORTED_FEATURES_BITMASK_TABLE bitfield (9.1 and MCL)")
    ISI_VERSION_HISTORY("002.006")
   
    PROPERTY_STRING(PROPERTY_CHANGE_REASON,    "Improvements")
    PROPERTY_STRING(PROPERTY_CHANGE_REFERENCE, "SWAM ADB / KM09022351713")
    PROPERTY_STRING(PROPERTY_CHANGE_STATUS,    "NON-DRAFT")
    PROPERTY_STRING(PROPERTY_CHANGE_DATE,      "24-Feb-2009")
    PROPERTY_STRING(PROPERTY_CHANGE_PERSON,    "Kari Meriläinen")
    COMMENT(COMMENT_TEXT,             "Version updated")
    ISI_VERSION_HISTORY("002.005")
        
    PROPERTY_STRING(PROPERTY_CHANGE_REASON,    "Improvements")
    PROPERTY_STRING(PROPERTY_CHANGE_REFERENCE, "SWAM ADB / KM08112055376")
    PROPERTY_STRING(PROPERTY_CHANGE_STATUS,    "NON-DRAFT")
    PROPERTY_STRING(PROPERTY_CHANGE_DATE,      "20-Nov-2008")
    PROPERTY_STRING(PROPERTY_CHANGE_PERSON,    "Kari Meriläinen")
    COMMENT(COMMENT_TEXT,             "Version updated")
    ISI_VERSION_HISTORY("002.004")
        
    PROPERTY_STRING(PROPERTY_CHANGE_REASON,    "Error correction")
    PROPERTY_STRING(PROPERTY_CHANGE_REFERENCE, "SWAM ADB / EK08041044788")
    PROPERTY_STRING(PROPERTY_CHANGE_STATUS,    "NON-DRAFT")
    PROPERTY_STRING(PROPERTY_CHANGE_DATE,      "10-Apr-2008")
    PROPERTY_STRING(PROPERTY_CHANGE_PERSON,    "Lasse Kongas")
    COMMENT(COMMENT_TEXT,"Version updated")
    ISI_VERSION_HISTORY("002.003")
        
    PROPERTY_STRING(PROPERTY_CHANGE_REASON,    "Improvements")
    PROPERTY_STRING(PROPERTY_CHANGE_REFERENCE, "SWAM ADB / EK08010739070")
    PROPERTY_STRING(PROPERTY_CHANGE_STATUS,    "NON-DRAFT")
    PROPERTY_STRING(PROPERTY_CHANGE_DATE,      "07-Feb-2008")
    PROPERTY_STRING(PROPERTY_CHANGE_PERSON,    "Lasse Kongas")
    COMMENT(COMMENT_TEXT,"From now on acc_shared_isi.h file is generated by \
    using acc_shared_isi_m.h macro file. Made some define fixes.")
    ISI_VERSION_HISTORY("002.002")    
    
    PROPERTY_STRING(PROPERTY_CHANGE_REASON,    "New features")
    PROPERTY_STRING(PROPERTY_CHANGE_REFERENCE, "CR: SWAM DB /EK07111246286")
    PROPERTY_STRING(PROPERTY_CHANGE_STATUS,    "NON-DRAFT")
    PROPERTY_STRING(PROPERTY_CHANGE_DATE,      "16-Nov-2007")
    PROPERTY_STRING(PROPERTY_CHANGE_PERSON,    "Lasse Kongas")
    COMMENT(COMMENT_TEXT,             "Support to control Vibra and USB interfaces")
    ISI_VERSION_HISTORY("002.001")
    
    PROPERTY_STRING(PROPERTY_CHANGE_REASON,    "New features")
    PROPERTY_STRING(PROPERTY_CHANGE_REFERENCE, "SWAM ADB / JH0708213489")
    PROPERTY_STRING(PROPERTY_CHANGE_STATUS,    "NON-DRAFT")
    PROPERTY_STRING(PROPERTY_CHANGE_DATE,      "20-Aug-2007")
    PROPERTY_STRING(PROPERTY_CHANGE_PERSON,    "Jari Huhtamaki")
    COMMENT(COMMENT_TEXT,             "Interface changes for vibra touch tactile feedback")
    ISI_VERSION_HISTORY("002.000")

    PROPERTY_STRING(PROPERTY_CHANGE_REASON,    "New features")
    PROPERTY_STRING(PROPERTY_CHANGE_REFERENCE, "SWAM ADB / SS07050838321")
    PROPERTY_STRING(PROPERTY_CHANGE_STATUS,    "NON-DRAFT")
    PROPERTY_STRING(PROPERTY_CHANGE_DATE,      "08-May-2007")
    PROPERTY_STRING(PROPERTY_CHANGE_PERSON,    "Sami Sutinen")
    COMMENT(COMMENT_TEXT,             "Interface changes for BT visibility and indicators improvements")
    ISI_VERSION_HISTORY("001.008")
    
    PROPERTY_STRING(PROPERTY_CHANGE_REASON,    "New features")
    PROPERTY_STRING(PROPERTY_CHANGE_REFERENCE, "SWAM ADB / SS06121341573")
    PROPERTY_STRING(PROPERTY_CHANGE_STATUS,    "NON-DRAFT")
    PROPERTY_STRING(PROPERTY_CHANGE_DATE,      "13-Dec-2006")
    PROPERTY_STRING(PROPERTY_CHANGE_PERSON,    "Sami Sutinen")
    COMMENT(COMMENT_TEXT,             "Field test display improvements. Added support for FTD_MODE_OPERATOR")
    ISI_VERSION_HISTORY("001.007")
    
    PROPERTY_STRING(PROPERTY_CHANGE_REASON,    "New features")
    PROPERTY_STRING(PROPERTY_CHANGE_REFERENCE, "SWAM ADB / KM06112344292")
    PROPERTY_STRING(PROPERTY_CHANGE_STATUS,    "NON-DRAFT")
    PROPERTY_STRING(PROPERTY_CHANGE_DATE,      "22-Nov-2006")
    PROPERTY_STRING(PROPERTY_CHANGE_PERSON,    "Kari Merilainen")
    COMMENT(COMMENT_TEXT,             "New symbol added, ACC_ANSWER_END_DOUBLECLICK")
    ISI_VERSION_HISTORY("001.006")

    PROPERTY_STRING(PROPERTY_CHANGE_REASON,    "New features")
    PROPERTY_STRING(PROPERTY_CHANGE_REFERENCE, "SWAM ADB / JH06082841031")
    PROPERTY_STRING(PROPERTY_CHANGE_STATUS,    "NON-DRAFT")
    PROPERTY_STRING(PROPERTY_CHANGE_DATE,      "28-Aug-2006")
    PROPERTY_STRING(PROPERTY_CHANGE_PERSON,    "Jari Huhtamaki")
    COMMENT(COMMENT_TEXT,             "New symbol added, ACC_MIC3")
    ISI_VERSION_HISTORY("001.005")

    PROPERTY_STRING(PROPERTY_CHANGE_REASON,    "New features")
    PROPERTY_STRING(PROPERTY_CHANGE_REFERENCE, "SCO: ISA RM / 009-27330")
    PROPERTY_STRING(PROPERTY_CHANGE_STATUS,    "NON-DRAFT")
    PROPERTY_STRING(PROPERTY_CHANGE_DATE,      "22-Aug-2006")
    PROPERTY_STRING(PROPERTY_CHANGE_PERSON,    "Jani Pellikka")
    COMMENT(COMMENT_TEXT,             "FTD macros updated")
    ISI_VERSION_HISTORY("001.004")

    PROPERTY_STRING(PROPERTY_CHANGE_REASON,    "New features")
    PROPERTY_STRING(PROPERTY_CHANGE_REFERENCE, "CR: SWAM ADB / JH06052265532")
    PROPERTY_STRING(PROPERTY_CHANGE_STATUS,    "NON-DRAFT")
    PROPERTY_STRING(PROPERTY_CHANGE_DATE,      "22-May-2006")
    PROPERTY_STRING(PROPERTY_CHANGE_PERSON,    "Jari Huhtamaki")
    COMMENT(COMMENT_TEXT,             "New features added to ACC_FEATURES table")
    ISI_VERSION_HISTORY("001.003")

    PROPERTY_STRING(PROPERTY_CHANGE_REASON,    "NokiaAV - Production test")
    PROPERTY_STRING(PROPERTY_CHANGE_REFERENCE, "SCO: ISA RM / 010-23460:ACC Srv: NOKAV: Calibration IF for C-Video cable")
    PROPERTY_STRING(PROPERTY_CHANGE_STATUS,    "NON-DRAFT")
    PROPERTY_STRING(PROPERTY_CHANGE_DATE,      "08-May-2006")
    PROPERTY_STRING(PROPERTY_CHANGE_PERSON,    "Kari Merilainen")
    COMMENT(COMMENT_TEXT,             "New request/responce pair for calibrating the C-Video cable")
    ISI_VERSION_HISTORY("001.002")

    PROPERTY_STRING(PROPERTY_CHANGE_REASON,    "NokiaAV - Production tests")
    PROPERTY_STRING(PROPERTY_CHANGE_REFERENCE, "SCO: ISA RM / 010-23033: ACC Srv: NOKAV: Test interface for TV_Out testing")
    PROPERTY_STRING(PROPERTY_CHANGE_STATUS,    "NON-DRAFT")
    PROPERTY_STRING(PROPERTY_CHANGE_DATE,      "04-May-2006")
    PROPERTY_STRING(PROPERTY_CHANGE_PERSON,    "Kari Merilainen")
    COMMENT(COMMENT_TEXT,             "Version updated")
    ISI_VERSION_HISTORY("001.001")

    PROPERTY_STRING(PROPERTY_CHANGE_REASON,    "ECI Features")
    PROPERTY_STRING(PROPERTY_CHANGE_REFERENCE, "SCO: ISA RM / 010-19044")
    PROPERTY_STRING(PROPERTY_CHANGE_STATUS,    "NON-DRAFT")
    PROPERTY_STRING(PROPERTY_CHANGE_DATE,      "02-Mar-2006")
    PROPERTY_STRING(PROPERTY_CHANGE_PERSON,    "Jari Huhtamaki")
    COMMENT(COMMENT_TEXT,             "Version updated")
    ISI_VERSION_HISTORY("001.000")

    PROPERTY_STRING(PROPERTY_CHANGE_REASON,    "NokiaAV - Production tests")
    PROPERTY_STRING(PROPERTY_CHANGE_REFERENCE, "SCO: ISA RM / 010-17727:ACC Srv: NOKAV: Accessory Production Tests")
    PROPERTY_STRING(PROPERTY_CHANGE_STATUS,    "NON-DRAFT")
    PROPERTY_STRING(PROPERTY_CHANGE_DATE,      "12-Dec-2005")
    PROPERTY_STRING(PROPERTY_CHANGE_PERSON,    "Kari Meriläinen")
    COMMENT(COMMENT_TEXT,             "Version updated")
    ISI_VERSION_HISTORY("000.052")

    PROPERTY_STRING(PROPERTY_CHANGE_REASON,    "NokiaAV - MIC Change & DSP hook polling")
    PROPERTY_STRING(PROPERTY_CHANGE_REFERENCE, "SCO: ISA RM / 010-19042 AUD Srv: NOKAV: Report MIC2 power to ACC HAL")
    PROPERTY_STRING(PROPERTY_CHANGE_STATUS,    "NON-DRAFT")
    PROPERTY_STRING(PROPERTY_CHANGE_DATE,      "01-Dec-2005")
    PROPERTY_STRING(PROPERTY_CHANGE_PERSON,    "Kari Meriläinen")
    COMMENT(COMMENT_TEXT,             "Version updated")
    ISI_VERSION_HISTORY("000.051")

    PROPERTY_STRING(PROPERTY_CHANGE_REASON,    "NokiaAV FTD")
    PROPERTY_STRING(PROPERTY_CHANGE_REFERENCE, "SCO: ISA RM / 009-19843 ACC Srv: NOKAV: FTD Display")
    PROPERTY_STRING(PROPERTY_CHANGE_STATUS,    "NON-DRAFT")
    PROPERTY_STRING(PROPERTY_CHANGE_DATE,      "21-Nov-2005")
    PROPERTY_STRING(PROPERTY_CHANGE_PERSON,    "Kari Meriläinen")
    COMMENT(COMMENT_TEXT,             "Version updated.")
    ISI_VERSION_HISTORY("000.050")
    
    PROPERTY_STRING(PROPERTY_CHANGE_REASON,    "NokiaAV")
    PROPERTY_STRING(PROPERTY_CHANGE_REFERENCE, "SCO: ISA RM / 009-19831 ACC Srv: NOKAV: ISI Interface")
    PROPERTY_STRING(PROPERTY_CHANGE_STATUS,    "NON-DRAFT")
    PROPERTY_STRING(PROPERTY_CHANGE_DATE,      "20-Oct-2005")
    PROPERTY_STRING(PROPERTY_CHANGE_PERSON,    "Jari Huhtamäki")
    COMMENT(COMMENT_TEXT,             "Version updated.")
    ISI_VERSION_HISTORY("000.049")
    
    PROPERTY_STRING(PROPERTY_CHANGE_REASON,    "TV-Out support")
    PROPERTY_STRING(PROPERTY_CHANGE_REFERENCE, "SCO: ISA RM / 010-12404: TV-Out support in ISA accessory SW")
    PROPERTY_STRING(PROPERTY_CHANGE_STATUS,    "NON-DRAFT")
    PROPERTY_STRING(PROPERTY_CHANGE_DATE,      "09-Aug-2005")
    PROPERTY_STRING(PROPERTY_CHANGE_PERSON,    "Kari Merilainen")
    COMMENT(COMMENT_TEXT,             "Added ACC_THWK_ADA_TVOUT subtype")
    ISI_VERSION_HISTORY("000.048")
    
    PROPERTY_STRING(PROPERTY_CHANGE_REASON,    "Flash accessory low power support")
    PROPERTY_STRING(PROPERTY_CHANGE_REFERENCE, "SCO: ISA RM / 009-18056: Camera PD-2 support")
    PROPERTY_STRING(PROPERTY_CHANGE_STATUS,    "NON-DRAFT")
    PROPERTY_STRING(PROPERTY_CHANGE_DATE,      "27-May-2005")
    PROPERTY_STRING(PROPERTY_CHANGE_PERSON,    "Kari Merilainen")
    COMMENT(COMMENT_TEXT,             "Added ACC_THWK_FLASH_LOW_POWER_ON")
    ISI_VERSION_HISTORY("000.047")
    
    PROPERTY_STRING(PROPERTY_CHANGE_REASON,    "Error fix")
    PROPERTY_STRING(PROPERTY_CHANGE_REFERENCE, "-")
    PROPERTY_STRING(PROPERTY_CHANGE_STATUS,    "NON-DRAFT")
    PROPERTY_STRING(PROPERTY_CHANGE_DATE,      "18-Apr-2005")
    PROPERTY_STRING(PROPERTY_CHANGE_PERSON,    "Mika P. Kangas")
    COMMENT(COMMENT_TEXT,             "Fixes for acc_shared_isi.h")
    ISI_VERSION_HISTORY("000.046")
    
    PROPERTY_STRING(PROPERTY_CHANGE_REASON,    "Created")
    PROPERTY_STRING(PROPERTY_CHANGE_REFERENCE, "ISA RM / 009-17465: AUD Srv: Audio routing for S60 3.0")
    PROPERTY_STRING(PROPERTY_CHANGE_STATUS,    "NON-DRAFT")
    PROPERTY_STRING(PROPERTY_CHANGE_DATE,      "01-Apr-2005")
    PROPERTY_STRING(PROPERTY_CHANGE_PERSON,    "Mika P. Kangas")
    COMMENT(COMMENT_TEXT,             "Created for shared usage")
    ISI_VERSION_HISTORY("000.045")

    
    /* Constant definitions */

/* Define the version of this ISI Messages for ACC */
    CONSTANT(ACC_ISI_VERSION_ZZZ,                 ACC_ISI_VERSION_Z)
    CONSTANT(ACC_ISI_VERSION_YYY,                 ACC_ISI_VERSION_Y)

    /* Constant tables */
    
    CONST_TBL_BEGIN(ACC_THWK_MASTER_TYPE, 8, BE, "000.045", "")
        CONST_TBL_ENTRY(ACC_THWK_OTHER,                         0x00, "")
        CONST_TBL_ENTRY(ACC_THWK_HEADSET,                       0x01, "")
        CONST_TBL_ENTRY(ACC_THWK_HANDSFREE,                     0x02, "")
        CONST_TBL_ENTRY(ACC_THWK_DATACABLE,                     0x03, "")
        CONST_TBL_ENTRY(ACC_THWK_TEST_DEVICE,                   0x04, "")
        CONST_TBL_ENTRY(ACC_THWK_CAMERA,                        0x05, "")
        CONST_TBL_ENTRY(ACC_THWK_MISC,                          0x06, "")
        CONST_TBL_ENTRY(ACC_THWK_ADAPTER,                       0x07, "")
        CONST_TBL_ENTRY(ACC_THWK_NO_INFORMATION,                0xFC, "")
        CONST_TBL_ENTRY(ACC_THWK_NOT_READY,                     0xFE, "")
        CONST_TBL_ENTRY(ACC_THWK_UNSUPPORTED,                   0xFD, "")
        CONST_TBL_ENTRY(ACC_THWK_NOT_CONNECTED,                 0xFF, "")
    CONST_TBL_END

    CONST_TBL_BEGIN(ACC_THWK_SUB_TYPE_OTHER, 8, BE, "000.045", "")
        CONST_TBL_ENTRY(ACC_THWK_HEADSET_UNIV,                  0x01, "")
        CONST_TBL_ENTRY(ACC_THWK_TTY_UNIV,                      0x02, "")
        CONST_TBL_ENTRY(ACC_THWK_LINEIN,                        0x03, "")
        CONST_TBL_ENTRY(ACC_THWK_TTY,                           0x10, "")
        CONST_TBL_ENTRY(ACC_THWK_NO_INFORMATION,                0xFC, "")
        CONST_TBL_ENTRY(ACC_THWK_NOT_READY,                     0xFE, "")
        CONST_TBL_ENTRY(ACC_THWK_UNSUPPORTED,                   0xFD, "")
        CONST_TBL_ENTRY(ACC_THWK_NOT_CONNECTED,                 0xFF, "")
    CONST_TBL_END


    CONST_TBL_BEGIN(ACC_THWK_SUB_TYPE_HD, 8, BE, "000.045", "")
        CONST_TBL_ENTRY(ACC_THWK_HD_BASIC,                      0x00, "")
        CONST_TBL_ENTRY(ACC_THWK_HD_STEREO,                     0x01, "")
        CONST_TBL_ENTRY(ACC_THWK_HD_LOOPSET,                    0x02, "")
        CONST_TBL_ENTRY(ACC_THWK_HD_RADIO,                      0x03, "")
        CONST_TBL_ENTRY(ACC_THWK_HD_ADVANCED,                   0x05, "")
        CONST_TBL_ENTRY(ACC_THWK_HD_HIFI,                       0x06, "")
        CONST_TBL_ENTRY(ACC_THWK_NO_INFORMATION,                0xFC, "")
        CONST_TBL_ENTRY(ACC_THWK_NOT_READY,                     0xFE, "")
        CONST_TBL_ENTRY(ACC_THWK_UNSUPPORTED,                   0xFD, "")
        CONST_TBL_ENTRY(ACC_THWK_NOT_CONNECTED,                 0xFF, "")
    CONST_TBL_END

    CONST_TBL_BEGIN(ACC_THWK_SUB_TYPE_HF, 8, BE, "000.045", "")
        CONST_TBL_ENTRY(ACC_THWK_HF_BASIC,                      0x00, "")
        CONST_TBL_ENTRY(ACC_THWK_HF_ADVANCED,                   0x01, "")
        CONST_TBL_ENTRY(ACC_THWK_HF_STEREO_OFFICE,              0x02, "")
        CONST_TBL_ENTRY(ACC_THWK_NO_INFORMATION,            0xFC, "")
        CONST_TBL_ENTRY(ACC_THWK_NOT_READY,                     0xFE, "")
        CONST_TBL_ENTRY(ACC_THWK_UNSUPPORTED,                   0xFD, "")
        CONST_TBL_ENTRY(ACC_THWK_NOT_CONNECTED,                 0xFF, "")
    CONST_TBL_END

    CONST_TBL_BEGIN(ACC_THWK_SUB_TYPE_DC, 8, BE, "000.045", "")
        CONST_TBL_ENTRY(ACC_THWK_DC_RS232,                      0x00, "")
        CONST_TBL_ENTRY(ACC_THWK_DC_USB,                        0x01, "")
        CONST_TBL_ENTRY(ACC_THWK_NO_INFORMATION,                0xFC, "")
        CONST_TBL_ENTRY(ACC_THWK_NOT_READY,                     0xFE, "")
        CONST_TBL_ENTRY(ACC_THWK_UNSUPPORTED,                   0xFD, "")
        CONST_TBL_ENTRY(ACC_THWK_NOT_CONNECTED,                 0xFF, "")
    CONST_TBL_END

    CONST_TBL_BEGIN(ACC_THWK_SUB_TYPE_TD, 8, BE, "000.045", "")
        CONST_TBL_ENTRY(ACC_THWK_TD_AUDIO,                      0x00, "")
        CONST_TBL_ENTRY(ACC_THWK_NO_INFORMATION,                0xFC, "")
        CONST_TBL_ENTRY(ACC_THWK_NOT_READY,                     0xFE, "")
        CONST_TBL_ENTRY(ACC_THWK_UNSUPPORTED,                   0xFD, "")
        CONST_TBL_ENTRY(ACC_THWK_NOT_CONNECTED,                 0xFF, "")
    CONST_TBL_END

    CONST_TBL_BEGIN(ACC_THWK_SUB_TYPE_CAM, 8, BE, "000.045", "")
        CONST_TBL_ENTRY(ACC_THWK_CAM_HEADSET,                   0x00, "")
        CONST_TBL_ENTRY(ACC_THWK_NO_INFORMATION,                0xFC, "")
        CONST_TBL_ENTRY(ACC_THWK_NOT_READY,                     0xFE, "")
        CONST_TBL_ENTRY(ACC_THWK_UNSUPPORTED,                   0xFD, "")
        CONST_TBL_ENTRY(ACC_THWK_NOT_CONNECTED,                 0xFF, "")
    CONST_TBL_END

    CONST_TBL_BEGIN(ACC_THWK_SUB_TYPE_MISC, 8, BE, "000.045", "")
        CONST_TBL_ENTRY(ACC_THWK_MISC_FLASH_LIGHT,              0x00, "")
        CONST_TBL_ENTRY(ACC_THWK_NO_INFORMATION,                0xFC, "")
        CONST_TBL_ENTRY(ACC_THWK_NOT_READY,                     0xFE, "")
        CONST_TBL_ENTRY(ACC_THWK_UNSUPPORTED,                   0xFD, "")
        CONST_TBL_ENTRY(ACC_THWK_NOT_CONNECTED,                 0xFF, "")
    CONST_TBL_END
    
    CONST_TBL_BEGIN(ACC_THWK_SUB_TYPE_ADAPTER, 8, BE, "000.045", "")
        CONST_TBL_ENTRY(ACC_THWK_ADA_REMOTE,                    0x00, "")
        CONST_TBL_ENTRY_VER(ACC_THWK_ADA_TVOUT,                 0x01, "000.048", "")
        CONST_TBL_ENTRY(ACC_THWK_LINEIN,                        0x03, "")
        CONST_TBL_ENTRY(ACC_THWK_NO_INFORMATION,                0xFC, "")
        CONST_TBL_ENTRY(ACC_THWK_NOT_READY,                     0xFE, "")
        CONST_TBL_ENTRY(ACC_THWK_UNSUPPORTED,                   0xFD, "")
        CONST_TBL_ENTRY(ACC_THWK_NOT_CONNECTED,                 0xFF, "")
    CONST_TBL_END
    
    CONST_TBL_BEGIN(ACC_THWK_SUB_TYPE_NO_INFORMATION, 8, BE, "000.045", "")
        CONST_TBL_ENTRY(ACC_THWK_NO_INFORMATION,                0xFC, "")
    CONST_TBL_END

    
    /* Bit tables */
    
    BIT_TBL_BEGIN(ACC_THWK_INFO_FEATURE_ID, 16, BE, "000.045", "")
        BIT_TBL_ENTRY("0000000000000000", ACC_THWK_NO_FEATURE, "")
        BIT_TBL_ENTRY("XXXXXXXXXXXXXXX1", ACC_THWK_PLAY_PAUSE_KEY, "")
        BIT_TBL_ENTRY("XXXXXXXXXXXXXX1X", ACC_THWK_STOP_KEY, "")
        BIT_TBL_ENTRY("XXXXXXXXXXXXX1XX", ACC_THWK_VOLUME_UP, "")
        BIT_TBL_ENTRY("XXXXXXXXXXXX1XXX", ACC_THWK_VOLUME_DOWN, "")
        BIT_TBL_ENTRY("XXXXXXXXXXX1XXXX", ACC_THWK_FLASH_READY_ON, "")
        BIT_TBL_ENTRY("XXXXXXXXXX1XXXXX", ACC_THWK_LONG_HOOK, "")
        BIT_TBL_ENTRY("XXXXXXXXX1XXXXXX", ACC_THWK_CAMERA_LENS_COVER_ON, "")
        BIT_TBL_ENTRY("XXXXXXXX1XXXXXXX", ACC_THWK_HD_PLUG_ON, "")
        BIT_TBL_ENTRY("XXXXXXX1XXXXXXXX", ACC_THWK_SYNC_BTN_ON, "")
        BIT_TBL_ENTRY("XXXXXX1XXXXXXXXX", ACC_THWK_DTR_ON, "")
        BIT_TBL_ENTRY("XXXXX1XXXXXXXXXX", ACC_THWK_RTS_ON, "")
        BIT_TBL_ENTRY("XXXX1XXXXXXXXXXX", ACC_THWK_POWER_SUPPLY_ON, "")
        BIT_TBL_ENTRY("XXX1XXXXXXXXXXXX", ACC_THWK_HOOK_ON, "")
        BIT_TBL_ENTRY("XX1XXXXXXXXXXXXX", ACC_THWK_IGNITION_SENSE_ON, "")
        BIT_TBL_ENTRY("X1XXXXXXXXXXXXXX", ACC_THWK_EXT_AUDIO_IN, "")
        BIT_TBL_ENTRY("1XXXXXXXXXXXXXXX", ACC_THWK_ANSWER_END, "")
    BIT_TBL_END
    
    BIT_TBL_BEGIN(ACC_THWK_INFO_FEATURE2_ID, 8, BE, "000.045", "")
        BIT_TBL_ENTRY("00000000", ACC_THWK_NO_FEATURE, "")
        BIT_TBL_ENTRY("XXXXXXX1", ACC_THWK_BACK_KEY, "")
        BIT_TBL_ENTRY("XXXXXX1X", ACC_THWK_FORWARD_KEY, "")
        BIT_TBL_ENTRY("XXXXX1XX", ACC_THWK_LONG_BACK_KEY, "")
        BIT_TBL_ENTRY("XXXX1XXX", ACC_THWK_LONG_FORWARD_KEY, "")
    BIT_TBL_END


    BIT_TBL_BEGIN(ACC_THWK_EXEC_FEATURE_ID, 16, BE, "000.045", "")
        BIT_TBL_ENTRY("0000000000000000", ACC_THWK_NO_FEATURE, "")
        BIT_TBL_ENTRY_VER("XXXXXXXXXXXXXX1X", ACC_THWK_FLASH_LOW_POWER_ON, "000.047", "")
        BIT_TBL_ENTRY("XXXXXXXXXXXXX1XX", ACC_THWK_VIDEO_LIGHT_ON, "")
        BIT_TBL_ENTRY("XXXXXXXXXXXX1XXX", ACC_THWK_FLASH_ACTIVATION_ON, "")
        BIT_TBL_ENTRY("XXXXXXXXXXX1XXXX", ACC_THWK_CAMERA_MODULE_ON, "")
        BIT_TBL_ENTRY("XXXXXXXXXX1XXXXX", ACC_THWK_DCD_ON, "")
        BIT_TBL_ENTRY("XXXXXXXXX1XXXXXX", ACC_THWK_RI_ON, "")
        BIT_TBL_ENTRY("XXXXXXXX1XXXXXXX", ACC_THWK_DSR_ON, "")
        BIT_TBL_ENTRY("XXXXXXX1XXXXXXXX", ACC_THWK_CTS_ON, "")
        BIT_TBL_ENTRY("XXXXXX1XXXXXXXXX", ACC_THWK_HANDSET_AUDIO_ON, "")
        BIT_TBL_ENTRY("XXXXX1XXXXXXXXXX", ACC_THWK_CHARGER_ON, "")
        BIT_TBL_ENTRY("XXXX1XXXXXXXXXXX", ACC_THWK_POWER_ON, "")
        BIT_TBL_ENTRY("XXX1XXXXXXXXXXXX", ACC_THWK_CAR_RADIO_MUTE_ON, "")
        BIT_TBL_ENTRY("XX1XXXXXXXXXXXXX", ACC_THWK_MUTE_ON, "")
        BIT_TBL_ENTRY("X1XXXXXXXXXXXXXX", ACC_THWK_EXT_AUDIO_IN_ON, "")
        BIT_TBL_ENTRY("1XXXXXXXXXXXXXXX", ACC_THWK_AUD_AMP_ON, "")
    BIT_TBL_END
    
    /* Sequences */
  
    SEQ_BEGIN(ACC_AUDIO_BLOCK_DATA, DONT_CREATE_STRUCT, "000.045", "")
      VALUE(8, BE, data, "Data", HEX)
    SEQ_END


    /* Sub blocks */

    PROPERTY_STRING(PROPERTY_ISIHDR_STRUCT_NAME, "tACC_SB_ThwkExecFeature")
    PROPERTY_STRING(PROPERTY_ISIHDR_STRUCT_LENGTH_NAME, "ACC_SB_THWK_EXEC_FEATURE_LEN")
    SB_BEGIN(ACC_SB_THWK_EXEC_FEATURE, "000.045", "")
        ACC_SHARED_SB
        PROPERTY(PROPERTY_PMD_PARAMETER)
        VALUE_CONST(fea_id, "FeatureID", ACC_THWK_EXEC_FEATURE_ID)
        PROPERTY(PROPERTY_PMD_PARAMETER)
        VALUE_CONST(fea_state, "FeatureState", ACC_THWK_EXEC_FEATURE_ID)
        FILLER_EX(reserved1, 8, 1)
        FILLER_EX(reserved2, 8, 1)
    SB_END

    PROPERTY_STRING(PROPERTY_ISIHDR_STRUCT_NAME, "tACC_SB_ThwkInfoFeature")
    PROPERTY_STRING(PROPERTY_ISIHDR_STRUCT_LENGTH_NAME, "ACC_SB_THWK_INFO_FEATURE_LEN")
    SB_BEGIN(ACC_SB_THWK_INFO_FEATURE, "000.045", "")
        ACC_SHARED_SB
        PROPERTY(PROPERTY_PMD_PARAMETER)
        VALUE_CONST(fea_id, "FeatureID", ACC_THWK_INFO_FEATURE_ID)
        PROPERTY(PROPERTY_PMD_PARAMETER)
        VALUE_CONST(fea_state, "FeatureState", ACC_THWK_INFO_FEATURE_ID)
        PROPERTY(PROPERTY_PMD_PARAMETER)
        VALUE_CONST(fea2_id, "Feature2ID", ACC_THWK_INFO_FEATURE2_ID)
        PROPERTY(PROPERTY_PMD_PARAMETER)
        VALUE_CONST(fea2_state, "Feature2State", ACC_THWK_INFO_FEATURE2_ID)
    SB_END

    PROPERTY_STRING(PROPERTY_ISIHDR_STRUCT_NAME, "tACC_SB_ThwkAudioBlock")
    PROPERTY_STRING(PROPERTY_ISIHDR_STRUCT_LENGTH_NAME, "ACC_SB_THWK_AUDIO_BLOCK_LEN")
    SB_BEGIN(ACC_SB_THWK_AUDIO_BLOCK, "000.045", "")
        ACC_SHARED_SB
        SEQ_OF(audio_block_data, "Audio Block Data", ACC_AUDIO_BLOCK_DATA, 15)
        FILLER_EX(reserved1, 8, 1)
        FILLER_EX(reserved2, 8, 1)
        FILLER_EX(reserved3, 8, 1)
    SB_END
    
RES_END


/*  5    DATA TYPES */

/*  6    CLASSES */

/*  7    OBJECTS */

/*  8    DATA STRUCTURES */

/*  9    FUNCTION PROTOTYPES */

#endif /* ACC_SHARED_ISI_M_H */
/*  End of file acc_shared_isi_m.h  */
