/*
NOKIA
R&D Copenhagen
CoreSW/Corleone









                autogen_def.c
                -------------
                SW Module






Project:          autogen

%name:            autogen_def.c %
%version:         co1tss#91 %
%instance:        co_pctls_1 %
%derived_by:      eliasen %
%date_modified:   Tue Apr 13 14:57:53 2010 %

Copyright (c) Nokia. All rights reserved
*/


/* ============================================================================================= */
/* Abstract */
/* ============================================================================================= */

/*  Source file for autogen

    The file contains initialization of global variables
*/


/* ============================================================================================= */
/* Includes */
/* ============================================================================================= */

#include "autogen_def.h"
#include "pmd_heap.h"

#include <stdlib.h>


/* ============================================================================================= */
/* Global definitions */
/* ============================================================================================= */

/* pointer to the list of resources in the data mode */
autogen_obj_list* g_res_list = NULL;

/* trace group counfigurations */
autogen_trcgrp_conf g_trcgrp_conf[AUTOGEN_OBJ_TRACEGRP_MAX] = 
{
     /* Index                              res,                      list, map,  has_grp, trace_entity_id_refname,     size  special_type                              trace_group_id_refname,      size   special_type,                             trace_id_refname,      size   special_type                        table, length, short, max_entities, n_entries, resource(s),                           anchor,                       conflicts  msg_type                                 Entity entry point subtree             Info type (for entry point)                 PMD classification */
    {/* AUTOGEN_OBJ_TRACEGRP_NONE       */ RESOURCE_UNKNOWN,         NULL, NULL, FALSE,   "",                          0,    0,                                        "",                          0,     0,                                        "",                    0,     0,                                  FALSE, 0,      FALSE, 1,            0,         0,                                     "",                           FALSE,     PMD_MESSAGE_TYPE_UNDEFINED,              0,                                     PMD_INFO_TYPE_NONE,                         0 },
    {/* AUTOGEN_OBJ_TRACEGRP_MCU        */ RESOURCE_TRC_MCU,         NULL, NULL, TRUE,    "",                          0,    0,                                        "TRACE_GROUP_ID",           16,     PMD_NUMBER_SPECIAL_TYPE_TRACE_GROUP_ID,   "TRACE_ID",           16,     PMD_NUMBER_SPECIAL_TYPE_TRACE_ID,   TRUE,  16,     TRUE,  1,            0,         RESOURCE_TRC_MCU | RESOURCE_ISI,       "MCU_TRACE_STRUCTURE",        FALSE,     PMD_MESSAGE_TYPE_MCU_TRACE,              0,                                     PMD_INFO_TYPE_NONE,                         0 },
    {/* AUTOGEN_OBJ_TRACEGRP_SYMBIAN    */ RESOURCE_TRC_SYMBIAN,     NULL, NULL, TRUE,    "TRACE_ENTITY_ID_SYMBIAN",  32,    PMD_NUMBER_SPECIAL_TYPE_PRINTF_ID,        "TRACE_GROUP_ID_SYMBIAN",   16,     PMD_NUMBER_SPECIAL_TYPE_TRACE_GROUP_ID,   "TRACE_ID_SYMBIAN",   16,     PMD_NUMBER_SPECIAL_TYPE_TRACE_ID,   FALSE, 0,      FALSE, 1024,         0,         RESOURCE_TRC_SYMBIAN | RESOURCE_ISI,   "SYMBIAN_TRACE_STRUCTURE",    FALSE,     PMD_MESSAGE_TYPE_SYMBIAN_TRACE,          PMD_ENTRY_POINT_SYMBIAN_TRACE_ENTITY,  PMD_INFO_TYPE_SYMBIAN_COMPONENT_IDS,        0 },
    {/* AUTOGEN_OBJ_TRACEGRP_INVARIANT  */ RESOURCE_TRC_INVARIANT,   NULL, NULL, TRUE,    "TRACE_ENTITY_ID_INVARIANT", 8,    PMD_NUMBER_SPECIAL_TYPE_TRACE_ENTITY_ID,  "TRACE_GROUP_ID_INVARIANT",  8,     PMD_NUMBER_SPECIAL_TYPE_TRACE_GROUP_ID,   "TRACE_ID_INVARIANT",  8,     PMD_NUMBER_SPECIAL_TYPE_TRACE_ID,   FALSE, 16,     FALSE, 16,           0,         RESOURCE_TRC_INVARIANT,                "INVARIANT_TRACE_STRUCTURE",  FALSE,     PMD_MESSAGE_TYPE_INVARIANT_TRACE,        PMD_ENTRY_POINT_INVARIANT_TRACE_ENTITY,PMD_INFO_TYPE_INVARIANT_TRACE_ENTITY_IDS,   AUTOGEN_PMD_FILE_RESTRICTION_ANY },
    {/* AUTOGEN_OBJ_TRACEGRP_OS         */ RESOURCE_TRC_OS,          NULL, NULL, TRUE,    "",                          0,    0,                                        "",                          0,     0,                                        "TRACE_ID_OS",         8,     PMD_NUMBER_SPECIAL_TYPE_TRACE_ID,   FALSE, 0,      FALSE, 1,            0,         RESOURCE_TRC_OS,                       "OS_TRACE_STRUCTURE",         FALSE,     PMD_MESSAGE_TYPE_OS_TRACE,               0,                                     PMD_INFO_TYPE_NONE,                         0 },
    {/* AUTOGEN_OBJ_TRACEGRP_HAL        */ RESOURCE_TRC_HAL,         NULL, NULL, TRUE,    "",                          0,    0,                                        "TRACE_GROUP_ID_HAL",        8,     PMD_NUMBER_SPECIAL_TYPE_TRACE_GROUP_ID,   "TRACE_ID_HAL",        8,     PMD_NUMBER_SPECIAL_TYPE_TRACE_ID,   FALSE, 0,      FALSE, 1,            0,         RESOURCE_TRC_HAL,                      "HAL_TRACE_STRUCTURE",        FALSE,     PMD_MESSAGE_TYPE_HAL_TRACE,              0,                                     PMD_INFO_TYPE_NONE,                         0 },
    {/* AUTOGEN_OBJ_TRACEGRP_CDSP5 */      RESOURCE_TRC_CDSP5,       NULL, NULL, TRUE,    "TRACE_ENTITY_ID_CDSP5",    16,    PMD_NUMBER_SPECIAL_TYPE_TRACE_ENTITY_ID,  "TRACE_GROUP_ID_CDSP5",     16,     PMD_NUMBER_SPECIAL_TYPE_TRACE_GROUP_ID,   "TRACE_ID_CDSP5",     16,     PMD_NUMBER_SPECIAL_TYPE_TRACE_ID,   FALSE, 0,      FALSE, 256,          0,         RESOURCE_TRC_CDSP5,                    "CDSP5_TRACE_STRUCTURE",      FALSE,     PMD_MESSAGE_TYPE_CDSP5_TRACE,            PMD_ENTRY_POINT_CDSP5_TRACE_ENTITY,    PMD_INFO_TYPE_CDSP_TRACE_ENTITY_IDS,        0 },
	{/* AUTOGEN_OBJ_TRACEGRP_ADSP5 */      RESOURCE_TRC_ADSP5,       NULL, NULL, TRUE,    "TRACE_ENTITY_ID_ADSP5",    16,    PMD_NUMBER_SPECIAL_TYPE_TRACE_ENTITY_ID,  "TRACE_GROUP_ID_ADSP5",     16,     PMD_NUMBER_SPECIAL_TYPE_TRACE_GROUP_ID,   "TRACE_ID_ADSP5",     16,     PMD_NUMBER_SPECIAL_TYPE_TRACE_ID,   FALSE, 0,      FALSE, 256,          0,         RESOURCE_TRC_ADSP5,                    "ADSP5_TRACE_STRUCTURE",      FALSE,     PMD_MESSAGE_TYPE_ADSP5_TRACE,            PMD_ENTRY_POINT_ADSP5_TRACE_ENTITY,    PMD_INFO_TYPE_ADSP_TRACE_ENTITY_IDS,        0 },
    {/* AUTOGEN_OBJ_TRACEGRP_VENDOR */     RESOURCE_TRC_VENDOR,      NULL, NULL, TRUE,    "TRACE_ENTITY_ID_VENDOR",    8,    PMD_NUMBER_SPECIAL_TYPE_TRACE_ENTITY_ID,  "TRACE_GROUP_ID_VENDOR",     8,     PMD_NUMBER_SPECIAL_TYPE_TRACE_GROUP_ID,   "TRACE_ID_VENDOR",     8,     PMD_NUMBER_SPECIAL_TYPE_TRACE_ID,   FALSE, 0,      FALSE, 16,           0,         RESOURCE_TRC_VENDOR,                   "VENDOR_COMPONENT_TRACE_STRUCTURE",FALSE,PMD_MESSAGE_TYPE_VENDOR_COMPONENT_TRACE, PMD_ENTRY_POINT_VENDOR_COMPONENT_TRACE_ENTITY,   PMD_INFO_TYPE_VENDOR_COMPONENT_TRACE_ENTITY_IDS,      0 },
    {/* AUTOGEN_OBJ_TRACEGRP_MASTER */     RESOURCE_TRC_MASTER,      NULL, NULL, FALSE,   "",                          0,    0,                                        "",                          0,     0,                                        "TRACE_ID_MASTER",     8,     PMD_NUMBER_SPECIAL_TYPE_TRACE_ID,   FALSE, 0,      FALSE, 1,            0,         RESOURCE_TRC_MASTER,                   "XTI_MASTER_STRUCTURE",       FALSE,     PMD_MESSAGE_TYPE_UNDEFINED,              PMD_ENTRY_POINT_XTI_MASTER,            PMD_INFO_TYPE_XTI_MASTER_IDS,               AUTOGEN_PMD_FILE_RESTRICTION_ANY },
    {/* AUTOGEN_OBJ_TRACEGRP_HSP        */ RESOURCE_TRC_HSP,         NULL, NULL, TRUE,    "",                          0,    0,                                        "TRACE_GROUP_ID_HSP",        8,     PMD_NUMBER_SPECIAL_TYPE_TRACE_GROUP_ID,   "TRACE_ID_HSP",        8,     PMD_NUMBER_SPECIAL_TYPE_TRACE_ID,   FALSE, 0,      FALSE, 1,            0,         RESOURCE_TRC_HSP,                      "HSP_TRACE_STRUCTURE",        FALSE,     PMD_MESSAGE_TYPE_HSP_TRACE,              0 },
};

/* resource counfigurations */
autogen_res_conf g_res_conf[AUTOGEN_RESOURCE_TYPES_MAX] = 
{
   /* type                             res sel, extension type,                  device id                  unique msg_id size            msg_id offset          submsg_id size         submsg_id offset       msg_length size        msg_length offset      pmd_msg_type                                 msg_type flag                     anchor                         xml_name */
    { RESOURCE_UNKNOWN,                FALSE,   0,                               AUTOGEN_DEVICE_CURRENT,    FALSE, AUTOGEN_VALUE_VARIES,  AUTOGEN_VALUE_VARIES,  AUTOGEN_VALUE_VARIES,  AUTOGEN_VALUE_VARIES,  AUTOGEN_VALUE_VARIES,  AUTOGEN_VALUE_VARIES,  PMD_MESSAGE_TYPE_UNDEFINED,                  0,                                "",                            NULL },
    { RESOURCE_SYMBOLS,                FALSE,   0,                               AUTOGEN_DEVICE_CURRENT,    TRUE,  AUTOGEN_NOT_SUPPORTED, AUTOGEN_NOT_SUPPORTED, AUTOGEN_NOT_SUPPORTED, AUTOGEN_NOT_SUPPORTED, AUTOGEN_NOT_SUPPORTED, AUTOGEN_NOT_SUPPORTED, PMD_MESSAGE_TYPE_UNDEFINED,                  0,                                "",                            NULL },
    { RESOURCE_ISI,                    TRUE,    RESOURCE_ISI_EXTENSION,          AUTOGEN_DEVICE_GENERAL,    FALSE, 8,                     1,                     AUTOGEN_VALUE_VARIES,  2,                     AUTOGEN_NOT_SUPPORTED, AUTOGEN_NOT_SUPPORTED, PMD_MESSAGE_TYPE_ISI,                        PMD_MESSAGE_TYPE_FLAG_IS_MESSAGE, "",                            "ResourceIsi" },
    { RESOURCE_ISI_COMMON_MESSAGES,    FALSE,   0,                               AUTOGEN_DEVICE_GENERAL,    TRUE,  8,                     1,                     8,                     2,                     AUTOGEN_NOT_SUPPORTED, AUTOGEN_NOT_SUPPORTED, PMD_MESSAGE_TYPE_ISI,                        PMD_MESSAGE_TYPE_FLAG_IS_MESSAGE, "",                            "ResourceIsiCommon" },
    { RESOURCE_ISI_COMMON_MESSAGES_EXT,FALSE,   0,                               AUTOGEN_DEVICE_GENERAL,    TRUE,  8,                     1,                     8,                     4,                     AUTOGEN_NOT_SUPPORTED, AUTOGEN_NOT_SUPPORTED, PMD_MESSAGE_TYPE_ISI,                        PMD_MESSAGE_TYPE_FLAG_IS_MESSAGE, "",                            "ResourceIsiCommonExtension" },
    { RESOURCE_ISI_DSP,                TRUE,    0,                               AUTOGEN_DEVICE_GENERAL,    FALSE, 8,                     1,                     8,                     2,                     AUTOGEN_NOT_SUPPORTED, AUTOGEN_NOT_SUPPORTED, PMD_MESSAGE_TYPE_ISI,                        PMD_MESSAGE_TYPE_FLAG_IS_MESSAGE, "",                            "ResourceIsi" },
    /* RESOURCE_ISI_GSM_DSP_TEST is obsolete... */
    { RESOURCE_ISI_GSM_DSP_TEST,       FALSE,   0,                               PN_DEV_DSP_MAIN,           TRUE,  8,                     1,                     8,                     2,                     AUTOGEN_NOT_SUPPORTED, AUTOGEN_NOT_SUPPORTED, PMD_MESSAGE_TYPE_ISI,                        PMD_MESSAGE_TYPE_FLAG_IS_MESSAGE, "",                            NULL },
    { RESOURCE_ISI_MEDIA_CONTROL,      TRUE,    0,                               AUTOGEN_DEVICE_GENERAL,    TRUE,  8,                     1,                     8,                     2,                     AUTOGEN_NOT_SUPPORTED, AUTOGEN_NOT_SUPPORTED, PMD_MESSAGE_TYPE_ISI,                        PMD_MESSAGE_TYPE_FLAG_IS_MESSAGE, "",                            "ResourceIsi" },
    { RESOURCE_ISI_PREFIX,             FALSE,   0,                               AUTOGEN_DEVICE_GENERAL,    FALSE, 8,                     1,                     8,                     4,                     AUTOGEN_NOT_SUPPORTED, AUTOGEN_NOT_SUPPORTED, PMD_MESSAGE_TYPE_ISI,                        PMD_MESSAGE_TYPE_FLAG_IS_MESSAGE, "",                            "ResourceIsiPrefix" },
    { RESOURCE_ISI_PRIVATE,            FALSE,   0,                               AUTOGEN_DEVICE_GENERAL,    FALSE, 8,                     1,                     8,                     4,                     AUTOGEN_NOT_SUPPORTED, AUTOGEN_NOT_SUPPORTED, PMD_MESSAGE_TYPE_ISI_PRIVATE,                PMD_MESSAGE_TYPE_FLAG_IS_MESSAGE, "",                            "ResourceIsiPrivate" },
    { RESOURCE_ISI_EXTENSION,          TRUE,    0,                               AUTOGEN_DEVICE_GENERAL,    FALSE, 8,                     1,                     AUTOGEN_VALUE_VARIES,  2,                     AUTOGEN_NOT_SUPPORTED, AUTOGEN_NOT_SUPPORTED, PMD_MESSAGE_TYPE_ISI,                        PMD_MESSAGE_TYPE_FLAG_IS_MESSAGE, "",                            "ResourceIsiExtension" },
    { RESOURCE_MEDIA_MODULE,           FALSE,   RESOURCE_MEDIA_MODULE_EXTENSION, AUTOGEN_DEVICE_GENERAL,    FALSE, 8,                     0,                     8,                     1,                     AUTOGEN_NOT_SUPPORTED, AUTOGEN_NOT_SUPPORTED, PMD_MESSAGE_TYPE_MEDIA_MODULE,               PMD_MESSAGE_TYPE_FLAG_IS_MESSAGE, "",                            "ResourceMediaModule" },
    { RESOURCE_MEDIA_MODULE_EXTENSION, FALSE,   0,                               AUTOGEN_DEVICE_GENERAL,    FALSE, 8,                     0,                     8,                     1,                     AUTOGEN_NOT_SUPPORTED, AUTOGEN_NOT_SUPPORTED, PMD_MESSAGE_TYPE_MEDIA_MODULE,               PMD_MESSAGE_TYPE_FLAG_IS_MESSAGE, "",                            "ResourceMediaModuleExtension" },
    { RESOURCE_PHONET,                 FALSE,   0,                               AUTOGEN_DEVICE_GENERAL,    FALSE, 8,                     0,                     8,                     1,                     AUTOGEN_NOT_SUPPORTED, AUTOGEN_NOT_SUPPORTED, PMD_MESSAGE_TYPE_PHONET_,                    PMD_MESSAGE_TYPE_FLAG_IS_MESSAGE, "",                            "ResourcePhonet" },
    { RESOURCE_PHONET_EXT,             TRUE,    0,                               AUTOGEN_DEVICE_GENERAL,    FALSE, 8,                     0,                     8,                     1,                     AUTOGEN_NOT_SUPPORTED, AUTOGEN_NOT_SUPPORTED, PMD_MESSAGE_TYPE_PHONET_EXT,                 PMD_MESSAGE_TYPE_FLAG_IS_MESSAGE, "",                            "ResourcePhonetExtended" },
    { RESOURCE_TRC_SYMBIAN,            FALSE,   0,                               PN_DEV_SOS,                FALSE, AUTOGEN_NOT_SUPPORTED, AUTOGEN_NOT_SUPPORTED, AUTOGEN_NOT_SUPPORTED, AUTOGEN_NOT_SUPPORTED, AUTOGEN_NOT_SUPPORTED, AUTOGEN_NOT_SUPPORTED, PMD_MESSAGE_TYPE_SYMBIAN_TRACE,              PMD_MESSAGE_TYPE_FLAG_IS_TRACE,   "",                            "ResourceTraceSymbian" },
    { RESOURCE_TRC_INVARIANT,          FALSE,   0,                               AUTOGEN_DEVICE_GENERAL,    FALSE, AUTOGEN_NOT_SUPPORTED, AUTOGEN_NOT_SUPPORTED, AUTOGEN_NOT_SUPPORTED, AUTOGEN_NOT_SUPPORTED, AUTOGEN_NOT_SUPPORTED, AUTOGEN_NOT_SUPPORTED, PMD_MESSAGE_TYPE_INVARIANT_TRACE_FIRST,      PMD_MESSAGE_TYPE_FLAG_IS_TRACE,   "",                            "ResourceInvariantTraces" },
    { RESOURCE_TRC_VENDOR,             FALSE,   0,                               AUTOGEN_DEVICE_CURRENT,    FALSE, AUTOGEN_NOT_SUPPORTED, AUTOGEN_NOT_SUPPORTED, AUTOGEN_NOT_SUPPORTED, AUTOGEN_NOT_SUPPORTED, AUTOGEN_NOT_SUPPORTED, AUTOGEN_NOT_SUPPORTED, PMD_MESSAGE_TYPE_VENDOR_COMPONENT_TRACE,     PMD_MESSAGE_TYPE_FLAG_IS_TRACE,   "",                            "ResourceVendorComponentTraces" },
    { RESOURCE_TRC_MCU,                FALSE,   0,                               AUTOGEN_DEVICE_CURRENT,    FALSE, AUTOGEN_NOT_SUPPORTED, AUTOGEN_NOT_SUPPORTED, AUTOGEN_NOT_SUPPORTED, AUTOGEN_NOT_SUPPORTED, AUTOGEN_NOT_SUPPORTED, AUTOGEN_NOT_SUPPORTED, PMD_MESSAGE_TYPE_MCU_TRACE,                  PMD_MESSAGE_TYPE_FLAG_IS_TRACE,   "MCU_TRACE_STRUCTURE",         "ResourceTraceMcu" },
    { RESOURCE_TRC_DSP5_ADSP,          FALSE,   0,                               PN_DEV_DSP_AUX,            TRUE,  AUTOGEN_NOT_SUPPORTED, AUTOGEN_NOT_SUPPORTED, AUTOGEN_NOT_SUPPORTED, AUTOGEN_NOT_SUPPORTED, AUTOGEN_NOT_SUPPORTED, AUTOGEN_NOT_SUPPORTED, PMD_MESSAGE_TYPE_DSP5_ADSP_FIRST,            PMD_MESSAGE_TYPE_FLAG_IS_TRACE,   "DSP5_ADSP_TRACE_STRUCTURE",   "ResourceTraceDsp5Adsp" },
    { RESOURCE_TRC_DSP5_CDSP,          FALSE,   0,                               PN_DEV_DSP_MAIN,           TRUE,  AUTOGEN_NOT_SUPPORTED, AUTOGEN_NOT_SUPPORTED, AUTOGEN_NOT_SUPPORTED, AUTOGEN_NOT_SUPPORTED, AUTOGEN_NOT_SUPPORTED, AUTOGEN_NOT_SUPPORTED, PMD_MESSAGE_TYPE_DSP5_CDSP_FIRST,            PMD_MESSAGE_TYPE_FLAG_IS_TRACE,   "DSP5_TRACE_STRUCTURE",        "ResourceTraceDsp5Cdsp" },
    { RESOURCE_TRC_STI,                FALSE,   0,                               PN_DEV_TRACEBOX,           FALSE, 8,                     1,                     8,                     2,                     AUTOGEN_NOT_SUPPORTED, AUTOGEN_NOT_SUPPORTED, PMD_MESSAGE_TYPE_STI_TRACE,                  PMD_MESSAGE_TYPE_FLAG_IS_TRACE,   "OS_DSP_TRACE_STRUCTURE",      "ResourceTraceSti" },
    { RESOURCE_TRC_OS,                 FALSE,   0,                               AUTOGEN_DEVICE_CURRENT,    TRUE,  AUTOGEN_NOT_SUPPORTED, AUTOGEN_NOT_SUPPORTED, AUTOGEN_NOT_SUPPORTED, AUTOGEN_NOT_SUPPORTED, AUTOGEN_NOT_SUPPORTED, AUTOGEN_NOT_SUPPORTED, PMD_MESSAGE_TYPE_OS_TRACE,                   PMD_MESSAGE_TYPE_FLAG_IS_TRACE,   "",                            "ResourceTraceOs" },
    { RESOURCE_TRC_HAL,                FALSE,   0,                               AUTOGEN_DEVICE_CURRENT,    TRUE,  AUTOGEN_NOT_SUPPORTED, AUTOGEN_NOT_SUPPORTED, AUTOGEN_NOT_SUPPORTED, AUTOGEN_NOT_SUPPORTED, AUTOGEN_NOT_SUPPORTED, AUTOGEN_NOT_SUPPORTED, PMD_MESSAGE_TYPE_HAL_TRACE,                  PMD_MESSAGE_TYPE_FLAG_IS_TRACE,   "",                            "ResourceTraceHal" },
    { RESOURCE_TRC_MASTER,             FALSE,   0,                               AUTOGEN_DEVICE_GENERAL,    TRUE,  AUTOGEN_NOT_SUPPORTED, AUTOGEN_NOT_SUPPORTED, AUTOGEN_NOT_SUPPORTED, AUTOGEN_NOT_SUPPORTED, AUTOGEN_NOT_SUPPORTED, AUTOGEN_NOT_SUPPORTED, PMD_MESSAGE_TYPE_MASTER_TRACE,               PMD_MESSAGE_TYPE_FLAG_IS_TRACE,   "",                            "ResourceTraceMaster" },
    { RESOURCE_PROTOCOL,               FALSE,   RESOURCE_PROTOCOL_EXTENSION,     AUTOGEN_DEVICE_GENERAL,    FALSE, AUTOGEN_VALUE_VARIES,  AUTOGEN_VALUE_VARIES,  AUTOGEN_VALUE_VARIES,  AUTOGEN_VALUE_VARIES,  AUTOGEN_VALUE_VARIES,  AUTOGEN_VALUE_VARIES,  PMD_MESSAGE_TYPE_PROTOCOL,                   PMD_MESSAGE_TYPE_FLAG_IS_MESSAGE, "",                            "ResourceGenericProtocol" },
    { RESOURCE_PROTOCOL_EXTENSION,     FALSE,   0,                               AUTOGEN_DEVICE_GENERAL,    FALSE, AUTOGEN_VALUE_VARIES,  AUTOGEN_VALUE_VARIES,  AUTOGEN_VALUE_VARIES,  AUTOGEN_VALUE_VARIES,  AUTOGEN_VALUE_VARIES,  AUTOGEN_VALUE_VARIES,  PMD_MESSAGE_TYPE_PROTOCOL,                   PMD_MESSAGE_TYPE_FLAG_IS_MESSAGE, "",                            "ResourceGenericProtocolExtension" },
    { RESOURCE_SHARED,                 FALSE,   0,                               AUTOGEN_DEVICE_CURRENT,    FALSE, AUTOGEN_NOT_SUPPORTED, AUTOGEN_NOT_SUPPORTED, AUTOGEN_NOT_SUPPORTED, AUTOGEN_NOT_SUPPORTED, AUTOGEN_NOT_SUPPORTED, AUTOGEN_NOT_SUPPORTED, PMD_MESSAGE_TYPE_UNDEFINED,                  0,                                "",                            "ResourceShared" },
    { RESOURCE_TRC_CDSP5,              FALSE,   0,                               PN_DEV_DSP_MAIN,           FALSE, AUTOGEN_NOT_SUPPORTED, AUTOGEN_NOT_SUPPORTED, AUTOGEN_NOT_SUPPORTED, AUTOGEN_NOT_SUPPORTED, AUTOGEN_NOT_SUPPORTED, AUTOGEN_NOT_SUPPORTED, PMD_MESSAGE_TYPE_DSP5_CDSP_FIRST,            PMD_MESSAGE_TYPE_FLAG_IS_TRACE,   "CDSP5_TRACE_STRUCTURE",       "ResourceTraceCdsp5" },
    { RESOURCE_TRC_ADSP5,              FALSE,   0,                               PN_DEV_DSP_AUX,            FALSE, AUTOGEN_NOT_SUPPORTED, AUTOGEN_NOT_SUPPORTED, AUTOGEN_NOT_SUPPORTED, AUTOGEN_NOT_SUPPORTED, AUTOGEN_NOT_SUPPORTED, AUTOGEN_NOT_SUPPORTED, PMD_MESSAGE_TYPE_DSP5_ADSP_FIRST,            PMD_MESSAGE_TYPE_FLAG_IS_TRACE,   "ADSP5_TRACE_STRUCTURE",       "ResourceTraceAdsp5" },
    { RESOURCE_OST,                    FALSE,   0,                               AUTOGEN_DEVICE_GENERAL,    FALSE, AUTOGEN_VALUE_VARIES,  AUTOGEN_VALUE_VARIES,  AUTOGEN_VALUE_VARIES,  AUTOGEN_VALUE_VARIES,  AUTOGEN_NOT_SUPPORTED, AUTOGEN_NOT_SUPPORTED, PMD_MESSAGE_TYPE_OST,                        PMD_MESSAGE_TYPE_FLAG_IS_MESSAGE, "",                            "ResourceOst" },
    { RESOURCE_TRC_HSP,                FALSE,   0,                               AUTOGEN_DEVICE_CURRENT,    TRUE,  AUTOGEN_NOT_SUPPORTED, AUTOGEN_NOT_SUPPORTED, AUTOGEN_NOT_SUPPORTED, AUTOGEN_NOT_SUPPORTED, AUTOGEN_NOT_SUPPORTED, AUTOGEN_NOT_SUPPORTED, PMD_MESSAGE_TYPE_HSP_TRACE,                  PMD_MESSAGE_TYPE_FLAG_IS_TRACE,   "",                            "ResourceTraceHsp" },

};

/* global symbol table configuration */
autogen_symbol_conf g_symbol_conf[AUTOGEN_SYMBOL_TYPES_MAX] = 
{
   /* Type in isi_macros.h              name in VALUE_CONST                 symbol table                          size         device                  presentation flag                        PMD info type                       PMD constant configuration  #entries                           pmd flags                           xml_type_name     xml_const_name        xml_generate */
    { PN_RESOURCE,                      "PN_RESOURCE",                      "SYMBOLS_PN_RESOURCE",                 8,          AUTOGEN_DEVICE_GENERAL, AUTOGEN_PRESENTATION_PN_CONST,           PMD_INFO_TYPE_PN_RESOURCES,         NULL,                       0,                                 AUTOGEN_PMD_FILE_RESTRICTION_ANY,   "Constant",       "PhonetResource",     TRUE }, 
    { PN_MEDIA,                         "PN_MEDIA",                         "SYMBOLS_PN_MEDIA",                    8,          AUTOGEN_DEVICE_GENERAL, AUTOGEN_PRESENTATION_PN_CONST,           PMD_INFO_TYPE_PN_MEDIAS,            NULL,                       0,                                 AUTOGEN_PMD_FILE_RESTRICTION_ANY,   "Constant",       "PhonetMedia",        TRUE },
    { PN_DEVICE,                        "PN_DEVICE",                        "SYMBOLS_PN_DEVICE",                   8,          AUTOGEN_DEVICE_GENERAL, AUTOGEN_PRESENTATION_PN_CONST,           PMD_INFO_TYPE_PN_DEVICES,           NULL,                       0,                                 AUTOGEN_PMD_FILE_RESTRICTION_ANY,   "Constant",       "PhonetDevice",       TRUE },
    { PN_DEVICE_6,                      "PN_DEVICE_6",                      "SYMBOLS_PN_DEVICE_6",                 6,          AUTOGEN_DEVICE_GENERAL, AUTOGEN_PRESENTATION_PN_CONST,           PMD_INFO_TYPE_PN_DEVICES_6,         NULL,                       0,                                 0,                                  "Constant",       "PhonetDevice",       FALSE },
    { PN_OBJECT,                        "PN_OBJECT",                        "SYMBOLS_PN_OBJECT",                   8,          PN_DEV_HOST,            AUTOGEN_PRESENTATION_PN_CONST,           PMD_INFO_TYPE_PN_OBJECTS,           NULL,                       0,                                 0,                                  "Constant",       "PhonetObject",       FALSE },
    { PN_OBJECT_10,                     "PN_OBJECT_10",                     "SYMBOLS_PN_OBJECT_10",               10,          PN_DEV_HOST,            AUTOGEN_PRESENTATION_PN_CONST,           PMD_INFO_TYPE_PN_OBJECTS,           NULL,                       0,                                 0,                                  "Constant",       "PhonetObject",       FALSE },
    { PN_OBJECT_16,                     "PN_OBJECT_16",                     "SYMBOLS_PN_OBJECT_16",               16,          PN_DEV_HOST,            AUTOGEN_PRESENTATION_PN_CONST,           PMD_INFO_TYPE_PN_OBJECTS,           NULL,                       0,                                 0,                                  "Constant",       "PhonetObject",       FALSE },
    { YES_NO,                           "YES_NO",                           "SYMBOLS_YES_NO",                      8,          AUTOGEN_DEVICE_GENERAL, AUTOGEN_PRESENTATION_GLOBAL,             PMD_INFO_TYPE_NONE,                 NULL,                       0,                                 AUTOGEN_PMD_FILE_RESTRICTION_ANY,   "Constant",       "YesNo",              TRUE },
    { YES_NO_1,                         "YES_NO_1",                         "SYMBOLS_YES_NO_1",                    1,          AUTOGEN_DEVICE_GENERAL, AUTOGEN_PRESENTATION_GLOBAL,             PMD_INFO_TYPE_NONE,                 NULL,                       0,                                 AUTOGEN_PMD_FILE_RESTRICTION_ANY,   "Constant",       "YesNo",              FALSE },
    { YES_NO_16,                        "YES_NO_16",                        "SYMBOLS_YES_NO_16",                  16,          AUTOGEN_DEVICE_GENERAL, AUTOGEN_PRESENTATION_GLOBAL,             PMD_INFO_TYPE_NONE,                 NULL,                       0,                                 AUTOGEN_PMD_FILE_RESTRICTION_ANY,   "Constant",       "YesNo",              FALSE },
    { ON_OFF,                           "ON_OFF",                           "SYMBOLS_ON_OFF",                      8,          AUTOGEN_DEVICE_GENERAL, AUTOGEN_PRESENTATION_GLOBAL,             PMD_INFO_TYPE_NONE,                 NULL,                       0,                                 AUTOGEN_PMD_FILE_RESTRICTION_ANY,   "Constant",       "OnOff",              TRUE },
    { ON_OFF_1,                         "ON_OFF_1",                         "SYMBOLS_ON_OFF_1",                    1,          AUTOGEN_DEVICE_GENERAL, AUTOGEN_PRESENTATION_GLOBAL,             PMD_INFO_TYPE_NONE,                 NULL,                       0,                                 AUTOGEN_PMD_FILE_RESTRICTION_ANY,   "Constant",       "OnOff",              FALSE },
    { ON_OFF_16,                        "ON_OFF_16",                        "SYMBOLS_ON_OFF_16",                  16,          AUTOGEN_DEVICE_GENERAL, AUTOGEN_PRESENTATION_GLOBAL,             PMD_INFO_TYPE_NONE,                 NULL,                       0,                                 AUTOGEN_PMD_FILE_RESTRICTION_ANY,   "Constant",       "OnOff",              FALSE },
    { ENABLED_DISABLED,                 "ENABLED_DISABLED",                 "SYMBOLS_ENABLED_DISABLED",            8,          AUTOGEN_DEVICE_GENERAL, AUTOGEN_PRESENTATION_GLOBAL,             PMD_INFO_TYPE_NONE,                 NULL,                       0,                                 AUTOGEN_PMD_FILE_RESTRICTION_ANY,   "Constant",       "EnabledDisabled",    TRUE },
    { ENABLED_DISABLED_1,               "ENABLED_DISABLED_1",               "SYMBOLS_ENABLED_DISABLED_1",          1,          AUTOGEN_DEVICE_GENERAL, AUTOGEN_PRESENTATION_GLOBAL,             PMD_INFO_TYPE_NONE,                 NULL,                       0,                                 AUTOGEN_PMD_FILE_RESTRICTION_ANY,   "Constant",       "EnabledDisabled",    FALSE },
    { ENABLED_DISABLED_16,              "ENABLED_DISABLED_16",              "SYMBOLS_ENABLED_DISABLED_16",        16,          AUTOGEN_DEVICE_GENERAL, AUTOGEN_PRESENTATION_GLOBAL,             PMD_INFO_TYPE_NONE,                 NULL,                       0,                                 AUTOGEN_PMD_FILE_RESTRICTION_ANY,   "Constant",       "EnabledDisabled",    FALSE },
    { OK_FAIL,                          "OK_FAIL",                          "SYMBOLS_OK_FAIL",                     8,          AUTOGEN_DEVICE_GENERAL, AUTOGEN_PRESENTATION_GLOBAL,             PMD_INFO_TYPE_NONE,                 NULL,                       0,                                 AUTOGEN_PMD_FILE_RESTRICTION_ANY,   "Constant",       "OkFail",             TRUE },
    { OK_FAIL_1,                        "OK_FAIL_1",                        "SYMBOLS_OK_FAIL_1",                   1,          AUTOGEN_DEVICE_GENERAL, AUTOGEN_PRESENTATION_GLOBAL,             PMD_INFO_TYPE_NONE,                 NULL,                       0,                                 AUTOGEN_PMD_FILE_RESTRICTION_ANY,   "Constant",       "OkFail",             FALSE },
    { OK_FAIL_16,                       "OK_FAIL_16",                       "SYMBOLS_OK_FAIL_16",                 16,          AUTOGEN_DEVICE_GENERAL, AUTOGEN_PRESENTATION_GLOBAL,             PMD_INFO_TYPE_NONE,                 NULL,                       0,                                 AUTOGEN_PMD_FILE_RESTRICTION_ANY,   "Constant",       "OkFail",             FALSE },
    { TRUE_FALSE,                       "TRUE_FALSE",                       "SYMBOLS_TRUE_FALSE",                  8,          AUTOGEN_DEVICE_GENERAL, AUTOGEN_PRESENTATION_GLOBAL,             PMD_INFO_TYPE_NONE,                 NULL,                       0,                                 AUTOGEN_PMD_FILE_RESTRICTION_ANY,   "Constant",       "TrueFalse",          TRUE },
    { TRUE_FALSE_1,                     "TRUE_FALSE_1",                     "SYMBOLS_TRUE_FALSE_1",                1,          AUTOGEN_DEVICE_GENERAL, AUTOGEN_PRESENTATION_GLOBAL,             PMD_INFO_TYPE_NONE,                 NULL,                       0,                                 AUTOGEN_PMD_FILE_RESTRICTION_ANY,   "Constant",       "TrueFalse",          FALSE },
    { TRUE_FALSE_16,                    "TRUE_FALSE_16",                    "SYMBOLS_TRUE_FALSE_16",              16,          AUTOGEN_DEVICE_GENERAL, AUTOGEN_PRESENTATION_GLOBAL,             PMD_INFO_TYPE_NONE,                 NULL,                       0,                                 AUTOGEN_PMD_FILE_RESTRICTION_ANY,   "Constant",       "TrueFalse",          FALSE },
    { COLD_WARM,                        "COLD_WARM",                        "SYMBOLS_COLD_WARM",                   8,          AUTOGEN_DEVICE_GENERAL, AUTOGEN_PRESENTATION_GLOBAL,             PMD_INFO_TYPE_NONE,                 NULL,                       0,                                 AUTOGEN_PMD_FILE_RESTRICTION_ANY,   "Constant",       "ColdWarm",           TRUE },
    { COLD_WARM_1,                      "COLD_WARM_1",                      "SYMBOLS_COLD_WARM_1",                 1,          AUTOGEN_DEVICE_GENERAL, AUTOGEN_PRESENTATION_GLOBAL,             PMD_INFO_TYPE_NONE,                 NULL,                       0,                                 AUTOGEN_PMD_FILE_RESTRICTION_ANY,   "Constant",       "ColdWarm",           FALSE },
    { COLD_WARM_16,                     "COLD_WARM_16",                     "SYMBOLS_COLD_WARM_16",               16,          AUTOGEN_DEVICE_GENERAL, AUTOGEN_PRESENTATION_GLOBAL,             PMD_INFO_TYPE_NONE,                 NULL,                       0,                                 AUTOGEN_PMD_FILE_RESTRICTION_ANY,   "Constant",       "ColdWarm",           FALSE },
    { YES_NO_16_BE,                     "YES_NO_16_BE",                     "SYMBOLS_YES_NO_16_BE",               16,          AUTOGEN_DEVICE_GENERAL, AUTOGEN_PRESENTATION_GLOBAL,             PMD_INFO_TYPE_NONE,                 NULL,                       0,                                 AUTOGEN_PMD_FILE_RESTRICTION_ANY,   "Constant",       "YesNo",              FALSE },
    { YES_NO_16_LE,                     "YES_NO_16_LE",                     "SYMBOLS_YES_NO_16_LE",               16,          AUTOGEN_DEVICE_GENERAL, AUTOGEN_PRESENTATION_GLOBAL,             PMD_INFO_TYPE_NONE,                 NULL,                       0,                                 AUTOGEN_PMD_FILE_RESTRICTION_ANY,   "Constant",       "YesNo",              FALSE },
    { YES_NO_16_NATIVE,                 "YES_NO_16_NATIVE",                 "SYMBOLS_YES_NO_16_NATIVE",           16,          AUTOGEN_DEVICE_GENERAL, AUTOGEN_PRESENTATION_GLOBAL,             PMD_INFO_TYPE_NONE,                 NULL,                       0,                                 AUTOGEN_PMD_FILE_RESTRICTION_ANY,   "Constant",       "YesNo",              FALSE },
    { ON_OFF_16_BE,                     "ON_OFF_16_BE",                     "SYMBOLS_ON_OFF_16_BE",               16,          AUTOGEN_DEVICE_GENERAL, AUTOGEN_PRESENTATION_GLOBAL,             PMD_INFO_TYPE_NONE,                 NULL,                       0,                                 AUTOGEN_PMD_FILE_RESTRICTION_ANY,   "Constant",       "OnOff",              FALSE },
    { ON_OFF_16_LE,                     "ON_OFF_16_LE",                     "SYMBOLS_ON_OFF_16_LE",               16,          AUTOGEN_DEVICE_GENERAL, AUTOGEN_PRESENTATION_GLOBAL,             PMD_INFO_TYPE_NONE,                 NULL,                       0,                                 AUTOGEN_PMD_FILE_RESTRICTION_ANY,   "Constant",       "OnOff",              FALSE },
    { ON_OFF_16_NATIVE,                 "ON_OFF_16_NATIVE",                 "SYMBOLS_ON_OFF_16_NATIVE",           16,          AUTOGEN_DEVICE_GENERAL, AUTOGEN_PRESENTATION_GLOBAL,             PMD_INFO_TYPE_NONE,                 NULL,                       0,                                 AUTOGEN_PMD_FILE_RESTRICTION_ANY,   "Constant",       "OnOff",              FALSE },
    { ENABLED_DISABLED_16_BE,           "ENABLED_DISABLED_16_BE",           "SYMBOLS_ENABLED_DISABLED_16_BE",     16,          AUTOGEN_DEVICE_GENERAL, AUTOGEN_PRESENTATION_GLOBAL,             PMD_INFO_TYPE_NONE,                 NULL,                       0,                                 AUTOGEN_PMD_FILE_RESTRICTION_ANY,   "Constant",       "EnabledDisabled",    FALSE },
    { ENABLED_DISABLED_16_LE,           "ENABLED_DISABLED_16_LE",           "SYMBOLS_ENABLED_DISABLED_16_LE",     16,          AUTOGEN_DEVICE_GENERAL, AUTOGEN_PRESENTATION_GLOBAL,             PMD_INFO_TYPE_NONE,                 NULL,                       0,                                 AUTOGEN_PMD_FILE_RESTRICTION_ANY,   "Constant",       "EnabledDisabled",    FALSE },
    { ENABLED_DISABLED_16_NATIVE,       "ENABLED_DISABLED_16_NATIVE",       "SYMBOLS_ENABLED_DISABLED_16_NATIVE", 16,          AUTOGEN_DEVICE_GENERAL, AUTOGEN_PRESENTATION_GLOBAL,             PMD_INFO_TYPE_NONE,                 NULL,                       0,                                 AUTOGEN_PMD_FILE_RESTRICTION_ANY,   "Constant",       "EnabledDisabled",    FALSE },
    { OK_FAIL_16_BE,                    "OK_FAIL_16_BE",                    "SYMBOLS_OK_FAIL_16_BE",              16,          AUTOGEN_DEVICE_GENERAL, AUTOGEN_PRESENTATION_GLOBAL,             PMD_INFO_TYPE_NONE,                 NULL,                       0,                                 AUTOGEN_PMD_FILE_RESTRICTION_ANY,   "Constant",       "OkFail",             FALSE },
    { OK_FAIL_16_LE,                    "OK_FAIL_16_LE",                    "SYMBOLS_OK_FAIL_16_LE",              16,          AUTOGEN_DEVICE_GENERAL, AUTOGEN_PRESENTATION_GLOBAL,             PMD_INFO_TYPE_NONE,                 NULL,                       0,                                 AUTOGEN_PMD_FILE_RESTRICTION_ANY,   "Constant",       "OkFail",             FALSE },
    { OK_FAIL_16_NATIVE,                "OK_FAIL_16_NATIVE",                "SYMBOLS_OK_FAIL_16_NATIVE",          16,          AUTOGEN_DEVICE_GENERAL, AUTOGEN_PRESENTATION_GLOBAL,             PMD_INFO_TYPE_NONE,                 NULL,                       0,                                 AUTOGEN_PMD_FILE_RESTRICTION_ANY,   "Constant",       "OkFail",             FALSE },
    { TRUE_FALSE_16_BE,                 "TRUE_FALSE_16_BE",                 "SYMBOLS_TRUE_FALSE_16_BE",           16,          AUTOGEN_DEVICE_GENERAL, AUTOGEN_PRESENTATION_GLOBAL,             PMD_INFO_TYPE_NONE,                 NULL,                       0,                                 AUTOGEN_PMD_FILE_RESTRICTION_ANY,   "Constant",       "TrueFalse",          FALSE },
    { TRUE_FALSE_16_LE,                 "TRUE_FALSE_16_LE",                 "SYMBOLS_TRUE_FALSE_16_LE",           16,          AUTOGEN_DEVICE_GENERAL, AUTOGEN_PRESENTATION_GLOBAL,             PMD_INFO_TYPE_NONE,                 NULL,                       0,                                 AUTOGEN_PMD_FILE_RESTRICTION_ANY,   "Constant",       "TrueFalse",          FALSE },
    { TRUE_FALSE_16_NATIVE,             "TRUE_FALSE_16_NATIVE",             "SYMBOLS_TRUE_FALSE_16_NATIVE",       16,          AUTOGEN_DEVICE_GENERAL, AUTOGEN_PRESENTATION_GLOBAL,             PMD_INFO_TYPE_NONE,                 NULL,                       0,                                 AUTOGEN_PMD_FILE_RESTRICTION_ANY,   "Constant",       "TrueFalse",          FALSE },
    { COLD_WARM_16_BE,                  "COLD_WARM_16_BE",                  "SYMBOLS_COLD_WARM_16_BE",            16,          AUTOGEN_DEVICE_GENERAL, AUTOGEN_PRESENTATION_GLOBAL,             PMD_INFO_TYPE_NONE,                 NULL,                       0,                                 AUTOGEN_PMD_FILE_RESTRICTION_ANY,   "Constant",       "ColdWarm",           FALSE },
    { COLD_WARM_16_LE,                  "COLD_WARM_16_LE",                  "SYMBOLS_COLD_WARM_16_LE",            16,          AUTOGEN_DEVICE_GENERAL, AUTOGEN_PRESENTATION_GLOBAL,             PMD_INFO_TYPE_NONE,                 NULL,                       0,                                 AUTOGEN_PMD_FILE_RESTRICTION_ANY,   "Constant",       "ColdWarm",           FALSE },
    { COLD_WARM_16_NATIVE,              "COLD_WARM_16_NATIVE",              "SYMBOLS_COLD_WARM_16_NATIVE",        16,          AUTOGEN_DEVICE_GENERAL, AUTOGEN_PRESENTATION_GLOBAL,             PMD_INFO_TYPE_NONE,                 NULL,                       0,                                 AUTOGEN_PMD_FILE_RESTRICTION_ANY,   "Constant",       "ColdWarm",           FALSE },
#if (defined AUTOGEN_INCLUDE_NOS_TRACES || defined AUTOGEN_ENVIRONMENT_LOCAL)
    { OS_TASK_NAME,                     "OS_TASK_NAME",                     "SYMBOLS_OS_TASK_NAME",               16,          AUTOGEN_DEVICE_CURRENT, AUTOGEN_PRESENTATION_OS_CONST,           PMD_INFO_TYPE_OS_TASK_MCU,          NULL,                       0,                                 0,                                  NULL, NULL, FALSE },
    { OS_TIMER_NAME,                    "OS_TIMER_NAME",                    "SYMBOLS_OS_TIMER_NAME",              16,          AUTOGEN_DEVICE_CURRENT, AUTOGEN_PRESENTATION_OS_CONST,           PMD_INFO_TYPE_OS_TIMER_MCU,         NULL,                       0,                                 0,                                  NULL, NULL, FALSE },
    { OS_RESOURCE_NAME,                 "OS_RESOURCE_NAME",                 "SYMBOLS_OS_RESOURCE_NAME",           16,          AUTOGEN_DEVICE_CURRENT, AUTOGEN_PRESENTATION_OS_CONST,           PMD_INFO_TYPE_OS_RESOURCE_MCU,      NULL,                       0,                                 0,                                  NULL, NULL, FALSE },
    { OS_BLOCK_SET_NAME,                "OS_BLOCK_SET_NAME",                "SYMBOLS_OS_BLOCK_SET_NAME",          16,          AUTOGEN_DEVICE_CURRENT, AUTOGEN_PRESENTATION_OS_CONST,           PMD_INFO_TYPE_OS_BLOCK_SET_MCU,     NULL,                       0,                                 0,                                  NULL, NULL, FALSE },
    { OS_ERROR_CODE,                    "OS_ERROR_CODE",                    "SYMBOLS_OS_ERROR_CODE",               8,          AUTOGEN_DEVICE_CURRENT, AUTOGEN_PRESENTATION_OS_CONST,           PMD_INFO_TYPE_OS_ERROR_CODES_MCU,   pmd_constant_os_error_code, PMD_OS_ERROR_CODE_MAX,             0,                                  NULL, NULL, FALSE },
    { OS_TASK_STATE,                    "OS_TASK_STATE",                    "SYMBOLS_OS_TASK_STATE",               8,          AUTOGEN_DEVICE_CURRENT, AUTOGEN_PRESENTATION_OS_CONST,           PMD_INFO_TYPE_OS_TASK_STATES_MCU,   pmd_constant_os_task_state, PMD_OS_TASK_STATE_MAX,             0,                                  NULL, NULL, FALSE },
    { OS_HOOK_ID,                       "OS_HOOK_ID",                       "SYMBOLS_OS_HOOK",                     8,          AUTOGEN_DEVICE_CURRENT, AUTOGEN_PRESENTATION_OS_CONST,           PMD_INFO_TYPE_OS_HOOKS_MCU,         pmd_constant_os_hook,       PMD_OS_HOOK_MAX,                   0,                                  NULL, NULL, FALSE },
#endif
#if (defined AUTOGEN_ENVIRONMENT_PRODUCT_MCU || defined AUTOGEN_ENVIRONMENT_LOCAL)
    { HW_RESET_REASON,                  "HW_RESET_REASON",                  "SYMBOLS_HW_RESET_REASON",             8,          AUTOGEN_DEVICE_GENERAL, AUTOGEN_PRESENTATION_SYMBOL,             PMD_INFO_TYPE_HW_RESET_REASONS,     pmd_constant_hw_reset_type, PMD_HW_RESET_TYPE_MAX,             0,                                  NULL, NULL, FALSE },
#endif
    { CDSP_PROCESS_ID,                  "CDSP_PROCESS_ID",                  "SYMBOLS_CDSP_PROCESS_ID",            16,          PN_DEV_DSP_MAIN,        AUTOGEN_PRESENTATION_CDSP_PROCESS_ID,    PMD_INFO_TYPE_CDSP_TASKS,           NULL,                       0,                                 0,                                  NULL, NULL, FALSE },
    { ADSP_PROCESS_ID,                  "ADSP_PROCESS_ID",                  "SYMBOLS_ADSP_PROCESS_ID",            16,          PN_DEV_DSP_AUX,         AUTOGEN_PRESENTATION_ADSP_PROCESS_ID,    PMD_INFO_TYPE_ADSP_TASKS,           NULL,                       0,                                 0,                                  NULL, NULL, FALSE },
    { CDSP_SIGNAL_ID,                   "CDSP_SIGNAL_ID",                   "SYMBOLS_CDSP_SIGNAL_ID",             16,          PN_DEV_DSP_MAIN,        AUTOGEN_PRESENTATION_CDSP_PROCESS_ID,    PMD_INFO_TYPE_CDSP_SIGNALS,         NULL,                       0,                                 0,                                  NULL, NULL, FALSE },
    { ADSP_SIGNAL_ID,                   "ADSP_SIGNAL_ID",                   "SYMBOLS_ADSP_SIGNAL_ID",             16,          PN_DEV_DSP_AUX,         AUTOGEN_PRESENTATION_ADSP_PROCESS_ID,    PMD_INFO_TYPE_ADSP_SIGNALS,         NULL,                       0,                                 0,                                  NULL, NULL, FALSE },
    { CDSP5_TRACE_SOURCES,              "CDSP5_TRACE_SOURCES",              "SYMBOLS_CDSP5_TRACE_SOURCES",        16,          PN_DEV_DSP_MAIN,        AUTOGEN_PRESENTATION_SYMBOL,             PMD_INFO_TYPE_NONE,                 NULL,                       0,                                 0,                                  NULL, NULL, FALSE },
    { ADSP5_TRACE_SOURCES,              "ADSP5_TRACE_SOURCES",              "SYMBOLS_ADSP5_TRACE_SOURCES",        16,          PN_DEV_DSP_AUX,         AUTOGEN_PRESENTATION_SYMBOL,             PMD_INFO_TYPE_NONE,                 NULL,                       0,                                 0,                                  NULL, NULL, FALSE },
    { CDSP_INTERRUPT_ID,                "CDSP_INTERRUPT_ID",                "SYMBOLS_CDSP_INTERRUPT_ID",          16,          PN_DEV_DSP_MAIN,        AUTOGEN_PRESENTATION_SYMBOL,             PMD_INFO_TYPE_CDSP_INTERRUPTS,      NULL,                       0,                                 0,                                  NULL, NULL, FALSE },
    { CDSP_ERROR_ID,                    "CDSP_ERROR_ID",                    "SYMBOLS_CDSP_ERROR_ID",              32,          PN_DEV_DSP_MAIN,        AUTOGEN_PRESENTATION_SYMBOL,             PMD_INFO_TYPE_CDSP_ERRORS,          NULL,                       0,                                 0,                                  NULL, NULL, FALSE },
    { CDSP_ERROR_DESCRIPTION,           "CDSP_ERROR_DESCRIPTION",           "SYMBOLS_CDSP_ERROR_DESCRIPTION",     16,          PN_DEV_DSP_MAIN,        AUTOGEN_PRESENTATION_SYMBOL,             PMD_INFO_TYPE_CDSP_ERROR_DESCRIPTIONS,NULL,                     0,                                 0,                                  NULL, NULL, FALSE },
    { CDSP_ERROR_EXTRA_PARAMETER,       "CDSP_ERROR_EXTRA_PARAMETER",       "SYMBOLS_CDSP_ERROR_EXTRA_PARAMETER", 16,          PN_DEV_DSP_MAIN,        AUTOGEN_PRESENTATION_SYMBOL,             PMD_INFO_TYPE_CDSP_ERROR_EXTRA_PARAMETERS, NULL,                0,                                 0,                                  NULL, NULL, FALSE },
    { TRACEBOX_OBJECT_ID,               "TRACEBOX_OBJECT_ID",               "SYMBOLS_TRACEBOX_OBJECT_ID",          8,          PN_DEV_TRACEBOX,        AUTOGEN_PRESENTATION_SYMBOL,             PMD_INFO_TYPE_PN_OBJECTS,           pmd_constant_tracebox_object_id, PMD_TRACEBOX_OBJECT_ID_MAX,   0,                                  NULL, NULL, FALSE },
    { PRIVATE_ID,                       "PRIVATE_ID",                       "SYMBOLS_PRIVATE_ID",                 16,          AUTOGEN_DEVICE_GENERAL, AUTOGEN_PRESENTATION_SYMBOL,             PMD_INFO_TYPE_PRIVATE_IDS,          NULL,                       0,                                 0,                                  NULL, NULL, FALSE },
    { INVARIANT_TRACE_ENTITY_ID,        "INVARIANT_TRACE_ENTITY_ID",        "SYMBOLS_INVARIANT_TRACE_ENTITY_ID",   8,          AUTOGEN_DEVICE_GENERAL, AUTOGEN_PRESENTATION_SYMBOL,             PMD_INFO_TYPE_INVARIANT_TRACE_ENTITY_IDS, NULL,                 0,                                 AUTOGEN_PMD_FILE_RESTRICTION_ANY,   NULL, NULL, FALSE },
    { RESOURCE_ID,                      "RESOURCE_ID",                      "SYMBOLS_RESOURCE_ID",                16,          AUTOGEN_DEVICE_GENERAL, AUTOGEN_PRESENTATION_SYMBOL,             PMD_INFO_TYPE_RESOURCE_IDS,         NULL,                       0,                                 0,                                  NULL, NULL, FALSE },
    { XTI_MASTER_ID,                    "XTI_MASTER_ID",                    "SYMBOLS_XTI_MASTER_ID",               8,          AUTOGEN_DEVICE_GENERAL, AUTOGEN_PRESENTATION_SYMBOL,             PMD_INFO_TYPE_XTI_MASTER_IDS,       NULL,                       0,                                 AUTOGEN_PMD_FILE_RESTRICTION_ANY,   NULL, NULL, FALSE },
    { SYMBIAN_COMPONENT_ID,             "SYMBIAN_COMPONENT_ID",             "SYMBOLS_SYMBIAN_COMPONENT_ID",       32,          AUTOGEN_DEVICE_GENERAL, AUTOGEN_PRESENTATION_SYMBOL,             PMD_INFO_TYPE_SYMBIAN_COMPONENT_IDS,NULL,                       0,                                 0,                                  NULL, NULL, FALSE },
    { VENDOR_COMPONENT_TRACE_ENTITY_ID, "VENDOR_COMPONENT_TRACE_ENTITY_ID", "SYMBOLS_SYMBIAN_COMPONENT_ID",        8,
                                                                                                    AUTOGEN_DEVICE_GENERAL, AUTOGEN_PRESENTATION_SYMBOL,             PMD_INFO_TYPE_VENDOR_COMPONENT_TRACE_ENTITY_IDS,   NULL,        0,                                 0,                                  NULL, NULL, FALSE },
};

/* pointer to the list of embedded files */
autogen_obj_list* g_emb_file_list = NULL;

/* list of PMD environment constants */
autogen_obj g_pmd_environment_variables = INIT_OBJECT;

/* is any warnings found during the analysis of the data model? */
int g_has_warnings = FALSE;

/* autogen environment */
#ifdef AUTOGEN_ENVIRONMENT_LOCAL
 unsigned int g_autogen_env = AUTOGEN_ENV_LOCAL;
#elif (defined AUTOGEN_ENVIRONMENT_PRODUCT_DSP)
 unsigned int g_autogen_env = AUTOGEN_ENV_PRODUCT_DSP;
#elif (defined AUTOGEN_ENVIRONMENT_PRODUCT_ADSP)
 unsigned int g_autogen_env = AUTOGEN_ENV_PRODUCT_ADSP;
#elif (defined AUTOGEN_ENVIRONMENT_PRODUCT_MCU)
 unsigned int g_autogen_env = AUTOGEN_ENV_PRODUCT_MCU;
#elif (defined AUTOGEN_ENVIRONMENT_PRODUCT_SYMBIAN)
 unsigned int g_autogen_env = AUTOGEN_ENV_PRODUCT_SYMBIAN;
#elif (defined AUTOGEN_ENVIRONMENT_PRODUCT_DEVICE)
 unsigned int g_autogen_env = AUTOGEN_ENV_PRODUCT_DEVICE;
#else
 unsigned int g_autogen_env = AUTOGEN_ENV_PRODUCT;
#endif

/* pointer to the log file handle */
FILE* g_log = NULL;

/* generic STI trace definitions */
unsigned int g_sti_trace_id = 0;
const char*  g_sti_trace_name = "";


/*  End of file autogen_def.c  */
