/*
NOKIA
Devices R&D Salo
DCT/ASD/AM/SWAM



            comm_isi_m.h
            -------------------
            SW include - ANSI C



Continuus Ref:
--------------
database:        ou1gif

project path:    global_interface/coresw_interface/coresw_public

name:            comm_isi_m.h

version:         000.031

type:            incl

instance:        sa_mcu#3



Document code:    -

Copyright(c) Nokia Corporation. All rights reserved.

Change History:
VERSION       000.031a  NON-DRAFT   12-Jun-09         Leif Karilainen 
REASON        Minor updates
REFERENCE     See SWAM ADB LK09061551762.
DESCRIPTION   Minor updates to html output for modem outlicensing case.

VERSION       000.031  NON-DRAFT   11-Dec-08         Leif Karilainen 
REASON        Minor updates
REFERENCE     See SWAM ADB LK08120847276.
DESCRIPTION   Added 3rd party specific address space (OxF3) 

VERSION       000.030  NON-DRAFT   14-Nov-08         Leif Karilainen 
REASON        Minor updates
REFERENCE     See SWAM ADB LK08111334707.
DESCRIPTION   Regenerated all common message output files as autogen had some problems to 
	      generate correct message length macros with the old autogen version.

VERSION       000.029  NON-DRAFT   03-May-07         Leif Karilainen 
REASON        Minor updates
REFERENCE     See SWAM ADB LK07050349205.
DESCRIPTION   Removed autogen warnings caused by old macro usage. Updated references.
              
VERSION       000.028  NON-DRAFT   08-Dec-06         Leif Karilainen 
REASON        Update to support extended resource ID concept behind flag
              COMMON_MESSAGES_EXTENDED_INTERFACE.
REFERENCE     See SWAM ADB LK06120455502.
DESCRIPTION   New C-structures introduced because of extended resource ID concept.
              New file outputs generated comm_ext_isi.h(_16.h)

VERSION       000.027  NON-DRAFT   04-Jan-06         Leif Karilainen 
REASON        Minor update.
REFERENCE     See SWAM ADB LK06010448865.
DESCRIPTION   New COMM_RF_WIFI operation value added to COMM_RF_CONTROL_REQ message.

VERSION       000.026  NON-DRAFT   26-Aug-04         Leif Karilainen 
REASON        New message.
REFERENCE     See SWAM ADB LK04082636973.
DESCRIPTION   COMM_SERVICE_NOT_AUTHENTICATED_RESP introduced.

VERSION       000.025  NON-DRAFT   26-Apr-04         Leif Karilainen 
REASON        comm_isi_m.h needs updates.
REFERENCE     See SWAM ADB LK04042648164.
DESCRIPTION   HEX interpretation for some fields in COMM_SERVICE_NOT_IDENTIFIED_RESP message and
              one field in COMM_ISA_ENTITY_NOT_REACHABLE_RESP.

VERSION       000.024  NON-DRAFT   01-Mar-04         Leif Karilainen 
REASON        comm_isi_16.h needs updates.
REFERENCE     See SWAM ADB LK04030137132
DESCRIPTION   New defines for merge fields in comm_isi_16.h have been taken into use
              See e.g.PROPERTY_ISIHDR_GENERATE_MERGED_MASKS_16.

VERSION       000.023  NON-DRAFT   12-Jan-04         Leif Karilainen 
REASON        New common ISI message
REFERENCE     See SWAM ADB LK04011246215
DESCRIPTION   COMM_RF_CONTROL_REQ(RESP) added.

VERSION       000.022  NON-DRAFT   13-Oct-03          Leif Karilainen 
REASON        Comments from inspection.
REFERENCE     See SWAM ADB LK03093036140
DESCRIPTION   Continuus html project info added to cover page.

VERSION       000.021  NON-DRAFT   29-Sep-03          Leif Karilainen 
REASON        Autogenerated common ISI header taken into use in sw packages.
REFERENCE     See SWAM ADB LK03093036140
DESCRIPTION   COMM_FTD_DATA_STRING C-structure changed so that string[] field 
              is generated. References have been updated.

VERSION       000.020  NON-DRAFT   28-Apr-03          Leif Karilainen 
REASON        New message macro template taken into use and some macros 
              updated because of new autogen version 
              (DEFINE_CONST_TBL_BEGIN -->CONST_TBL_BEGIN and similar kind
              of cases). COMM_FTD_SYSTEM_SWITCH sub block added.
              COMM_MAX_FTD_STRING_LENGTH changed from 127 to 124
              This version is now compatible with the 
              ISI:COMMON_FEATURES.BASE-SPEC;000.020.
REFERENCE     See SWAM ADB LK03042933779
DESCRIPTION   Autogen release 5.21 and new template taken into use.
              Handmade message spec. replaced with autogenerated one.


VERSION       000.019  NON-DRAFT   30-Nov-01          Leif Karilainen 
REASON        Defects found in inspection are corrected. This version 
              is now compatible with the ISI:COMMON_MESSAGES.
              BASE-SPEC;19.0.
REFERENCE     See SWAM ADB LK01112144458.
DESCRIPTION   The message name for COMM_SERVICE_PROVIDER_NOT_FOUND_RESP 
              changed to COMM_ISA_ENTITY_NOT_REACHABLE_RESP and status 
              field added to the message. The only sub block which should 
              be possible for COMM_FTD_DATA_DEACTIVATE_RESP is 
              COMM_FTD_DATA_FAIL.

VERSION     : 000.018  NON-DRAFT   21-May-01          Leif Karilainen 
REASON      : New functionality. This version is now
              compatible with the ISI:COMMON_MESSAGES.BASE-SPEC;18.0.
              The version number has been aligned with the message spec.
              so versions 000.016 and 000.017 has been jumped over.
REFERENCE     See SWAM ADB LK01112144458.
DESCRIPTION : COMM_SERVICE_PROVIDER_NOT_FOUND_RESP added.

VERSION     : 000.015  NON-DRAFT   03-May-01          Leif Karilainen 
REASON      : Updates received via email insp. This version is now
              compatible with the ISI:COMMON_MESSAGES.BASE-SPEC;15.0.
REFERENCE   : See SWAM ADB LK01032756471.
DESCRIPTION : COMM_MAX_FTD_DATA_LENGTH changed from 255 to 248 in
              COMM_FTD_DATA_TABLE sub block template. Added the VALUE_LIMITS
              macro.
              This file is just meant to be used in the ISI message interpretation
              phase (MDF) when tracing/debugging SW code. This file is matching (
              not 100 %) the handmade comm_isi.h;000.015. to some messages.

VERSION     : 000.014    NON-DRAFT    26-Mar-2001  Leif Karilainen
REASON      : Updates.
REFERENCE   : See SWAM ADB LK01032756471.
DESCRIPTION : COMM_ISI_VERSION_GET_REQ(RESP) added. This file is just meant to be
              used in the ISI message interpretation phase (MDF) when tracing/debugging
              SW code. This file is matching (not 100 %) the handmade comm_isi.h;000.014.

VERSION     : 7          NON-DRAFT    15-Jan-2001  Leif Karilainen
REASON      : Improvement to conform to the general message macro rules.
REFERENCE   : See SWAM ADB LK00121257625.
DESCRIPTION : Two consecutive FILLER(FIXED_FILLER, 8) has been replaced with
              FILLER(FIXED_FILLER, 16) in some main messages.

VERSION     : 6          NON-DRAFT    11-Dec-2000  Leif Karilainen
REASON      : Improvement to conform to the general message macro rules.
REFERENCE   : See SWAM ADB LK00121257625.
DESCRIPTION : The file has been changed so that it's following the general
              instructions about how to use the message macros. E.g. the 
              FILLER macro and the general sub block macro has been 
              taken into use. This file should NEVER be used to produce the 
              ISI message header file to be used in the SW. This file is 
              following the message layout specified manually in i_comm_m.doc 
              but the manually created comm_isi.h should be used in the SW 
              packages. This file is just meant to be used in the ISI message 
              interpretation phase (MDF) when tracing/debugging SW code.
              This file is matching the handmade comm_isi.h;13
  
VERSION     : 5          NON-DRAFT    16-Oct-2000  Leif Karilainen
REASON      : Taking over the responsibility of this file from Christian.
REFERENCE   : See SWAM ADB LK00102557255.
DESCRIPTION : The file has been changed so that it's matching the handmade 
              comm_isi.h;13 as much as possible.

VERSION     : 4          DRAFT        19-Sep-2000  Christian Jacob Hansen
REASON      : Change in autogeneration tool
REFERENCE   : -
DESCRIPTION : The file has been changed according to the changes made to
              the autogeneration tool
              Updated according to i_comm_m.doc, version 11.0 NON-DRAFT, 
              29-May-00. Added sequence COMM_FTD_DATA_TABLE

VERSION     : 3          DRAFT        12-Jul-2000  Christian Jacob Hansen
REASON      : -
REFERENCE   : -
DESCRIPTION : The file has ben updated according to 
              i_comm_m-doc, version 11.0 NON_DRAFT 29-May-00

VERSION     : 2          DRAFT        22-Mar-2000  Christian Jacob Hansen
REASON      : -
REFERENCE   : -
DESCRIPTION : The file has ben updated according to 
              i_comm_m-doc, version 10.0 NON_DRAFT 10-Mar-00

VERSION     : 1          DRAFT        25-Feb-2000  Christian Jacob Hansen
REASON      : Original
REFERENCE   : -
DESCRIPTION : The file is based on the message description document 
              i_comm_m.doc, version 2.0 APPROVED 16-Jul-99

*/

/* ------------------------------------------------------------------------- */


/*  1    ABSTRACT

    1.1    Module type

    Message definition file for autogeneration
   
    1.2    Functional description

    This file is the message definition file for the so called common ISI messages

    1.3    Notes

    2    CONTENTS

    3    CONSTANTS

    4    MACROS

    5    DATA TYPES

    6    CLASSES

    7    OBJECTS

    8    DATA STRUCTURES

    9    FUNCTION PROTOTYPES
*/

#ifdef COMMON_MESSAGES_EXTENDED_INTERFACE
#ifndef _COMM_ISI_M_H_EXTENDED_
#define _COMM_ISI_M_H_INCLUDE_
#define _COMM_ISI_M_H_EXTENDED_
#endif /* _COMM_ISI_M_H_EXTENDED_ */
#else
#ifndef _COMM_ISI_M_H_NORMAL_
#define _COMM_ISI_M_H_INCLUDE_
#define _COMM_ISI_M_H_NORMAL_
#endif /* _COMM_ISI_M_H_NORMAL_ */
#endif /* COMMON_MESSAGES_EXTENDED_INTERFACE */

#ifdef _COMM_ISI_M_H_INCLUDE_
#undef _COMM_ISI_M_H_INCLUDE_

/*  3    CONSTANTS */

/* Message ID's */
#define COMMON_MESSAGE                      0xF0

#ifndef COMM_GENERATE_MODEM_LICENSING
#define SBC_MESSAGE                         0xF1
#endif  /* COMM_GENERATE_MODEM_LICENSING */

#define SERVER_MESSAGE_SPACE_EXTENSION      0xF2

#ifndef COMM_GENERATE_MODEM_LICENSING
#define THIRD_PARTY_SPECIFIC_MESSAGE	    0xF3
#endif  /* COMM_GENERATE_MODEM_LICENSING */

/* Sub message ID's */
#define COMM_SERVICE_NOT_IDENTIFIED_RESP    0x01

#ifndef COMM_GENERATE_MODEM_LICENSING
#define COMM_SERVER_VERSION_GET_REQ         0x02
#define COMM_SERVER_VERSION_GET_RESP        0x03
#define COMM_FTD_DATA_REQ                   0x04
#define COMM_FTD_DATA_RESP                  0x05
#define COMM_FTD_TEST_DATA_REQ              0x06
#define COMM_FTD_TEST_DATA_RESP             0x07
#define COMM_FTD_DATA_DEACTIVATE_REQ        0x08
#define COMM_FTD_DATA_DEACTIVATE_RESP       0x09
#endif  /* COMM_GENERATE_MODEM_LICENSING */

/* 0x0A and 0x0B not used anymore, the C-structures exists in the 
   handmade comm_isi.h;000.019 just to be sure not to break 
   the builds
*/
#ifndef COMM_GENERATE_MODEM_LICENSING
#define COMM_PWR_OFF_CONFIRM_REQ            0x0C
#define COMM_PWR_OFF_CONFIRM_RESP           0x0D
#define COMM_NVD_SET_DEFAULT_REQ            0x0E
#define COMM_NVD_SET_DEFAULT_RESP           0x0F
#define COMM_NVD_VERSION_CHK_REQ            0x10
#define COMM_NVD_VERSION_CHK_RESP           0x11
#endif  /* COMM_GENERATE_MODEM_LICENSING */

#define COMM_ISI_VERSION_GET_REQ            0x12
#define COMM_ISI_VERSION_GET_RESP           0x13
#define COMM_ISA_ENTITY_NOT_REACHABLE_RESP  0x14

#ifndef COMM_GENERATE_MODEM_LICENSING
#define COMM_RF_CONTROL_REQ                 0x15
#define COMM_RF_CONTROL_RESP                0x16
#define COMM_SERVICE_NOT_AUTHENTICATED_RESP 0x17
#endif  /* COMM_GENERATE_MODEM_LICENSING */

/* Sub block ID's */
/* COMM_NVD_SINGLE_TRANSFER is removed, it exists 
   in the handmade comm_isi.h;000.019 just to be sure not 
   to break the builds */

/* Sub Block ID's for COMM_FTD_DATA_* */
#ifndef COMM_GENERATE_MODEM_LICENSING
#define COMM_FTD_DATA_FAIL                  0x0000
#define COMM_FTD_DATA_ALL                   0x0001
#define COMM_FTD_SYSTEM_SWITCH              0x0002
/* #define COMM_LAST_COMMON_FTD_ID          0x000F */
#endif  /* COMM_GENERATE_MODEM_LICENSING */

/* Other constants */
#define COMM_MAX_VERSION_COMMENTS_LENGTH    127
#define COMM_MAX_FTD_STRING_LENGTH          124
#define COMM_MAX_FTD_DATA_LENGTH            248
#define COMM_MAX_FTD_DATA_ITEMS             255
#define COMM_STRING_ASCII                   0
#define COMM_STRING_UNICODE                 1

/*  4    MACROS */

#undef FILLERS_0_2 /* inesrt 0 fillers in normal file and 2 fillers in extended file */
#undef FILLERS_2_0 /* inesrt 2 fillers in normal file and 0 fillers in extended file */

#undef COMM_MSG_HEADER
#undef COMM_MSG_HEADER_

#undef EXT_STRUCT_NAME /* set different struct / struct length name in extended file */
#undef EXT_ISIHDR_DONT_GENERATE /* dont generate constants etc. in extended file */


#ifdef COMMON_MESSAGES_EXTENDED_INTERFACE

#define COMM_MSG_HEADER   COMMON_PREFIX_SUB_MSG_HDR
#define COMM_MSG_HEADER_  COMMON_PREFIX_SUB_MSG_HDR

#define FILLERS_0_2(filler1, filler2) \
   COMMENT(COMMENT_TEXT, "For future use. The value should always be zero.") \
   FILLER_EX(filler1, 8, 1) \
   COMMENT(COMMENT_TEXT, "For future use. The value should always be zero.") \
   FILLER_EX(filler2, 8, 1)

#define FILLERS_2_0(filler1, filler2)

#define EXT_STRUCT_NAME(name) \
   PROPERTY_STRING(PROPERTY_ISIHDR_STRUCT_NAME,        #name "_STR") \
   PROPERTY_STRING(PROPERTY_ISIHDR_STRUCT_LENGTH_NAME, "SIZE_" #name "_STR")

#define EXT_ISIHDR_DONT_GENERATE \
   PROPERTY(PROPERTY_ISIHDR_DONT_GENERATE)

#else /* COMMON_MESSAGES_EXTENDED_INTERFACE */

#define COMM_MSG_HEADER \
   COMMENT(COMMENT_TEXT, "-") \
   VALUE(8, BE, transactionID, "Transaction ID", DEC) \
   REFERENCE(8, BE, messageID, "Message ID", MSG_ID) \
   REFERENCE(8, BE, submessageID, "Sub message ID", SUB_MSG_ID)

#define COMM_MSG_HEADER_ \
   COMMENT(COMMENT_TEXT, "-") \
   VALUE(8, BE, transaction_ID, "Transaction ID", DEC) \
   REFERENCE(8, BE, messageID, "Message ID", MSG_ID) \
   REFERENCE(8, BE, submessageID, "Sub message ID", SUB_MSG_ID)

#define FILLERS_0_2(filler1, filler2)

#define FILLERS_2_0(filler1, filler2) \
    COMMENT(COMMENT_TEXT, "For future use. The value should always be zero.") \
    FILLER_EX(filler1, 8, 1) \
    COMMENT(COMMENT_TEXT, "For future use. The value should always be zero.") \
    FILLER_EX(filler2, 8, 1)

#define EXT_STRUCT_NAME(name)
#define EXT_ISIHDR_DONT_GENERATE

#endif /* COMMON_MESSAGES_EXTENDED_INTERFACE */

#define COMM_SB_16 \
    REFERENCE(16, BE, subblockID, "Sub Block ID", SB_ID) \
    REFERENCE(8, BE, subblock_length, "Sub Block Length", SB_LENGTH) 

#define FTD_SB_16 \
    REFERENCE(16, BE, subblockID, "Sub Block ID", SB_ID) \
    REFERENCE(8, BE, subblock_length, "Sub Block Length", SB_LENGTH) 

/* TODO: Change the version whenever the interface is changed */
/* default ISI version */
#ifndef COMM_ISI_VERSION
#define COMM_ISI_VERSION
#define COMM_ISI_VERSION_Z      0
#define COMM_ISI_VERSION_Y      31
#endif

    /* --------------------------------------------------------------------- */
    /* Project / Document information */
    /* --------------------------------------------------------------------- */
    /* Project / Document properties */
#if ((defined COMM_GENERATE_VENDOR_VERSION) || (defined COMM_GENERATE_MODEM_LICENSING))
    PROPERTY(PROPERTY_NOKIA_3RD_PARTY_VENDOR_OUTPUT)
#endif 

    PROPERTY_STRING(PROPERTY_PROJECT_SITE_NAME, "Devices R&D Salo")
    PROPERTY_STRING(PROPERTY_PROJECT_NAME,      "DCT/ASD/AM/SWAM")
    PROPERTY_STRING(PROPERTY_PROJECT_OWNER_NAME,"Leif Karilainen")

    /* ISI header properties */
    PROPERTY_STRING(PROPERTY_ISIHDR_CONTINUUS_PROJECT_DB,       "ou1gif")
    PROPERTY_STRING(PROPERTY_ISIHDR_CONTINUUS_PROJECT_PATH,     "global_interface/coresw_interface/coresw_public")
    PROPERTY_STRING(PROPERTY_ISIHDR_CONTINUUS_PROJECT_PATH_16,  "global_interface/coresw_interface/coresw_public")
    PROPERTY_STRING(PROPERTY_ISIHDR_CONTINUUS_INSTANCE_NAME,    "sa_mcu#1")
    PROPERTY_STRING(PROPERTY_ISIHDR_CONTINUUS_INSTANCE_NAME_16, "sa_mcu#1")
    
#ifdef COMM_GENERATE_MODEM_LICENSING /* Wireless Modem version */
    PROPERTY_STRING(PROPERTY_ISIHDR_FILENAME, "comm_wm_isi.h")
    PROPERTY_STRING(PROPERTY_ISIHDR_FILENAME_16, "") 
#endif /* COMM_GENERATE_MODEM_LICENSING */


    /* HTML properties */
#ifdef COMMON_MESSAGES_EXTENDED_INTERFACE
    PROPERTY_STRING(PROPERTY_HTML_TITLE,                        "Extended Common Message Description")
#else /* COMMON_MESSAGES_EXTENDED_INTERFACE */
    PROPERTY_STRING(PROPERTY_HTML_TITLE,                        "ISI Common Message Interface Specification")
#endif /* COMMON_MESSAGES_EXTENDED_INTERFACE */

    PROPERTY_STRING(PROPERTY_HTML_DOCUMENT_NUMBER,              "-")
    PROPERTY_STRING(PROPERTY_HTML_CONTINUUS_PROJECT_DB,         "ou1gif")
    PROPERTY_STRING(PROPERTY_HTML_CONTINUUS_PROJECT_NAME,       "GIF_SPECS-ou1gif#browse")
    PROPERTY_STRING(PROPERTY_HTML_DIRECTORY_PATH,               "GIF_SPECS/CoreSW/coresw_public_spec")
    PROPERTY(PROPERTY_HTML_INCLUDE_INTRODUCTION)
    
#ifdef COMM_GENERATE_MODEM_LICENSING /* Wireless Modem version */
    PROPERTY_STRING(PROPERTY_HTML_FILENAME, "i_comm_wm_m.html")
#endif /* COMM_GENERATE_MODEM_LICENSING */


    /* additional comments to introduction */

    COMMENT(COMMENT_TEXT, 
        "The common ISI feature descriptions can be found from reference ")
    COMMENT_LINK(LINK_NOTE, "/4/", "", "")
    COMMENT(COMMENT_TEXT, ", where the glossary is presented")


    /* --------------------------------------------------------------------- */
    /* Server description */
    /* --------------------------------------------------------------------- */

    /* All _16 properties will just affect the generated comm_(ext_)isi_16.h output */
    PROPERTY(PROPERTY_ISIHDR_GENERATE_MERGED_MASKS_16)
    PROPERTY(PROPERTY_SUBMSG_NAMES_ARE_UNIQUE)
    
#ifdef COMMON_MESSAGES_EXTENDED_INTERFACE

    COMMENT(COMMENT_ISIHDR_BEFORE_DEF, "/* defines constants and sub blocks */")
    COMMENT(COMMENT_ISIHDR_BEFORE_DEF, "#include \"comm_isi.h\"")

    COMMENT(COMMENT_ISIHDR_BEFORE_DEF_16, "/* defines constants and sub blocks */")
    COMMENT(COMMENT_ISIHDR_BEFORE_DEF_16, "#include \"comm_isi_16.h\"")

    PROPERTY_STRING(PROPERTY_ISIHDR_MERGED_MASK_PREFIX,"_EXT_")

    PROPERTY_STRING(PROPERTY_ISI_VERSION_AUTO_GENERATE,"000.027")

    RES_BEGIN(RESOURCE_ISI_COMMON_MESSAGES_EXT, AUTOGEN_NO_RESOURCE_ID, COMM_EXT, "Common Messages (Extended)", 
        RES_VERSION_STRING(COMM_ISI_VERSION_Z, COMM_ISI_VERSION_Y), FALSE)

#else /* COMMON_MESSAGES_EXTENDED_INTERFACE */

    PROPERTY_STRING(PROPERTY_ISIHDR_MERGED_MASK_PREFIX,"_")
    PROPERTY(PROPERTY_ISIHDR_GENERATE_STRUCT_BYTE_INDEX_16) 
    PROPERTY_STRING(PROPERTY_ISI_VERSION_AUTO_GENERATE,"000.027")

    RES_BEGIN(RESOURCE_ISI_COMMON_MESSAGES, AUTOGEN_NO_RESOURCE_ID, COMM, "Common Messages", 
        RES_VERSION_STRING(COMM_ISI_VERSION_Z, COMM_ISI_VERSION_Y), FALSE)

#endif /* COMMON_MESSAGES_EXTENDED_INTERFACE */
 
    /* --------------------------------------------------------------------- */
    /* ISI version history */
    /* --------------------------------------------------------------------- */

    /* TODO: Add version history block every time the interface is changed */
    PROPERTY_STRING(PROPERTY_CHANGE_STATUS,    "APPROVED")
    PROPERTY_STRING(PROPERTY_CHANGE_DATE,      "11-Dec-2008")
    PROPERTY_STRING(PROPERTY_CHANGE_PERSON,    "Leif Karilainen")
    PROPERTY_STRING(PROPERTY_CHANGE_REFERENCE, "See SWAM ADB LK08120847276")
    PROPERTY_STRING(PROPERTY_CHANGE_REASON,    "Minor updates")
    COMMENT(COMMENT_TEXT, "Added 3rd party specific address space, OxF3")
    ISI_VERSION_HISTORY("000.031")

    
    PROPERTY_STRING(PROPERTY_CHANGE_STATUS,    "APPROVED")
    PROPERTY_STRING(PROPERTY_CHANGE_DATE,      "14-Nov-2008")
    PROPERTY_STRING(PROPERTY_CHANGE_PERSON,    "Leif Karilainen")
    PROPERTY_STRING(PROPERTY_CHANGE_REFERENCE, "See SWAM ADB LK08111334707")
    PROPERTY_STRING(PROPERTY_CHANGE_REASON,    "Minor updates")
    COMMENT(COMMENT_TEXT, "Regenerated all common message output files as autogen had some problems to" 
	      " generate correct message length macros with the old autogen version.")
    ISI_VERSION_HISTORY("000.030")

    PROPERTY_STRING(PROPERTY_CHANGE_STATUS,    "APPROVED")
    PROPERTY_STRING(PROPERTY_CHANGE_DATE,      "03-May-2007")
    PROPERTY_STRING(PROPERTY_CHANGE_PERSON,    "Leif Karilainen")
    PROPERTY_STRING(PROPERTY_CHANGE_REFERENCE, "See SWAM ADB LK07050349205")
    PROPERTY_STRING(PROPERTY_CHANGE_REASON,    "Minor updates")
    COMMENT(COMMENT_TEXT, "Removed autogen warnings caused by old macro usage. Updated references.")
    ISI_VERSION_HISTORY("000.029")
    
    PROPERTY_STRING(PROPERTY_CHANGE_STATUS,    "APPROVED")
    PROPERTY_STRING(PROPERTY_CHANGE_DATE,      "08-Dec-2006")
    PROPERTY_STRING(PROPERTY_CHANGE_PERSON,    "Leif Karilainen")
    PROPERTY_STRING(PROPERTY_CHANGE_REFERENCE, "See SWAM ADB LK06120455502")
    PROPERTY_STRING(PROPERTY_CHANGE_REASON,    "Update to support extended resource ID concept"
                        " behind flag COMMON_MESSAGES_EXTENDED_INTERFACE first time.")
    COMMENT(COMMENT_TEXT, "-")                    
    ISI_VERSION_HISTORY("000.028")

    PROPERTY_STRING(PROPERTY_CHANGE_STATUS,    "APPROVED")
    PROPERTY_STRING(PROPERTY_CHANGE_DATE,      "04-Jan-2006")
    PROPERTY_STRING(PROPERTY_CHANGE_PERSON,    "Leif Karilainen")
    PROPERTY_STRING(PROPERTY_CHANGE_REFERENCE, "See SWAM ADB LK06010448865")
    PROPERTY_STRING(PROPERTY_CHANGE_REASON,    "Minor update")
    ISI_VERSION_HISTORY("000.027")
    
    PROPERTY_STRING(PROPERTY_CHANGE_STATUS,    "APPROVED")
    PROPERTY_STRING(PROPERTY_CHANGE_DATE,      "26-Aug-2004")
    PROPERTY_STRING(PROPERTY_CHANGE_PERSON,    "Leif Karilainen")
    PROPERTY_STRING(PROPERTY_CHANGE_REFERENCE, "See SWAM ADB LK04082636973")
    PROPERTY_STRING(PROPERTY_CHANGE_REASON,    "New message.")
    COMMENT(COMMENT_TEXT, "COMM_SERVICE_NOT_AUTHENTICATED_RESP introduced.")
    ISI_VERSION_HISTORY("000.026")

    PROPERTY_STRING(PROPERTY_CHANGE_STATUS,    "APPROVED")
    PROPERTY_STRING(PROPERTY_CHANGE_DATE,      "26-Apr-2004")
    PROPERTY_STRING(PROPERTY_CHANGE_PERSON,    "Leif Karilainen")
    PROPERTY_STRING(PROPERTY_CHANGE_REFERENCE, "See SWAM ADB LK04042648164")
    PROPERTY_STRING(PROPERTY_CHANGE_REASON,    "comm_isi_m.h needs updates.")
    COMMENT(COMMENT_TEXT, "HEX interpretation for some fields in COMM_SERVICE_NOT_IDENTIFIED_RESP"
                          " and one field in COMM_ISA_ENTITY_NOT_REACHABLE_RESP messages.")
    ISI_VERSION_HISTORY("000.025")


    PROPERTY_STRING(PROPERTY_CHANGE_STATUS,    "APPROVED")
    PROPERTY_STRING(PROPERTY_CHANGE_DATE,      "01-Mar-2004")
    PROPERTY_STRING(PROPERTY_CHANGE_PERSON,    "Leif Karilainen")
    PROPERTY_STRING(PROPERTY_CHANGE_REFERENCE, "See SWAM ADB LK04030137132")
    PROPERTY_STRING(PROPERTY_CHANGE_REASON,    "comm_isi_16.h needs updates.")
    COMMENT(COMMENT_TEXT, "New defines for merge fields in comm_isi_16.h" 
                          " have been taken into use."
                          " See e.g. PROPERTY_ISIHDR_GENERATE_MERGED_MASKS_16.")
    ISI_VERSION_HISTORY("000.024")

    PROPERTY_STRING(PROPERTY_CHANGE_STATUS,    "APPROVED")
    PROPERTY_STRING(PROPERTY_CHANGE_DATE,      "12-Jan-2004")
    PROPERTY_STRING(PROPERTY_CHANGE_PERSON,    "Leif Karilainen")
    PROPERTY_STRING(PROPERTY_CHANGE_REFERENCE, "See SWAM ADB LK04011246215.")
    PROPERTY_STRING(PROPERTY_CHANGE_REASON,    "New common ISI message.")
    COMMENT(COMMENT_TEXT, "COMM_RF_CONTROL_REQ(RESP) added.")
    ISI_VERSION_HISTORY("000.023")
    
    PROPERTY_STRING(PROPERTY_CHANGE_STATUS,    "APPROVED")
    PROPERTY_STRING(PROPERTY_CHANGE_DATE,      "13-Oct-2003")
    PROPERTY_STRING(PROPERTY_CHANGE_PERSON,    "Leif Karilainen")
    PROPERTY_STRING(PROPERTY_CHANGE_REFERENCE, "See SWAM ADB LK03093036140.")
    PROPERTY_STRING(PROPERTY_CHANGE_REASON,    "Comments from inspection.")
    COMMENT(COMMENT_TEXT, "Continuus html project info added to cover page.")
    ISI_VERSION_HISTORY("000.022")

    PROPERTY_STRING(PROPERTY_CHANGE_STATUS,    "APPROVED")
    PROPERTY_STRING(PROPERTY_CHANGE_DATE,      "29-Sep-2003")
    PROPERTY_STRING(PROPERTY_CHANGE_PERSON,    "Leif Karilainen")
    PROPERTY_STRING(PROPERTY_CHANGE_REFERENCE, "See SWAM ADB LK03093036140.")
    PROPERTY_STRING(PROPERTY_CHANGE_REASON, "Autogenerated common ISI header taken into use in sw packages.")
    COMMENT(COMMENT_TEXT, "COMM_FTD_DATA_STRING C-structure changed so that"
                          " string[] field is generated. References have been updated.")
    ISI_VERSION_HISTORY("000.021")

    PROPERTY_STRING(PROPERTY_CHANGE_STATUS,    "APPROVED")
    PROPERTY_STRING(PROPERTY_CHANGE_DATE,      "28-Apr-2003")
    PROPERTY_STRING(PROPERTY_CHANGE_PERSON,    "Leif Karilainen")
    PROPERTY_STRING(PROPERTY_CHANGE_REFERENCE, "See SWAM ADB LK03042933779.")
    PROPERTY_STRING(PROPERTY_CHANGE_REASON, "New message macro template taken into use and some macros" 
        " updated because of new autogen version" 
        " (DEFINE_CONST_TBL_BEGIN -->CONST_TBL_BEGIN and similar kind"
        " of cases). COMM_FTD_SYSTEM_SWITCH sub block added."
        " COMM_MAX_FTD_STRING_LENGTH changed from 127 to 124. This version is now compatible with the" 
        " ISI:COMMON_FEATURES.BASE-SPEC;000.020.")
    COMMENT(COMMENT_TEXT, "-")
    ISI_VERSION_HISTORY("000.020")

    PROPERTY_STRING(PROPERTY_CHANGE_STATUS, "NON-DRAFT")
    PROPERTY_STRING(PROPERTY_CHANGE_DATE, "30-Nov-2001")
    PROPERTY_STRING(PROPERTY_CHANGE_PERSON, "Leif Karilainen")
    PROPERTY_STRING(PROPERTY_CHANGE_REFERENCE, "See SWAM ADB LK01112144458")
    PROPERTY_STRING(PROPERTY_CHANGE_REASON, 
        "Defects found in inspection are corrected. This version is now "
        "compatible with the ISI:COMMON_MESSAGES.BASE-SPEC;19.0")
    COMMENT(COMMENT_TEXT, 
        "The message name for COMM_SERVICE_PROVIDER_NOT_FOUND_RESP "
        "changed to COMM_ISA_ENTITY_NOT_REACHABLE_RESP and status field "
        "added to the message")
    ISI_VERSION_HISTORY("000.019")

    /* --------------------------------------------------------------------- */
    /* Notes / references  */
    /* --------------------------------------------------------------------- */

    COMMENT(COMMENT_PARAGRAPH, "Autogeneration Process")
    COMMENT(COMMENT_PARAGRAPH, "Intranet")
    COMMENT(COMMENT_PARAGRAPH, "http://tracing.europe.nokia.com/autogen/overview.asp")
    NOTE("/1/")

    COMMENT(COMMENT_PARAGRAPH, "ISI Server Specification Documentation Guidelines")
    COMMENT(COMMENT_PARAGRAPH, "Document code: DSY02803-EN")
    COMMENT(COMMENT_PARAGRAPH, "DocMan location: eslns42/SRV/Nokia")
    COMMENT(COMMENT_PARAGRAPH, "DocMan: DCT DocMan")
    COMMENT(COMMENT_PARAGRAPH, "Filename: TP/PP/ppmgmtdm.nsf")
    NOTE("/2/")

    COMMENT(COMMENT_PARAGRAPH, "ISI General Information")
    COMMENT(COMMENT_PARAGRAPH, "Document code: DSY02801-EN")
    COMMENT(COMMENT_PARAGRAPH, "DocMan location: eslns42/SRV/Nokia")
    COMMENT(COMMENT_PARAGRAPH, "DocMan: DCT DocMan")
    COMMENT(COMMENT_PARAGRAPH, "Filename: TP/PP/ppmgmtdm.nsf")
    NOTE("/3/")

    COMMENT(COMMENT_PARAGRAPH, "ISI Common Feature Descriptions")
    COMMENT(COMMENT_PARAGRAPH, "Continuus Database: ou1gif")
    COMMENT(COMMENT_PARAGRAPH, "Continuus Project: GIF_SPECS-ou1gif#browse")
    COMMENT(COMMENT_PARAGRAPH, "Directory Path: GIF_SPECS/CoreSW/coresw_public_spec")
    COMMENT(COMMENT_PARAGRAPH, "Filename:  i_comm_fp.doc")
    COMMENT(COMMENT_PARAGRAPH, "http://oucmswww.nmp.nokia.com:58080/document_browser/ccm_wa/GIF_SPECS/CoreSW/coresw_public_spec/")
    NOTE("/4/")

    COMMENT(COMMENT_PARAGRAPH, "Common R&D Display Data and Layout")
    COMMENT(COMMENT_PARAGRAPH, "Continuus Database: sa1core")
    COMMENT(COMMENT_PARAGRAPH, "Continuus Project: paradise_doc-ou1core#browse")
    COMMENT(COMMENT_PARAGRAPH, "Directory Path: paradise_doc/FTD")
    COMMENT(COMMENT_PARAGRAPH, "Filename:  rd_display_spec.doc")
    COMMENT(COMMENT_PARAGRAPH, "https://oucmswww.nmp.nokia.com:58443/document_browser/ccm_wa/paradise_doc/FTD/")
    NOTE("/5/")

    COMMENT(COMMENT_PARAGRAPH, "NVD Library Interface Specification")
    COMMENT(COMMENT_PARAGRAPH, "Continuus Database: ou1gif")
    COMMENT(COMMENT_PARAGRAPH, "Continuus Project: GIF_SPECS-ou1gif#browse")
    COMMENT(COMMENT_PARAGRAPH, "Directory Path: GIF_SPECS/CoreSW/coresw_public_spec")
    COMMENT(COMMENT_PARAGRAPH, "Filename:  nvd_lib_inf.doc")
    COMMENT(COMMENT_PARAGRAPH, "http://oucmswww.nmp.nokia.com:58080/document_browser/ccm_wa/GIF_SPECS/CoreSW/coresw_public_spec/")    
    NOTE("/6/")

    COMMENT(COMMENT_PARAGRAPH, "ISI Non-Volatile Data Server Feature Descriptions")
    COMMENT(COMMENT_PARAGRAPH, "Continuus Database: ou1gif")
    COMMENT(COMMENT_PARAGRAPH, "Continuus Project: GIF_SPECS-ou1gif#browse")
    COMMENT(COMMENT_PARAGRAPH, "Directory Path: GIF_SPECS/CoreSW/coresw_public_spec")
    COMMENT(COMMENT_PARAGRAPH, "Filename:  i_nvd_f.doc")
    COMMENT(COMMENT_PARAGRAPH, "http://oucmswww.nmp.nokia.com:58080/document_browser/ccm_wa/GIF_SPECS/CoreSW/coresw_public_spec/")
    NOTE("/7/")

    COMMENT(COMMENT_PARAGRAPH, "Monitor server FTD user instructions")
    COMMENT(COMMENT_PARAGRAPH, "Continuus Database: co1core")
    COMMENT(COMMENT_PARAGRAPH, "Continuus Project: Core_SW_Cph-Latest")
    COMMENT(COMMENT_PARAGRAPH, "Directory Path: Core_SW_Cph/Components/Monitor_Server")
    COMMENT(COMMENT_PARAGRAPH, "Filename:  mon_ftd_user_instr.doc")
    COMMENT(COMMENT_PARAGRAPH, "https://cocmswww.europe.nokia.com:58443/document_browser/ccm_wa/co1core/Core_SW_Cph-Latest/Core_SW_Cph/Components/Monitor_Server/")
    NOTE("/8/")

    /* --------------------------------------------------------------------- */
    /* Constant definitions */
    /* --------------------------------------------------------------------- */

#ifndef COMM_GENERATE_MODEM_LICENSING
    COMMENT(COMMENT_TEXT, 
        "COMM_ISI_H_VERSION definition should not be used anymore, "
        "use instead the COMM_ISI_VERSION_Z(Y) definitions")
        
    EXT_ISIHDR_DONT_GENERATE    
    CONSTANT(COMM_ISI_H_VERSION,                COMM_ISI_VERSION_Y)
#endif /* COMM_GENERATE_MODEM_LICENSING */

    COMMENT(COMMENT_TEXT,
        "The range from 0xF0(240) to 0xFF(255) is reserved for common purposes and "
        "therefore should not be used for server-specific ISI messages.")
    EXT_ISIHDR_DONT_GENERATE
    CONSTANT(COMMON_MESSAGE,                    0xF0)

#ifndef COMM_GENERATE_MODEM_LICENSING
    COMMENT(COMMENT_TEXT,
        "Server base component is sending messages to itself and needs therefore a "
        "global message ID which is not in conflict with the real server's own "
        "message space address")
    EXT_ISIHDR_DONT_GENERATE
    CONSTANT(SBC_MESSAGE,                       0xF1)

    COMMENT(COMMENT_PARAGRAPH,
        "If the server's own message ID space is full (0x00-0xEF) there is a "
        "possibility to enlarge the address space by using the "
        "SERVER_MESSAGE_SPACE_EXTENSION message and in the following field "
        "specifying the actual message ID. ")
    COMMENT(COMMENT_PARAGRAPH,
        "Note that the usage of this space extension must be known when "
        "specifying the message because of the alignment restrictions. "
        "Same rules applies to the enlarged message ID space as for the "
        "original one (server specific space is from 0x00 to 0xEF). "
        "By this we support the possibility to have nested message ID extensions.")
    COMMENT(COMMENT_NEWLINE, "")
    COMMENT(COMMENT_PARAGRAPH,
        "So we are reusing the 0x00 - 0xEF address space with a field telling "
        "the extension level (see message 3.1 Message extension level). "
        "If the extension level is e.g. 3 it means that we have used the "
        "0x00 - 0xEF address space 4 times, so we have totally 4 x 240 "
        "messages available")
    EXT_ISIHDR_DONT_GENERATE
    CONSTANT(SERVER_MESSAGE_SPACE_EXTENSION,    0xF2)

    COMMENT(COMMENT_PARAGRAPH,
    	"Sub message address space 0x00-0xFF under message ID 0xF3 is reserved for "
	"3rd party specific messages i.e. Nokia should not be using this address "
	"space range.") 
    EXT_ISIHDR_DONT_GENERATE
    CONSTANT(THIRD_PARTY_SPECIFIC_MESSAGE,	0xF3) 
#endif /* COMM_GENERATE_MODEM_LICENSING */   

    EXT_ISIHDR_DONT_GENERATE
#ifdef COMM_GENERATE_MODEM_LICENSING
    PROPERTY(PROPERTY_ISIHDR_DONT_GENERATE)
    PROPERTY(PROPERTY_HTML_DONT_GENERATE)
#endif /* COMM_GENERATE_MODEM_LICENSING */ 
    COMMENT(COMMENT_TEXT, "-")               
    CONSTANT(COMM_MAX_FTD_STRING_LENGTH, COMM_MAX_FTD_STRING_LENGTH)

    EXT_ISIHDR_DONT_GENERATE
#ifdef COMM_GENERATE_MODEM_LICENSING
    PROPERTY(PROPERTY_ISIHDR_DONT_GENERATE)
    PROPERTY(PROPERTY_HTML_DONT_GENERATE)
#endif /* COMM_GENERATE_MODEM_LICENSING */
    COMMENT(COMMENT_TEXT, "-")                
    CONSTANT(COMM_MAX_FTD_DATA_LENGTH, COMM_MAX_FTD_DATA_LENGTH)

#ifndef COMM_GENERATE_MODEM_LICENSING
    EXT_ISIHDR_DONT_GENERATE
    COMMENT(COMMENT_TEXT, "-")
    CONSTANT(COMM_MAX_VERSION_COMMENTS_LENGTH, COMM_MAX_VERSION_COMMENTS_LENGTH)
#endif /* COMM_GENERATE_MODEM_LICENSING */   

    EXT_ISIHDR_DONT_GENERATE
#ifdef COMM_GENERATE_MODEM_LICENSING
    PROPERTY(PROPERTY_ISIHDR_DONT_GENERATE)
    PROPERTY(PROPERTY_HTML_DONT_GENERATE)
#endif /* COMM_GENERATE_MODEM_LICENSING */
    COMMENT(COMMENT_TEXT, "-")                
    CONSTANT(COMM_MAX_FTD_DATA_ITEMS, COMM_MAX_FTD_DATA_ITEMS)

    
    /* --------------------------------------------------------------------- */
    /* Symbol tables */
    /* --------------------------------------------------------------------- */

#ifndef COMM_GENERATE_MODEM_LICENSING
    EXT_ISIHDR_DONT_GENERATE
    CONST_TBL_BEGIN(COMM_FTD_FAIL_REASON, 8, BE, "", "")
        COMMENT(COMMENT_TEXT, "-")
        CONST_TBL_ENTRY(COMM_FTD_DATA_NOT_ACTIVATED,        0x00, "")
	COMMENT(COMMENT_TEXT, "-")
        CONST_TBL_ENTRY(COMM_FTD_DATA_NOT_SUPPORTED,        0x01, "")
	COMMENT(COMMENT_TEXT, "-")
        CONST_TBL_ENTRY(COMM_FTD_DATA_NOT_AVAILABLE,        0x02, "")
    CONST_TBL_END

    EXT_ISIHDR_DONT_GENERATE
    CONST_TBL_BEGIN(COMM_GEN_STATUS_INFO, 8, BE, "", "")
        COMMENT(COMMENT_TEXT, "-")
        CONST_TBL_ENTRY(COMM_STATUS_OK,         0x00, "")
	COMMENT(COMMENT_TEXT, "-")
        CONST_TBL_ENTRY(COMM_STATUS_FAIL,       0x01, "")
    CONST_TBL_END

    EXT_ISIHDR_DONT_GENERATE
    CONST_TBL_BEGIN(COMM_PWR_OFF_STATES, 8, BE, "", "")
        COMMENT(COMMENT_TEXT, "-")
        CONST_TBL_ENTRY(COMM_PWR_OFF,           0x00, "")
	COMMENT(COMMENT_TEXT, "-")
        CONST_TBL_ENTRY(COMM_PWR_CHARGING,      0x01, "")
	COMMENT(COMMENT_TEXT, "-")
        CONST_TBL_ENTRY(COMM_PWR_DISCHARGING,   0x02, "")
    CONST_TBL_END
#endif /* COMM_GENERATE_MODEM_LICENSING */ 

    EXT_ISIHDR_DONT_GENERATE
#ifdef COMM_GENERATE_MODEM_LICENSING
    PROPERTY(PROPERTY_ISIHDR_DONT_GENERATE)
    PROPERTY(PROPERTY_HTML_DONT_GENERATE)
#endif /* COMM_GENERATE_MODEM_LICENSING */                
    CONST_TBL_BEGIN(COMM_STRING_TYPE, 1, BE, "", "")
        COMMENT(COMMENT_TEXT, "-")
        CONST_TBL_ENTRY(COMM_STRING_ASCII,      COMM_STRING_ASCII, "")
	COMMENT(COMMENT_TEXT, "-")
        CONST_TBL_ENTRY(COMM_STRING_UNICODE,    COMM_STRING_UNICODE, "")
    CONST_TBL_END
    
    EXT_ISIHDR_DONT_GENERATE
    COMMENT(COMMENT_TEXT, "ISA Entity not Reachable States")             
    CONST_TBL_BEGIN(COMM_ISA_ENTITY_NOT_REACHABLE_STATUS, 8, BE, "000.019", "")
        COMMENT(COMMENT_TEXT, "-")
        CONST_TBL_ENTRY(COMM_ISA_ENTITY_NOT_AVAILABLE,  0x00, "")
	COMMENT(COMMENT_TEXT, "-")
        CONST_TBL_ENTRY(COMM_ISA_ENTITY_NOT_EXISTING,   0x01, "")
    CONST_TBL_END
    
#ifndef COMM_GENERATE_MODEM_LICENSING    
    EXT_ISIHDR_DONT_GENERATE
    CONST_TBL_BEGIN(COMM_FTD_SYSTEM_SWITCH_INFO, 8, BE, "000.020", "")
        COMMENT(COMMENT_TEXT, "-")
        CONST_TBL_ENTRY(COMM_FTD_SWITCH_WCDMA_TO_GSM, 0x01, "")
	COMMENT(COMMENT_TEXT, "-")
        CONST_TBL_ENTRY(COMM_FTD_SWITCH_GSM_TO_WCDMA, 0x02, "")
    CONST_TBL_END

    EXT_ISIHDR_DONT_GENERATE
    CONST_TBL_BEGIN(COMM_RF_OPERATION, 8, BE, "000.023", "")
        COMMENT(COMMENT_TEXT, "-")
        CONST_TBL_ENTRY(COMM_RF_ON, 0x00, "")
	COMMENT(COMMENT_TEXT, "-")
        CONST_TBL_ENTRY(COMM_RF_OFF,0x01, "")
	COMMENT(COMMENT_TEXT, "-")
        CONST_TBL_ENTRY_VER(COMM_RF_WIFI, 0x02, "000.027", "")
    CONST_TBL_END
#endif /* COMM_GENERATE_MODEM_LICENSING */  


    /* --------------------------------------------------------------------- */
    /* FTD data table */
    /* --------------------------------------------------------------------- */


    /* --------------------------------------------------------------------- */
    /* Sub block template definitions (for FTD's) */
    /* --------------------------------------------------------------------- */

    COMMENT(COMMENT_TEXT, 
        "Should just be used as a template for FTD data item description, see reference ")
    COMMENT_LINK(LINK_NOTE, "/5/", "", "")
    EXT_ISIHDR_DONT_GENERATE
#ifdef COMM_GENERATE_MODEM_LICENSING
    PROPERTY(PROPERTY_ISIHDR_DONT_GENERATE)
    PROPERTY(PROPERTY_HTML_DONT_GENERATE)
#endif /* COMM_GENERATE_MODEM_LICENSING */            
    SEQ_BEGIN(COMM_FTD_DATA_BYTE, CREATE_STRUCT, "", "")
        FTD_SB_16
        PROPERTY_STRING(PROPERTY_PMD_ANCHOR, "FTD_DATA_VALUE")
	COMMENT(COMMENT_TEXT, "-")
        VALUE(8, BE, data, "Data", DEC)
    SEQ_END
     
    COMMENT(COMMENT_TEXT, 
       "Should just be used as a template for FTD data item description, see reference ")
    COMMENT_LINK(LINK_NOTE, "/5/", "", "")
    EXT_ISIHDR_DONT_GENERATE
#ifdef COMM_GENERATE_MODEM_LICENSING
    PROPERTY(PROPERTY_ISIHDR_DONT_GENERATE)
    PROPERTY(PROPERTY_HTML_DONT_GENERATE)
#endif /* COMM_GENERATE_MODEM_LICENSING */            
    SEQ_BEGIN(COMM_FTD_DATA_WORD, CREATE_STRUCT, "", "")
        FTD_SB_16
	COMMENT(COMMENT_TEXT, "For future use. The value should always be zero.")
        FILLER_EX(filler1, 8, 1)
        PROPERTY_STRING(PROPERTY_PMD_ANCHOR, "FTD_DATA_VALUE")
	COMMENT(COMMENT_TEXT, "-")
        VALUE(16, BE, data, "Data", DEC)
	COMMENT(COMMENT_TEXT, "For future use. The value should always be zero.")
        FILLER_EX(filler2, 8, 1)
	COMMENT(COMMENT_TEXT, "For future use. The value should always be zero.")
        FILLER_EX(filler3, 8, 1)
    SEQ_END
    
    COMMENT(COMMENT_TEXT, 
        "Should just be used as a template for FTD data item description, see reference ")
    COMMENT_LINK(LINK_NOTE, "/5/", "", "")
    EXT_ISIHDR_DONT_GENERATE
#ifdef COMM_GENERATE_MODEM_LICENSING
    PROPERTY(PROPERTY_ISIHDR_DONT_GENERATE)
    PROPERTY(PROPERTY_HTML_DONT_GENERATE)
#endif /* COMM_GENERATE_MODEM_LICENSING */            
    SEQ_BEGIN(COMM_FTD_DATA_DWORD, CREATE_STRUCT, "", "")
        FTD_SB_16
	COMMENT(COMMENT_TEXT, "For future use. The value should always be zero.")
        FILLER_EX(filler1, 8, 1)
        PROPERTY_STRING(PROPERTY_PMD_ANCHOR, "FTD_DATA_VALUE")
	COMMENT(COMMENT_TEXT, "-")
        VALUE(32, BE, data, "Data", DEC)
    SEQ_END
    
    COMMENT(COMMENT_TEXT, 
        "Should just be used as a template for FTD data item description, see reference ")
    COMMENT_LINK(LINK_NOTE, "/5/", "", "")
#ifdef COMM_GENERATE_MODEM_LICENSING
    PROPERTY(PROPERTY_ISIHDR_DONT_GENERATE)
    PROPERTY(PROPERTY_HTML_DONT_GENERATE)
#endif /* COMM_GENERATE_MODEM_LICENSING */            
    EXT_ISIHDR_DONT_GENERATE
    SEQ_BEGIN(COMM_FTD_DATA_STRING, CREATE_STRUCT, "", "")
        FTD_SB_16
        MERGE_BEGIN(8, BE, string_lenght, "String Data")
            REFERENCE_CONST(str_type, "String type", STR_TYPE, COMM_STRING_TYPE)
            PROPERTY_VALUE(PROPERTY_ITEM_MAXIMUM_VALUE, COMM_MAX_FTD_STRING_LENGTH)
            REFERENCE(7, BE, str_len,  "String length", STR_LEN)
        MERGE_END
        CHOICE_BEGIN(data, "String data", STR_TYPE)
            CASE_BEGIN(COMM_STRING_UNICODE, "", "")
                PROPERTY_STRING(PROPERTY_PMD_ANCHOR, "FTD_DATA_STRING")
                STRING_REF(STRING_UNICODE_ZERO_TERMINATED, BE, string, "Data", STR_LEN, ISIHDR_RESERVE_SPACE)
            CASE_END
            DEFAULT_BEGIN("", "")
                PROPERTY_STRING(PROPERTY_PMD_ANCHOR, "FTD_DATA_STRING")
                STRING_REF(STRING_ASCII_ZERO_TERMINATED, BE, string, "Data", STR_LEN, ISIHDR_RESERVE_SPACE)
            DEFAULT_END
        CHOICE_END
        FILLER(FILLER_VARIABLE, 32)
    SEQ_END

    COMMENT(COMMENT_TEXT, 
       "Should just be used as a template for FTD data item description, see reference ")
    COMMENT_LINK(LINK_NOTE, "/5/", "", "")
#ifdef COMM_GENERATE_MODEM_LICENSING
    PROPERTY(PROPERTY_ISIHDR_DONT_GENERATE)
    PROPERTY(PROPERTY_HTML_DONT_GENERATE)
#endif /* COMM_GENERATE_MODEM_LICENSING */            
    EXT_ISIHDR_DONT_GENERATE
    SEQ_BEGIN(COMM_FTD_DATA_TABLE, CREATE_STRUCT, "", "")
        FTD_SB_16
        PROPERTY_VALUE(PROPERTY_ITEM_MAXIMUM_VALUE, COMM_MAX_FTD_DATA_LENGTH)
        REFERENCE(8, BE, data_length, "Data length", N)
        PROPERTY_STRING(PROPERTY_PMD_ANCHOR, "FTD_DATA_TABLE")
	COMMENT(COMMENT_TEXT, "-")
        SEQ_OF_REF(data, "Data", AUTOGEN_SEQ_BYTE_DEC, N, ISIHDR_RESERVE_SPACE)
        FILLER(FILLER_VARIABLE, 32)
    SEQ_END    

    /* --------------------------------------------------------------------- */
    /* Sub blocks */
    /* --------------------------------------------------------------------- */
    EXT_ISIHDR_DONT_GENERATE
    SB_ID_SECTION

#ifndef COMM_GENERATE_MODEM_LICENSING     
    EXT_ISIHDR_DONT_GENERATE
    SB_BEGIN(COMM_FTD_DATA_FAIL, "", "")
        COMM_SB_16
	COMMENT(COMMENT_TEXT, "For future use. The value should always be zero.")
        FILLER_EX(filler1, 8, 1)
	COMMENT(COMMENT_TEXT, "-")
        VALUE_CONST(not_identified_subblockID, "Not Identified Sub Block ID", FTD_ID)
        VALUE_CONST(fail_reason, "Fail Reason", COMM_FTD_FAIL_REASON)
	COMMENT(COMMENT_TEXT, "For future use. The value should always be zero.")
        FILLER_EX(filler2, 8, 1)
    SB_END
    
    EXT_ISIHDR_DONT_GENERATE
    SB_BEGIN(COMM_FTD_DATA_ALL, "", "")
        COMM_SB_16
	COMMENT(COMMENT_TEXT, "For future use. The value should always be zero.")
        FILLER_EX(filler1, 8, 1)
    SB_END

    EXT_ISIHDR_DONT_GENERATE
    SB_BEGIN(COMM_FTD_SYSTEM_SWITCH,"000.020","")
        COMM_SB_16
        VALUE_CONST(system_switch, "System Switch", COMM_FTD_SYSTEM_SWITCH_INFO)
    SB_END
#endif /* COMM_GENERATE_MODEM_LICENSING */      

/* COMM_NVD_SINGLE_TRANSFER is removed, it exists 
   in the handmade comm_isi.h;000.019 just to be sure not 
   to break the builds
*/


    /* --------------------------------------------------------------------- */
    /* Messages */
    /* --------------------------------------------------------------------- */

    EXT_ISIHDR_DONT_GENERATE
    MSG_ID_SECTION

    /* COMM_ISA_ENTITY_NOT_REACHABLE_RESP */

    EXT_STRUCT_NAME(COMM_ISA_ENTITY_NOT_REACHABLE_EXT_RESP)
    SUB_MSG_BEGIN(COMM_ISA_ENTITY_NOT_REACHABLE_RESP, COMMON_MESSAGE, MESSAGE_RESP, "000.019", "")
        COMM_MSG_HEADER
	COMMENT(COMMENT_TEXT, "-")
        VALUE(8, BE, not_delivered_messageID, "Not Delivered Message ID", HEX)
        VALUE_CONST(status, "Status", COMM_ISA_ENTITY_NOT_REACHABLE_STATUS)
	COMMENT(COMMENT_TEXT, "For future use. The value should always be zero.")
        FILLER_EX(filler1, 8, 1)
        FILLERS_2_0(filler2, filler3)
    SUB_MSG_END

    /* COMM_SERVICE_NOT_IDENTIFIED */

    EXT_STRUCT_NAME(COMM_SERVICE_NOT_IDENTIFIED_EXT_RESP)
    SUB_MSG_BEGIN(COMM_SERVICE_NOT_IDENTIFIED_RESP, COMMON_MESSAGE, MESSAGE_RESP, "", "")
        COMM_MSG_HEADER
	COMMENT(COMMENT_TEXT, "-")
        VALUE(8, BE, not_served_messageID, "Not Served Message ID", HEX)
#ifndef COMM_GENERATE_MODEM_LICENSING 	
        COMMENT(COMMENT_TEXT, "If not served message ID is SERVER_MESSAGE_SPACE_EXTENSION this field" 
        " informs the level (amount) of extension fields in the message where the final message ID" 
        " resides which couldn´t be recognized. (0 means no extension in use), see the note in chapter ")
        COMMENT_LINK(LINK_CONSTANT, "SERVER_MESSAGE_SPACE_EXTENSION", "", "")
        COMMENT(COMMENT_TEXT, " about extension field usage.")	
        VALUE(8, BE, message_extension, "Message Extension Level", DEC)
#else
	COMMENT(COMMENT_TEXT, "For future use. The value should always be zero.")
	FILLER_EX(filler, 8, 1)	
#endif /* COMM_GENERATE_MODEM_LICENSING */ 
	COMMENT(COMMENT_TEXT, "-") 
        VALUE(8, BE, not_served_submessageID, "Not Served Sub Message ID", HEX)
        FILLERS_2_0(filler1, filler2)
    SUB_MSG_END
    
#ifndef COMM_GENERATE_MODEM_LICENSING 
    /* COMM_SERVER_VERSION_GET */

    EXT_STRUCT_NAME(COMM_SERVER_VERSION_GET_EXT_REQ)
    SUB_MSG_BEGIN(COMM_SERVER_VERSION_GET_REQ, COMMON_MESSAGE, MESSAGE_REQ, "", "")
        COMM_MSG_HEADER
	COMMENT(COMMENT_TEXT, "For future use. The value should always be zero.")
        FILLER_EX(filler1, 8, 1)
        FILLERS_0_2(filler2, filler3)
    SUB_MSG_END

    EXT_STRUCT_NAME(COMM_SERVER_VERSION_GET_EXT_RESP)
    SUB_MSG_BEGIN(COMM_SERVER_VERSION_GET_RESP, COMMON_MESSAGE, MESSAGE_RESP, "", "")
        COMM_MSG_HEADER
	COMMENT(COMMENT_TEXT, "-")
        VALUE(8, BE, version_nbr_zzz, "Version Number Z", DEC)
	COMMENT(COMMENT_TEXT, "-")
        VALUE(8, BE, version_nbr_yyy, "Version Number Y", DEC)
	COMMENT(COMMENT_TEXT, "-")
        VALUE(8, BE, version_nbr_xxx, "Version Number X", DEC)
	COMMENT(COMMENT_TEXT, "-")
        VALUE(8, BE, release_year, "Release Year", DEC)
	COMMENT(COMMENT_TEXT, "-")
        VALUE(8, BE, release_month, "Release Month", DEC)
	COMMENT(COMMENT_TEXT, "-")
        VALUE(8, BE, release_day, "Release Day", DEC)
        COMMENT(COMMENT_TEXT, "MSB must be set to 0 because of ASCII string ")
        PROPERTY_VALUE(PROPERTY_ITEM_MAXIMUM_VALUE, COMM_MAX_VERSION_COMMENTS_LENGTH)
        REFERENCE(8, BE, version_comments_length, "Version Comments Length", N)
        STRING_REF(STRING_ASCII_ZERO_TERMINATED, BE, version_comments, "Version Comments", N, ISIHDR_RESERVE_SPACE)
    SUB_MSG_END

    SUB_MSG_PAIR(COMM_SERVER_VERSION_GET_REQ, COMMON_MESSAGE,
                 COMM_SERVER_VERSION_GET_RESP, COMMON_MESSAGE)
#endif /* COMM_GENERATE_MODEM_LICENSING */                      

    /* COMM_ISI_VERSION_GET */

    EXT_STRUCT_NAME(COMM_ISI_VERSION_GET_EXT_REQ)
    SUB_MSG_BEGIN(COMM_ISI_VERSION_GET_REQ, COMMON_MESSAGE, MESSAGE_REQ, "", "")
        COMM_MSG_HEADER_
	COMMENT(COMMENT_TEXT, "For future use. The value should always be zero.")
        FILLER_EX(filler, 8, 1)
        FILLERS_0_2(filler2, filler3)
    SUB_MSG_END

    EXT_STRUCT_NAME(COMM_ISI_VERSION_GET_EXT_RESP)
    SUB_MSG_BEGIN(COMM_ISI_VERSION_GET_RESP, COMMON_MESSAGE, MESSAGE_RESP, "", "")
        COMM_MSG_HEADER_
	COMMENT(COMMENT_TEXT, "-")
        VALUE(8, BE, isi_version_zzz, "ISI Version Z", DEC)
	COMMENT(COMMENT_TEXT, "-")
        VALUE(8, BE, isi_version_yyy, "ISI Version Y", DEC)
	COMMENT(COMMENT_TEXT, "For future use. The value should always be zero.")
        FILLER_EX(filler1, 8, 1)
        FILLERS_2_0(filler2, filler3)
    SUB_MSG_END

    SUB_MSG_PAIR(COMM_ISI_VERSION_GET_REQ, COMMON_MESSAGE,
                 COMM_ISI_VERSION_GET_RESP, COMMON_MESSAGE)

#ifndef COMM_GENERATE_MODEM_LICENSING 
    /* COMM_FTD_DATA */

    EXT_STRUCT_NAME(COMM_FTD_DATA_EXT_REQ)
    SUB_MSG_BEGIN(COMM_FTD_DATA_REQ, COMMON_MESSAGE, MESSAGE_REQ, "", "")
        COMM_MSG_HEADER
        PROPERTY_VALUE(PROPERTY_ITEM_MAXIMUM_VALUE, COMM_MAX_FTD_DATA_ITEMS)
        REFERENCE(8, BE, nbr_of_FTD_data_items, "Number of asked FTD Data", N)
        COMMENT(COMMENT_PARAGRAPH, "COMM_FTD_DATA_ALL is NOT applicable here")
        SB_LST_REF_BEGIN(LIST_OF_SUBBLOCK_IDS, FTD_data_items, "List of FTD data items", N, ISIHDR_RESERVE_SPACE)
            SB_LST_ENTRY(SB_FTD_ANY)
        SB_LST_REF_END
    SUB_MSG_END

    EXT_STRUCT_NAME(COMM_FTD_DATA_EXT_RESP)
    PROPERTY(PROPERTY_PMD_PUBLIC)
    SUB_MSG_BEGIN(COMM_FTD_DATA_RESP, COMMON_MESSAGE, MESSAGE_RESP, "", "")
        COMM_MSG_HEADER
        FILLERS_0_2(filler1, filler2)
        REFERENCE(8, BE, nbr_of_subblocks, "Number of FTD Data", N)
        COMMENT(COMMENT_TEXT, "see reference ")
        COMMENT_LINK(LINK_NOTE, "/5/", "", "")
        COMMENT(COMMENT_TEXT, "and ")
        COMMENT_LINK(LINK_NOTE, "/8/","","")
        COMMENT(COMMENT_TEXT, " for sub blocks")
        SB_LST_REF_BEGIN(LIST_OF_SUBBLOCKS, sub_blocks, "Sub Blocks", N, ISIHDR_DONT_GENERATE)
            SB_LST_ENTRY(SB_FTD_ANY)
            SB_LST_ENTRY(COMM_FTD_DATA_FAIL)
            SB_LST_ENTRY(COMM_FTD_SYSTEM_SWITCH)
        SB_LST_REF_END
    SUB_MSG_END

    SUB_MSG_PAIR(COMM_FTD_DATA_REQ, COMMON_MESSAGE,
                 COMM_FTD_DATA_RESP, COMMON_MESSAGE)


    /* COMM_FTD_TEST_DATA */

    EXT_STRUCT_NAME(COMM_FTD_TEST_DATA_EXT_REQ)
    PROPERTY(PROPERTY_PMD_PUBLIC)
    SUB_MSG_BEGIN(COMM_FTD_TEST_DATA_REQ, COMMON_MESSAGE, MESSAGE_REQ, "", "")
        COMM_MSG_HEADER
	COMMENT(COMMENT_TEXT, "For future use. The value should always be zero.")
        FILLER_EX(filler1, 8, 1)
        COMMENT(COMMENT_TEXT, "Use FTD sub block IDs as parameter")
        PROPERTY_STRING(PROPERTY_PMD_ANCHOR, "FTD_TEST_DATA_STRUCTURE")
        VALUE(16, BE, FTD_data_item, "FTD data item", FTD_ID)            
        FILLERS_2_0(filler2, filler3)
        COMMENT(COMMENT_TEXT, "User provided data")
        VALUE(32, BE, user_provided_data, "Input Data", DEC)
    SUB_MSG_END

    EXT_STRUCT_NAME(COMM_FTD_TEST_DATA_EXT_RESP)
    SUB_MSG_BEGIN(COMM_FTD_TEST_DATA_RESP, COMMON_MESSAGE, MESSAGE_RESP, "", "")
        COMM_MSG_HEADER
        VALUE_CONST(status, "Status", COMM_GEN_STATUS_INFO)
        FILLERS_0_2(filler1, filler2)
    SUB_MSG_END

    SUB_MSG_PAIR(COMM_FTD_TEST_DATA_REQ, COMMON_MESSAGE,
                 COMM_FTD_TEST_DATA_RESP, COMMON_MESSAGE)


    /* COMM_FTD_DATA_DEACTIVATE */

    EXT_STRUCT_NAME(COMM_FTD_DATA_DEACTIVATE_EXT_REQ)
    SUB_MSG_BEGIN(COMM_FTD_DATA_DEACTIVATE_REQ, COMMON_MESSAGE, MESSAGE_REQ, "", "")
        COMM_MSG_HEADER
        PROPERTY_VALUE(PROPERTY_ITEM_MAXIMUM_VALUE, COMM_MAX_FTD_DATA_ITEMS)
        REFERENCE(8, BE, nbr_of_FTD_data_items, "Number of asked FTD Data", N)
        SB_LST_REF_BEGIN(LIST_OF_SUBBLOCK_IDS, FTD_data_items, "List of FTD data items", N, ISIHDR_RESERVE_SPACE)
            SB_LST_ENTRY(SB_FTD_ANY)
            SB_LST_ENTRY(COMM_FTD_DATA_ALL)
        SB_LST_REF_END
    SUB_MSG_END

    EXT_STRUCT_NAME(COMM_FTD_DATA_DEACTIVATE_EXT_RESP)
    SUB_MSG_BEGIN(COMM_FTD_DATA_DEACTIVATE_RESP, COMMON_MESSAGE, MESSAGE_RESP, "", "")
        COMM_MSG_HEADER
        FILLERS_0_2(filler1, filler2)
        REFERENCE(8, BE, nbr_of_subblocks, "Number of FTD Data", N)
        SB_LST_REF_BEGIN(LIST_OF_SUBBLOCKS, sub_blocks, "Sub blocks", N, ISIHDR_DONT_GENERATE)
            SB_LST_ENTRY(COMM_FTD_DATA_FAIL)
        SB_LST_REF_END
    SUB_MSG_END

    SUB_MSG_PAIR(COMM_FTD_DATA_DEACTIVATE_REQ, COMMON_MESSAGE,
                 COMM_FTD_DATA_DEACTIVATE_RESP, COMMON_MESSAGE)


    /* COMM_PWR_OFF_CONFIRM */

    EXT_STRUCT_NAME(COMM_PWR_OFF_CONFIRM_EXT_REQ)
    SUB_MSG_BEGIN(COMM_PWR_OFF_CONFIRM_REQ, COMMON_MESSAGE, MESSAGE_REQ, "", "")
        COMM_MSG_HEADER
	COMMENT(COMMENT_TEXT, "For future use. The value should always be zero.")
        FILLER_EX(filler1, 8, 1)
        FILLERS_0_2(filler2, filler3)
    SUB_MSG_END

    EXT_STRUCT_NAME(COMM_PWR_OFF_CONFIRM_EXT_RESP)
    SUB_MSG_BEGIN(COMM_PWR_OFF_CONFIRM_RESP, COMMON_MESSAGE, MESSAGE_RESP, "", "")
        COMM_MSG_HEADER
        VALUE_CONST(state, "Power Off State", COMM_PWR_OFF_STATES)
        FILLERS_0_2(filler1, filler2)
    SUB_MSG_END

    SUB_MSG_PAIR(COMM_PWR_OFF_CONFIRM_REQ, COMMON_MESSAGE,
                 COMM_PWR_OFF_CONFIRM_RESP, COMMON_MESSAGE)


    /* COMM_NVD_SET_DEFAULT */

    COMMENT(COMMENT_TEXT, "For a detailed description, see reference ")
    COMMENT_LINK(LINK_NOTE, "/6/", "", "")
    COMMENT(COMMENT_TEXT, " and ")
    COMMENT_LINK(LINK_NOTE, "/7/", "", "")
    COMMENT(COMMENT_NEWLINE, "")
    COMMENT(COMMENT_NEWLINE, "")
    COMMENT(COMMENT_TEXT, 
            "Note: The word 'reason' is used interchangeably with 'level' when used "
            "in the context of factory settings. Although 'reason' more accurately "
            "describes the parameter (and is used in all new documenation), it is "
            "possible to encounter 'level' in some NVD documenation that was approved "
            "prior to use of the term 'reason'.")

    EXT_STRUCT_NAME(COMM_NVD_SET_DEFAULT_EXT_REQ)
    SUB_MSG_BEGIN(COMM_NVD_SET_DEFAULT_REQ, COMMON_MESSAGE, MESSAGE_REQ, "", "")
        COMM_MSG_HEADER
	COMMENT(COMMENT_TEXT, "For future use. The value should always be zero.")
        FILLER_EX(filler1, 8, 1)
        FILLERS_0_2(filler2, filler3)
        COMMENT(COMMENT_TEXT, "See reference ")
        COMMENT_LINK(LINK_NOTE, "/7/", "", "")
        COMMENT(COMMENT_TEXT, " for different reason values")
        VALUE(32, BE, reason, "Reason", HEX)
    SUB_MSG_END

    COMMENT(COMMENT_TEXT, "For a detailed description, see reference ")
    COMMENT_LINK(LINK_NOTE, "/6/", "", "")
    COMMENT(COMMENT_TEXT, " and ")
    COMMENT_LINK(LINK_NOTE, "/7/", "", "")

    EXT_STRUCT_NAME(COMM_NVD_SET_DEFAULT_EXT_RESP)
    SUB_MSG_BEGIN(COMM_NVD_SET_DEFAULT_RESP, COMMON_MESSAGE, MESSAGE_RESP, "", "")
        COMM_MSG_HEADER
        VALUE_CONST(status, "Status", COMM_GEN_STATUS_INFO)    
        FILLERS_0_2(filler1, filler2)
    SUB_MSG_END

    SUB_MSG_PAIR(COMM_NVD_SET_DEFAULT_REQ, COMMON_MESSAGE,
                 COMM_NVD_SET_DEFAULT_RESP, COMMON_MESSAGE)


    /* COMM_NVD_VERSION_CHK */

    EXT_STRUCT_NAME(COMM_NVD_VERSION_CHK_EXT_REQ)
    SUB_MSG_BEGIN(COMM_NVD_VERSION_CHK_REQ, COMMON_MESSAGE, MESSAGE_REQ, "", "")
        COMM_MSG_HEADER
	COMMENT(COMMENT_TEXT, "For future use. The value should always be zero.")
        FILLER_EX(filler1, 8, 1)
        FILLERS_0_2(filler2, filler3)
    SUB_MSG_END

    EXT_STRUCT_NAME(COMM_NVD_VERSION_CHK_EXT_RESP)
    SUB_MSG_BEGIN(COMM_NVD_VERSION_CHK_RESP, COMMON_MESSAGE, MESSAGE_RESP, "", "")
        COMM_MSG_HEADER
        VALUE_CONST(status, "Status", COMM_GEN_STATUS_INFO)
        FILLERS_0_2(filler1, filler2)
    SUB_MSG_END

    SUB_MSG_PAIR(COMM_NVD_VERSION_CHK_REQ, COMMON_MESSAGE,
                 COMM_NVD_VERSION_CHK_RESP, COMMON_MESSAGE)


    /* COMM_RF_CONTROL */

    EXT_STRUCT_NAME(COMM_RF_CONTROL_EXT_REQ)
    SUB_MSG_BEGIN(COMM_RF_CONTROL_REQ, COMMON_MESSAGE, MESSAGE_REQ, "000.023", "")
        COMM_MSG_HEADER
        VALUE_CONST(operation, "RF Operation", COMM_RF_OPERATION)
        FILLERS_0_2(filler1, filler2)
    SUB_MSG_END
    
    EXT_STRUCT_NAME(COMM_RF_CONTROL_EXT_RESP)
    SUB_MSG_BEGIN(COMM_RF_CONTROL_RESP, COMMON_MESSAGE, MESSAGE_RESP, "000.023", "")
        COMM_MSG_HEADER
        VALUE_CONST(status, "Status", COMM_GEN_STATUS_INFO)        
        FILLERS_0_2(filler1, filler2)
    SUB_MSG_END

    SUB_MSG_PAIR(COMM_RF_CONTROL_REQ, COMMON_MESSAGE,
                 COMM_RF_CONTROL_RESP, COMMON_MESSAGE)

    /* COMM_SERVICE_NOT_AUTHENTICATED_RESP */

    EXT_STRUCT_NAME(COMM_SERVICE_NOT_AUTHENTICATED_EXT_RESP)
    SUB_MSG_BEGIN(COMM_SERVICE_NOT_AUTHENTICATED_RESP, COMMON_MESSAGE, MESSAGE_RESP, "000.026", "")
        COMM_MSG_HEADER
	COMMENT(COMMENT_TEXT, "-")
        VALUE(8, BE, not_served_messageID, "Not Served Message ID", HEX)
        FILLERS_0_2(filler1, filler2)
    SUB_MSG_END
#endif /* COMM_GENERATE_MODEM_LICENSING */  
    RES_END


/*  5    DATA TYPES */

/*  6    CLASSES */

/*  7    OBJECTS */

/*  8    DATA STRUCTURES */

/*  9    FUNCTION PROTOTYPES */

#endif /* _COMM_ISI_M_H_INCLUDE_ */

/* End of file comm_isi_m.h */
