/*
NOKIA                                                             CONFIDENTIAL
Devices R&D Salo
DCT/ASD/AM/SWAM
Leif Karilainen



                  comm_isi.h
                  --------------------------------
                  SW Include Document - ANSI C/C++



Continuus Ref:
--------------
database:        ou1gif

project path:    global_interface/coresw_interface/coresw_public

name:            comm_isi.h

version:         000.031

type:            incl

instance:        sa_mcu#1


ISI header file for Common Messages



Generated with autogen version 08_w51 on 30-Dec-2008 11:49:28
DO NOT EDIT - changes will be lost at next autogeneration

Copyright (c) Nokia Corporation. All rights reserved.


ISI version change history

Version     : 000.031    APPROVED    11-Dec-2008    Leif Karilainen
Reason      : Minor updates
Reference   : See SWAM ADB LK08120847276
Description : Added 3rd party specific address space, OxF3

Version     : 000.030    APPROVED    14-Nov-2008    Leif Karilainen
Reason      : Minor updates
Reference   : See SWAM ADB LK08111334707
Description : Regenerated all common message output files as autogen had some
              problems to generate correct message length macros with the old
              autogen version.

Version     : 000.029    APPROVED    03-May-2007    Leif Karilainen
Reason      : Minor updates
Reference   : See SWAM ADB LK07050349205
Description : Removed autogen warnings caused by old macro usage. Updated
              references.

Version     : 000.028    APPROVED    08-Dec-2006    Leif Karilainen
Reason      : Update to support extended resource ID concept behind flag
              COMMON_MESSAGES_EXTENDED_INTERFACE first time.
Reference   : See SWAM ADB LK06120455502
Description : -

Version     : 000.027    APPROVED    04-Jan-2006    Leif Karilainen
Reason      : Minor update
Reference   : See SWAM ADB LK06010448865
Description : Added Entry COMM_RF_WIFI to COMM_RF_OPERATION

Version     : 000.026    APPROVED    26-Aug-2004    Leif Karilainen
Reason      : New message.
Reference   : See SWAM ADB LK04082636973
Description : COMM_SERVICE_NOT_AUTHENTICATED_RESP introduced.

Version     : 000.025    APPROVED    26-Apr-2004    Leif Karilainen
Reason      : comm_isi_m.h needs updates.
Reference   : See SWAM ADB LK04042648164
Description : HEX interpretation for some fields in
              COMM_SERVICE_NOT_IDENTIFIED_RESP and one field in
              COMM_ISA_ENTITY_NOT_REACHABLE_RESP messages.

Version     : 000.024    APPROVED    01-Mar-2004    Leif Karilainen
Reason      : comm_isi_16.h needs updates.
Reference   : See SWAM ADB LK04030137132
Description : New defines for merge fields in comm_isi_16.h have been taken
              into use. See e.g. PROPERTY_ISIHDR_GENERATE_MERGED_MASKS_16.

Version     : 000.023    APPROVED    12-Jan-2004    Leif Karilainen
Reason      : New common ISI message.
Reference   : See SWAM ADB LK04011246215.
Description : COMM_RF_CONTROL_REQ(RESP) added.

Version     : 000.022    APPROVED    13-Oct-2003    Leif Karilainen
Reason      : Comments from inspection.
Reference   : See SWAM ADB LK03093036140.
Description : Continuus html project info added to cover page.

Version     : 000.021    APPROVED    29-Sep-2003    Leif Karilainen
Reason      : Autogenerated common ISI header taken into use in sw packages.
Reference   : See SWAM ADB LK03093036140.
Description : COMM_FTD_DATA_STRING C-structure changed so that string[] field
              is generated. References have been updated.

Version     : 000.020    APPROVED    28-Apr-2003    Leif Karilainen
Reason      : New message macro template taken into use and some macros
              updated because of new autogen version (DEFINE_CONST_TBL_BEGIN
              -->CONST_TBL_BEGIN and similar kind of cases).
              COMM_FTD_SYSTEM_SWITCH sub block added.
              COMM_MAX_FTD_STRING_LENGTH changed from 127 to 124. This
              version is now compatible with the
              ISI:COMMON_FEATURES.BASE-SPEC;000.020.
Reference   : See SWAM ADB LK03042933779.
Description : -

Version     : 000.019    NON-DRAFT   30-Nov-2001    Leif Karilainen
Reason      : Defects found in inspection are corrected. This version is now
              compatible with the ISI:COMMON_MESSAGES.BASE-SPEC;19.0
Reference   : See SWAM ADB LK01112144458
Description : The message name for COMM_SERVICE_PROVIDER_NOT_FOUND_RESP
              changed to COMM_ISA_ENTITY_NOT_REACHABLE_RESP and status field
              added to the message

------------------------------------------------------------------------------

Description

The common ISI feature descriptions can be found from reference /4/, where
the glossary is presented

*/

#ifndef _COMM_ISI_H
#define _COMM_ISI_H

#include "isi_conf.h"

#ifndef COMM_ISI_VERSION
#define COMM_ISI_VERSION
#define COMM_ISI_VERSION_Z   0
#define COMM_ISI_VERSION_Y  31
#endif

#define COMM_ISI_MIN_VERSION(z,y) \
 ((COMM_ISI_VERSION_Z == (z) && COMM_ISI_VERSION_Y >= (y)) || \
  (COMM_ISI_VERSION_Z > (z)))

#if !COMM_ISI_MIN_VERSION(0,19)
#error The specified interface version is not supported by this header file
#elif COMM_ISI_MIN_VERSION(0,32)
#error The specified interface version is not supported by this header file
#endif


/* ----------------------------------------------------------------------- */
/* Constants                                                               */
/* ----------------------------------------------------------------------- */

/* COMM_ISI_H_VERSION definition should not be used anymore, use instead the
   COMM_ISI_VERSION_Z(Y) definitions
*/
#define COMM_ISI_H_VERSION                       0x1F
/* Range from 0xF0(240) to 0xFF(255) is reserved for common purposes and
   should therefore not be used for server specific ISI messages
*/
#define COMMON_MESSAGE                           0xF0
/* Server base component is sending messages to itself and needs therefore a
   global message ID which is not in conflict with the real server's own
   message space address
*/
#define SBC_MESSAGE                              0xF1
/* If the server's own message ID space is full (0x00-0xEF) there is a
   possibility to enlarge the address space by using the
   SERVER_MESSAGE_SPACE_EXTENSION message and in the following field
   specifying the actual message ID. 
   Note that the usage of this space extension must be known when specifying
   the message because of the alignment restrictions. Same rules applies to
   the enlarged message ID space as for the original one (server specific
   space is from 0x00 to 0xEF). By this we support the possibility to have
   nested message ID extensions.
   
   So we are reusing the 0x00 - 0xEF address space with a field telling the
   extension level (see message 3.1 Message extension level). If the
   extension level is e.g. 3 it means that we have used the 0x00 - 0xEF
   address space 4 times, so we have totally 4 x 240 messages available
*/
#define SERVER_MESSAGE_SPACE_EXTENSION           0xF2
/* Sub message address space 0x00-0xFF under message ID 0xF3 is reserved for
   3rd party specific messages i.e. Nokia should not be using this address
   space range.
*/
#define THIRD_PARTY_SPECIFIC_MESSAGE             0xF3
#define COMM_MAX_FTD_STRING_LENGTH               0x7C
#define COMM_MAX_FTD_DATA_LENGTH                 0xF8
#define COMM_MAX_VERSION_COMMENTS_LENGTH         0x7F
#define COMM_MAX_FTD_DATA_ITEMS                  0xFF

/* ----------------------------------------------------------------------- */
/* Constant Table: COMM_FTD_FAIL_REASON                                    */
/* ----------------------------------------------------------------------- */
typedef uint8 COMM_FTD_FAIL_REASON_CONST;

#define COMM_FTD_DATA_NOT_ACTIVATED              0x00
#define COMM_FTD_DATA_NOT_SUPPORTED              0x01
#define COMM_FTD_DATA_NOT_AVAILABLE              0x02

/* ----------------------------------------------------------------------- */
/* Constant Table: COMM_GEN_STATUS_INFO                                    */
/* ----------------------------------------------------------------------- */
typedef uint8 COMM_GEN_STATUS_INFO_CONST;

#define COMM_STATUS_OK                           0x00
#define COMM_STATUS_FAIL                         0x01

/* ----------------------------------------------------------------------- */
/* Constant Table: COMM_PWR_OFF_STATES                                     */
/* ----------------------------------------------------------------------- */
typedef uint8 COMM_PWR_OFF_STATES_CONST;

#define COMM_PWR_OFF                             0x00
#define COMM_PWR_CHARGING                        0x01
#define COMM_PWR_DISCHARGING                     0x02

/* ----------------------------------------------------------------------- */
/* Constant Table: COMM_STRING_TYPE                                        */
/* ----------------------------------------------------------------------- */
#define COMM_STRING_ASCII                        0x00
#define COMM_STRING_UNICODE                      0x01

/* ----------------------------------------------------------------------- */
/* Constant Table: COMM_ISA_ENTITY_NOT_REACHABLE_STATUS - Valid from version 000.019 */
/* ----------------------------------------------------------------------- */
/* ISA Entity not Reachable States */
typedef uint8 COMM_ISA_ENTITY_NOT_REACHABLE_STATUS_CONST;

#define COMM_ISA_ENTITY_NOT_AVAILABLE            0x00
#define COMM_ISA_ENTITY_NOT_EXISTING             0x01

/* ----------------------------------------------------------------------- */
/* Constant Table: COMM_FTD_SYSTEM_SWITCH_INFO - Valid from version 000.020 */
/* ----------------------------------------------------------------------- */
typedef uint8 COMM_FTD_SYSTEM_SWITCH_INFO_CONST;

#define COMM_FTD_SWITCH_WCDMA_TO_GSM             0x01
#define COMM_FTD_SWITCH_GSM_TO_WCDMA             0x02

/* ----------------------------------------------------------------------- */
/* Constant Table: COMM_RF_OPERATION - Valid from version 000.023          */
/* ----------------------------------------------------------------------- */
typedef uint8 COMM_RF_OPERATION_CONST;

#define COMM_RF_ON                               0x00
#define COMM_RF_OFF                              0x01
#define COMM_RF_WIFI                             0x02

/* ----------------------------------------------------------------------- */
/* Message ID's and Submessage ID's                                        */
/* ----------------------------------------------------------------------- */


/* Submessage ID's for COMMON_MESSAGE */
#define COMM_SERVICE_NOT_IDENTIFIED_RESP         0x01
#define COMM_SERVER_VERSION_GET_REQ              0x02
#define COMM_SERVER_VERSION_GET_RESP             0x03
#define COMM_FTD_DATA_REQ                        0x04
#define COMM_FTD_DATA_RESP                       0x05
#define COMM_FTD_TEST_DATA_REQ                   0x06
#define COMM_FTD_TEST_DATA_RESP                  0x07
#define COMM_FTD_DATA_DEACTIVATE_REQ             0x08
#define COMM_FTD_DATA_DEACTIVATE_RESP            0x09
#define COMM_PWR_OFF_CONFIRM_REQ                 0x0C
#define COMM_PWR_OFF_CONFIRM_RESP                0x0D
#define COMM_NVD_SET_DEFAULT_REQ                 0x0E
#define COMM_NVD_SET_DEFAULT_RESP                0x0F
#define COMM_NVD_VERSION_CHK_REQ                 0x10
#define COMM_NVD_VERSION_CHK_RESP                0x11
#define COMM_ISI_VERSION_GET_REQ                 0x12
#define COMM_ISI_VERSION_GET_RESP                0x13
#define COMM_ISA_ENTITY_NOT_REACHABLE_RESP       0x14
#define COMM_RF_CONTROL_REQ                      0x15
#define COMM_RF_CONTROL_RESP                     0x16
#define COMM_SERVICE_NOT_AUTHENTICATED_RESP      0x17

/* ----------------------------------------------------------------------- */
/* Subblock ID's                                                           */
/* ----------------------------------------------------------------------- */

#define COMM_FTD_DATA_FAIL                       0x0000
#define COMM_FTD_DATA_ALL                        0x0001
#define COMM_FTD_SYSTEM_SWITCH                   0x0002

/* ----------------------------------------------------------------------- */
/* Subblock template: COMM_FTD_DATA_BYTE                                   */
/* ----------------------------------------------------------------------- */
/* Should just be used as a template for FTD data item description, see
   reference /5/
*/

typedef struct
    {
    uint16  subblockID;
    uint8   subblock_length;
    uint8   data;
    } COMM_FTD_DATA_BYTE_STR;

#define SIZE_COMM_FTD_DATA_BYTE_STR   sizeof(COMM_FTD_DATA_BYTE_STR)


/* ----------------------------------------------------------------------- */
/* Subblock template: COMM_FTD_DATA_WORD                                   */
/* ----------------------------------------------------------------------- */
/* Should just be used as a template for FTD data item description, see
   reference /5/
*/

typedef struct
    {
    uint16  subblockID;
    uint8   subblock_length;
    uint8   filler1;
    uint16  data;
    uint8   filler2;
    uint8   filler3;
    } COMM_FTD_DATA_WORD_STR;

#define SIZE_COMM_FTD_DATA_WORD_STR   sizeof(COMM_FTD_DATA_WORD_STR)


/* ----------------------------------------------------------------------- */
/* Subblock template: COMM_FTD_DATA_DWORD                                  */
/* ----------------------------------------------------------------------- */
/* Should just be used as a template for FTD data item description, see
   reference /5/
*/

typedef struct
    {
    uint16  subblockID;
    uint8   subblock_length;
    uint8   filler1;
    uint32  data;
    } COMM_FTD_DATA_DWORD_STR;

#define SIZE_COMM_FTD_DATA_DWORD_STR   sizeof(COMM_FTD_DATA_DWORD_STR)


/* ----------------------------------------------------------------------- */
/* Subblock template: COMM_FTD_DATA_STRING                                 */
/* ----------------------------------------------------------------------- */
/* Should just be used as a template for FTD data item description, see
   reference /5/
*/

typedef struct
    {
    uint16  subblockID;
    uint8   subblock_length;
    /* x-------  String type
       -xxxxxxx  String length
    */
    uint8   string_lenght;
    char    string[COMM_MAX_FTD_STRING_LENGTH];
    } COMM_FTD_DATA_STRING_STR;

#define SIZE_COMM_FTD_DATA_STRING_STR   (sizeof(uint16) + 2*sizeof(uint8) + \
        COMM_MAX_FTD_STRING_LENGTH*sizeof(char))


/* ----------------------------------------------------------------------- */
/* Subblock template: COMM_FTD_DATA_TABLE                                  */
/* ----------------------------------------------------------------------- */
/* Should just be used as a template for FTD data item description, see
   reference /5/
*/

typedef struct
    {
    uint16  subblockID;
    uint8   subblock_length;
    uint8   data_length;
    uint8   data[COMM_MAX_FTD_DATA_LENGTH];
    } COMM_FTD_DATA_TABLE_STR;

#define SIZE_COMM_FTD_DATA_TABLE_STR   (sizeof(uint16) + \
        (2 + COMM_MAX_FTD_DATA_LENGTH)*sizeof(uint8))


/* ----------------------------------------------------------------------- */
/* Subblock: COMM_FTD_DATA_FAIL                                            */
/* ----------------------------------------------------------------------- */

typedef struct
    {
    uint16  subblockID;
    uint8   subblock_length;
    uint8   filler1;
    uint16  not_identified_subblockID;
    /* Values from the constant table COMM_FTD_FAIL_REASON */
    uint8   fail_reason;
    uint8   filler2;
    } COMM_FTD_DATA_FAIL_STR;

#define SIZE_COMM_FTD_DATA_FAIL_STR   sizeof(COMM_FTD_DATA_FAIL_STR)


/* ----------------------------------------------------------------------- */
/* Subblock: COMM_FTD_DATA_ALL                                             */
/* ----------------------------------------------------------------------- */

typedef struct
    {
    uint16  subblockID;
    uint8   subblock_length;
    uint8   filler1;
    } COMM_FTD_DATA_ALL_STR;

#define SIZE_COMM_FTD_DATA_ALL_STR   sizeof(COMM_FTD_DATA_ALL_STR)


/* ----------------------------------------------------------------------- */
/* Subblock: COMM_FTD_SYSTEM_SWITCH - Valid from version 000.020           */
/* ----------------------------------------------------------------------- */

typedef struct
    {
    uint16  subblockID;
    uint8   subblock_length;
    /* Values from the constant table COMM_FTD_SYSTEM_SWITCH_INFO */
    uint8   system_switch;
    } COMM_FTD_SYSTEM_SWITCH_STR;

#define SIZE_COMM_FTD_SYSTEM_SWITCH_STR   sizeof(COMM_FTD_SYSTEM_SWITCH_STR)


/* ----------------------------------------------------------------------- */
/* Message: COMM_ISA_ENTITY_NOT_REACHABLE_RESP - Valid from version 000.019 */
/* ----------------------------------------------------------------------- */

typedef struct
    {
    uint8   transactionID;
    uint8   messageID;
    uint8   submessageID;
    uint8   not_delivered_messageID;
    /* Values from the constant table COMM_ISA_ENTITY_NOT_REACHABLE_STATUS */
    uint8   status;
    uint8   filler1;
    uint8   filler2;
    uint8   filler3;
    } COMM_ISA_ENTITY_NOT_REACHABLE_RESP_STR;

#define SIZE_COMM_ISA_ENTITY_NOT_REACHABLE_RESP_STR   \
        sizeof(COMM_ISA_ENTITY_NOT_REACHABLE_RESP_STR)


/* ----------------------------------------------------------------------- */
/* Message: COMM_SERVICE_NOT_IDENTIFIED_RESP                               */
/* ----------------------------------------------------------------------- */

typedef struct
    {
    uint8   transactionID;
    uint8   messageID;
    uint8   submessageID;
    uint8   not_served_messageID;
    /* If not served message ID is SERVER_MESSAGE_SPACE_EXTENSION this field
       informs the level (amount) of extension fields in the message where
       the final message ID resides which couldn´t be recognized. (0 means no
       extension in use), see the note in chapter
       SERVER_MESSAGE_SPACE_EXTENSION about extension field usage.
    */
    uint8   message_extension;
    uint8   not_served_submessageID;
    uint8   filler1;
    uint8   filler2;
    } COMM_SERVICE_NOT_IDENTIFIED_RESP_STR;

#define SIZE_COMM_SERVICE_NOT_IDENTIFIED_RESP_STR   \
        sizeof(COMM_SERVICE_NOT_IDENTIFIED_RESP_STR)


/* ----------------------------------------------------------------------- */
/* Message: COMM_SERVER_VERSION_GET_REQ                                    */
/* ----------------------------------------------------------------------- */

typedef struct
    {
    uint8   transactionID;
    uint8   messageID;
    uint8   submessageID;
    uint8   filler1;
    } COMM_SERVER_VERSION_GET_REQ_STR;

#define SIZE_COMM_SERVER_VERSION_GET_REQ_STR   \
        sizeof(COMM_SERVER_VERSION_GET_REQ_STR)


/* ----------------------------------------------------------------------- */
/* Message: COMM_SERVER_VERSION_GET_RESP                                   */
/* ----------------------------------------------------------------------- */

typedef struct
    {
    uint8   transactionID;
    uint8   messageID;
    uint8   submessageID;
    uint8   version_nbr_zzz;
    uint8   version_nbr_yyy;
    uint8   version_nbr_xxx;
    uint8   release_year;
    uint8   release_month;
    uint8   release_day;
    /* MSB must be set to 0 because of ASCII string  */
    uint8   version_comments_length;
    char    version_comments[COMM_MAX_VERSION_COMMENTS_LENGTH];
    } COMM_SERVER_VERSION_GET_RESP_STR;

#define SIZE_COMM_SERVER_VERSION_GET_RESP_STR   (10*sizeof(uint8) + \
        COMM_MAX_VERSION_COMMENTS_LENGTH*sizeof(char))


/* ----------------------------------------------------------------------- */
/* Message: COMM_ISI_VERSION_GET_REQ                                       */
/* ----------------------------------------------------------------------- */

typedef struct
    {
    uint8   transaction_ID;
    uint8   messageID;
    uint8   submessageID;
    uint8   filler;
    } COMM_ISI_VERSION_GET_REQ_STR;

#define SIZE_COMM_ISI_VERSION_GET_REQ_STR   \
        sizeof(COMM_ISI_VERSION_GET_REQ_STR)


/* ----------------------------------------------------------------------- */
/* Message: COMM_ISI_VERSION_GET_RESP                                      */
/* ----------------------------------------------------------------------- */

typedef struct
    {
    uint8   transaction_ID;
    uint8   messageID;
    uint8   submessageID;
    uint8   isi_version_zzz;
    uint8   isi_version_yyy;
    uint8   filler1;
    uint8   filler2;
    uint8   filler3;
    } COMM_ISI_VERSION_GET_RESP_STR;

#define SIZE_COMM_ISI_VERSION_GET_RESP_STR   \
        sizeof(COMM_ISI_VERSION_GET_RESP_STR)


/* ----------------------------------------------------------------------- */
/* Message: COMM_FTD_DATA_REQ                                              */
/* ----------------------------------------------------------------------- */

typedef struct
    {
    uint8   transactionID;
    uint8   messageID;
    uint8   submessageID;
    uint8   nbr_of_FTD_data_items;
    /* COMM_FTD_DATA_ALL is NOT applicable here
       Subblock ID's:
       COMM_FTD_DATA_*
    */
    uint16  FTD_data_items[COMM_MAX_FTD_DATA_ITEMS];
    } COMM_FTD_DATA_REQ_STR;

#define SIZE_COMM_FTD_DATA_REQ_STR   (4*sizeof(uint8) + \
        COMM_MAX_FTD_DATA_ITEMS*sizeof(uint16))


/* ----------------------------------------------------------------------- */
/* Message: COMM_FTD_DATA_RESP                                             */
/* ----------------------------------------------------------------------- */

typedef struct
    {
    uint8   transactionID;
    uint8   messageID;
    uint8   submessageID;
    uint8   nbr_of_subblocks;
    /* see reference /5/and /8/ for sub blocks
       Subblock list:
       COMM_FTD_DATA_*
       COMM_FTD_DATA_FAIL
       COMM_FTD_SYSTEM_SWITCH
    */
    } COMM_FTD_DATA_RESP_STR;

#define SIZE_COMM_FTD_DATA_RESP_STR   (4*sizeof(uint8))


/* ----------------------------------------------------------------------- */
/* Message: COMM_FTD_TEST_DATA_REQ                                         */
/* ----------------------------------------------------------------------- */

typedef struct
    {
    uint8   transactionID;
    uint8   messageID;
    uint8   submessageID;
    uint8   filler1;
    uint16  FTD_data_item; /* Use FTD sub block IDs as parameter */
    uint8   filler2;
    uint8   filler3;
    uint32  user_provided_data; /* User provided data */
    } COMM_FTD_TEST_DATA_REQ_STR;

#define SIZE_COMM_FTD_TEST_DATA_REQ_STR   sizeof(COMM_FTD_TEST_DATA_REQ_STR)


/* ----------------------------------------------------------------------- */
/* Message: COMM_FTD_TEST_DATA_RESP                                        */
/* ----------------------------------------------------------------------- */

typedef struct
    {
    uint8   transactionID;
    uint8   messageID;
    uint8   submessageID;
    uint8   status; /* Values from the constant table COMM_GEN_STATUS_INFO */
    } COMM_FTD_TEST_DATA_RESP_STR;

#define SIZE_COMM_FTD_TEST_DATA_RESP_STR   \
        sizeof(COMM_FTD_TEST_DATA_RESP_STR)


/* ----------------------------------------------------------------------- */
/* Message: COMM_FTD_DATA_DEACTIVATE_REQ                                   */
/* ----------------------------------------------------------------------- */

typedef struct
    {
    uint8   transactionID;
    uint8   messageID;
    uint8   submessageID;
    uint8   nbr_of_FTD_data_items;
    /* Subblock ID's:
       COMM_FTD_DATA_*
       COMM_FTD_DATA_ALL
    */
    uint16  FTD_data_items[COMM_MAX_FTD_DATA_ITEMS];
    } COMM_FTD_DATA_DEACTIVATE_REQ_STR;

#define SIZE_COMM_FTD_DATA_DEACTIVATE_REQ_STR   (4*sizeof(uint8) + \
        COMM_MAX_FTD_DATA_ITEMS*sizeof(uint16))


/* ----------------------------------------------------------------------- */
/* Message: COMM_FTD_DATA_DEACTIVATE_RESP                                  */
/* ----------------------------------------------------------------------- */

typedef struct
    {
    uint8   transactionID;
    uint8   messageID;
    uint8   submessageID;
    uint8   nbr_of_subblocks;
    /* Subblock list:
       COMM_FTD_DATA_FAIL
    */
    } COMM_FTD_DATA_DEACTIVATE_RESP_STR;

#define SIZE_COMM_FTD_DATA_DEACTIVATE_RESP_STR   (4*sizeof(uint8))


/* ----------------------------------------------------------------------- */
/* Message: COMM_PWR_OFF_CONFIRM_REQ                                       */
/* ----------------------------------------------------------------------- */

typedef struct
    {
    uint8   transactionID;
    uint8   messageID;
    uint8   submessageID;
    uint8   filler1;
    } COMM_PWR_OFF_CONFIRM_REQ_STR;

#define SIZE_COMM_PWR_OFF_CONFIRM_REQ_STR   \
        sizeof(COMM_PWR_OFF_CONFIRM_REQ_STR)


/* ----------------------------------------------------------------------- */
/* Message: COMM_PWR_OFF_CONFIRM_RESP                                      */
/* ----------------------------------------------------------------------- */

typedef struct
    {
    uint8   transactionID;
    uint8   messageID;
    uint8   submessageID;
    uint8   state;   /* Values from the constant table COMM_PWR_OFF_STATES */
    } COMM_PWR_OFF_CONFIRM_RESP_STR;

#define SIZE_COMM_PWR_OFF_CONFIRM_RESP_STR   \
        sizeof(COMM_PWR_OFF_CONFIRM_RESP_STR)


/* ----------------------------------------------------------------------- */
/* Message: COMM_NVD_SET_DEFAULT_REQ                                       */
/* ----------------------------------------------------------------------- */
/* For a detailed description, see reference /6/ and /7/
   
   Note: The word 'reason' is used interchangeably with 'level' when used in
   the context of factory settings. Although 'reason' more accurately
   describes the parameter (and is used in all new documenation), it is
   possible to encounter 'level' in some NVD documenation that was approved
   prior to use of the term 'reason'.
*/

typedef struct
    {
    uint8   transactionID;
    uint8   messageID;
    uint8   submessageID;
    uint8   filler1;
    uint32  reason;       /* See reference /7/ for different reason values */
    } COMM_NVD_SET_DEFAULT_REQ_STR;

#define SIZE_COMM_NVD_SET_DEFAULT_REQ_STR   \
        sizeof(COMM_NVD_SET_DEFAULT_REQ_STR)


/* ----------------------------------------------------------------------- */
/* Message: COMM_NVD_SET_DEFAULT_RESP                                      */
/* ----------------------------------------------------------------------- */
/* For a detailed description, see reference /6/ and /7/ */

typedef struct
    {
    uint8   transactionID;
    uint8   messageID;
    uint8   submessageID;
    uint8   status; /* Values from the constant table COMM_GEN_STATUS_INFO */
    } COMM_NVD_SET_DEFAULT_RESP_STR;

#define SIZE_COMM_NVD_SET_DEFAULT_RESP_STR   \
        sizeof(COMM_NVD_SET_DEFAULT_RESP_STR)


/* ----------------------------------------------------------------------- */
/* Message: COMM_NVD_VERSION_CHK_REQ                                       */
/* ----------------------------------------------------------------------- */

typedef struct
    {
    uint8   transactionID;
    uint8   messageID;
    uint8   submessageID;
    uint8   filler1;
    } COMM_NVD_VERSION_CHK_REQ_STR;

#define SIZE_COMM_NVD_VERSION_CHK_REQ_STR   \
        sizeof(COMM_NVD_VERSION_CHK_REQ_STR)


/* ----------------------------------------------------------------------- */
/* Message: COMM_NVD_VERSION_CHK_RESP                                      */
/* ----------------------------------------------------------------------- */

typedef struct
    {
    uint8   transactionID;
    uint8   messageID;
    uint8   submessageID;
    uint8   status; /* Values from the constant table COMM_GEN_STATUS_INFO */
    } COMM_NVD_VERSION_CHK_RESP_STR;

#define SIZE_COMM_NVD_VERSION_CHK_RESP_STR   \
        sizeof(COMM_NVD_VERSION_CHK_RESP_STR)


/* ----------------------------------------------------------------------- */
/* Message: COMM_RF_CONTROL_REQ - Valid from version 000.023               */
/* ----------------------------------------------------------------------- */

typedef struct
    {
    uint8   transactionID;
    uint8   messageID;
    uint8   submessageID;
    uint8   operation; /* Values from the constant table COMM_RF_OPERATION */
    } COMM_RF_CONTROL_REQ_STR;

#define SIZE_COMM_RF_CONTROL_REQ_STR   sizeof(COMM_RF_CONTROL_REQ_STR)


/* ----------------------------------------------------------------------- */
/* Message: COMM_RF_CONTROL_RESP - Valid from version 000.023              */
/* ----------------------------------------------------------------------- */

typedef struct
    {
    uint8   transactionID;
    uint8   messageID;
    uint8   submessageID;
    uint8   status; /* Values from the constant table COMM_GEN_STATUS_INFO */
    } COMM_RF_CONTROL_RESP_STR;

#define SIZE_COMM_RF_CONTROL_RESP_STR   sizeof(COMM_RF_CONTROL_RESP_STR)


/* ----------------------------------------------------------------------- */
/* Message: COMM_SERVICE_NOT_AUTHENTICATED_RESP - Valid from version 000.026 */
/* ----------------------------------------------------------------------- */

typedef struct
    {
    uint8   transactionID;
    uint8   messageID;
    uint8   submessageID;
    uint8   not_served_messageID;
    } COMM_SERVICE_NOT_AUTHENTICATED_RESP_STR;

#define SIZE_COMM_SERVICE_NOT_AUTHENTICATED_RESP_STR   \
        sizeof(COMM_SERVICE_NOT_AUTHENTICATED_RESP_STR)




/* ----------------------------------------------------------------------- */
/* Notes                                                                   */
/* ----------------------------------------------------------------------- */
/*
   /1/  Autogeneration Process
        Intranet
        http://tracing.europe.nokia.com/autogen/overview.asp

   /2/  ISI Server Specification Documentation Guidelines
        Document code: DSY02803-EN
        DocMan location: eslns42/SRV/Nokia
        DocMan: DCT DocMan
        Filename: TP/PP/ppmgmtdm.nsf

   /3/  ISI General Information
        Document code: DSY02801-EN
        DocMan location: eslns42/SRV/Nokia
        DocMan: DCT DocMan
        Filename: TP/PP/ppmgmtdm.nsf

   /4/  ISI Common Feature Descriptions
        Continuus Database: ou1gif
        Continuus Project: GIF_SPECS-ou1gif#browse
        Directory Path: GIF_SPECS/CoreSW/coresw_public_spec
        Filename:  i_comm_fp.doc
        http://oucmswww.nmp.nokia.com:58080/document_browser/ccm_wa/GIF_SPECS/CoreSW/coresw_public_spec/

   /5/  Common R&D Display Data and Layout
        Continuus Database: sa1core
        Continuus Project: paradise_doc-ou1core#browse
        Directory Path: paradise_doc/FTD
        Filename:  rd_display_spec.doc
        https://oucmswww.nmp.nokia.com:58443/document_browser/ccm_wa/paradise_doc/FTD/

   /6/  NVD Library Interface Specification
        Continuus Database: ou1gif
        Continuus Project: GIF_SPECS-ou1gif#browse
        Directory Path: GIF_SPECS/CoreSW/coresw_public_spec
        Filename:  nvd_lib_inf.doc
        http://oucmswww.nmp.nokia.com:58080/document_browser/ccm_wa/GIF_SPECS/CoreSW/coresw_public_spec/

   /7/  ISI Non-Volatile Data Server Feature Descriptions
        Continuus Database: ou1gif
        Continuus Project: GIF_SPECS-ou1gif#browse
        Directory Path: GIF_SPECS/CoreSW/coresw_public_spec
        Filename:  i_nvd_f.doc
        http://oucmswww.nmp.nokia.com:58080/document_browser/ccm_wa/GIF_SPECS/CoreSW/coresw_public_spec/

   /8/  Monitor server FTD user instructions
        Continuus Database: co1core
        Continuus Project: Core_SW_Cph-Latest
        Directory Path: Core_SW_Cph/Components/Monitor_Server
        Filename:  mon_ftd_user_instr.doc
        https://cocmswww.europe.nokia.com:58443/document_browser/ccm_wa/co1core/Core_SW_Cph-Latest/Core_SW_Cph/Components/Monitor_Server/
*/


#endif /* _COMM_ISI_H */
