/*
NOKIA
R&D Copenhagen
CoreSW/Corleone









                entry_points_m.h
                ----------------
                SW Include






Project:          autogen

%name:            entry_points_m.h %
%version:         10 %
%instance:        co1tss_1 %
%derived_by:      eliasen %
%date_modified:   Mon Aug  3 12:30:24 2009 %

Copyright (c) Nokia. All rights reserved
*/


/* ============================================================================================= */
/* Abstract */
/* ============================================================================================= */

/*  Header file for autogen

    This file contains definitions of all trace entry points
*/

#ifndef _ENTRY_POINTS_H_
#define _ENTRY_POINTS_H_


#ifdef AUTOGEN_INCLUDE_MCU_TRACES
        #define ENTRY_POINT_MCU_TRACE PMD_ENTRY_POINT_MCU_TRACE
        PROPERTY_VALUE(PROPERTY_PMD_PHONET_DEVICE_ID, AUTOGEN_DEVICE_CURRENT)
        PROPERTY(PROPERTY_PROTOCOL_HAS_NO_MESSAGES)
        RES_BEGIN(RESOURCE_PROTOCOL, ENTRY_POINT_MCU_TRACE, MCU_TRACE, "MCU trace entry point", "", FALSE)
            MSG_BEGIN(AUTOGEN_NO_MESSAGE_ID, MESSAGE_NONE, "", "")
#if ((defined AUTOGEN_ENVIRONMENT_PRODUCT_DEVICE) &&(PMD_FILE_FORMAT >= 501))
                REFERENCE(16, NATIVE, trc_grp, "Trace Group", TRACE_GROUP_ID)
                REFERENCE(16, NATIVE, trc_id, "Trace ID", TRACE_ID)
                REFERENCE(16, NATIVE, trc_data_length, "Trace Data Length", TRACE_DATA_LENGTH)
                BLOCK_REF(NATIVE, trc_data, "Trace data", BLOCK_PMD_ANCHOR, "MCU_TRACE_STRUCTURE", NULL, 0, REF_AS_MANY_AS_POSSIBLE)
#else
                REFERENCE(16, BE, trc_grp, "Trace Group", TRACE_GROUP_ID)
                REFERENCE(16, BE, trc_id, "Trace ID", TRACE_ID)
                REFERENCE(16, BE, trc_data_length, "Trace Data Length", TRACE_DATA_LENGTH)
                BLOCK_REF(BE, trc_data, "Trace data", BLOCK_PMD_ANCHOR, "MCU_TRACE_STRUCTURE", NULL, 0, REF_AS_MANY_AS_POSSIBLE)
#endif
            MSG_END

        RES_END
#endif /* AUTOGEN_INCLUDE_MCU_TRACES */

#ifdef AUTOGEN_INCLUDE_NOS_TRACES
        #define ENTRY_POINT_NOS_TRACE PMD_ENTRY_POINT_NOS_TRACE
        PROPERTY_VALUE(PROPERTY_PMD_PHONET_DEVICE_ID, AUTOGEN_DEVICE_CURRENT)
        PROPERTY(PROPERTY_PROTOCOL_HAS_NO_MESSAGES)
        RES_BEGIN(RESOURCE_PROTOCOL, ENTRY_POINT_NOS_TRACE, NOS_TRACE, "NOS trace entry point", "", FALSE)
            PROPERTY(PROPERTY_SUPPRESS_AUTOGEN_WARNINGS)
            MSG_BEGIN(AUTOGEN_NO_MESSAGE_ID, MESSAGE_NONE, "", "")
                PROPERTY(PROPERTY_SUPPRESS_AUTOGEN_WARNINGS)
                REFERENCE(8, BE, trace_id, "Trace ID", TRACE_ID_OS)
                BLOCK_REF(BE, trc_data, "Trace data", BLOCK_PMD_ANCHOR, "OS_TRACE_STRUCTURE", NULL, 0, REF_AS_MANY_AS_POSSIBLE)
            MSG_END
        RES_END
#endif /* AUTOGEN_INCLUDE_NOS_TRACES */


#ifdef AUTOGEN_INCLUDE_HAL_TRACES
        #define ENTRY_POINT_HAL_TRACE PMD_ENTRY_POINT_HAL_TRACE
        PROPERTY_VALUE(PROPERTY_PMD_PHONET_DEVICE_ID, AUTOGEN_DEVICE_CURRENT)
        PROPERTY(PROPERTY_PROTOCOL_HAS_NO_MESSAGES)
        RES_BEGIN(RESOURCE_PROTOCOL, ENTRY_POINT_HAL_TRACE, HAL_TRACE, "HAL trace entry point", "", FALSE)
            PROPERTY(PROPERTY_SUPPRESS_AUTOGEN_WARNINGS)
            MSG_BEGIN(AUTOGEN_NO_MESSAGE_ID, MESSAGE_NONE, "", "")
                PROPERTY(PROPERTY_SUPPRESS_AUTOGEN_WARNINGS)
                REFERENCE(8, BE, trace_group_id, "Trace Group ID", TRACE_GROUP_ID_HAL)
                PROPERTY(PROPERTY_SUPPRESS_AUTOGEN_WARNINGS)
                REFERENCE(8, BE, trace_id, "Trace ID", TRACE_ID_HAL)
                BLOCK_REF(BE, trc_data, "Trace data", BLOCK_PMD_ANCHOR, "HAL_TRACE_STRUCTURE", NULL, 0, REF_LENGTH_UNKNOWN)
            MSG_END
        RES_END
#endif /* AUTOGEN_INCLUDE_HAL_TRACES */

#ifdef AUTOGEN_INCLUDE_HSP_TRACES
       #define ENTRY_POINT_HSP_TRACE PMD_ENTRY_POINT_HSP_TRACE
       PROPERTY_VALUE(PROPERTY_PMD_PHONET_DEVICE_ID, AUTOGEN_DEVICE_CURRENT)
       PROPERTY(PROPERTY_PROTOCOL_HAS_NO_MESSAGES)
       RES_BEGIN(RESOURCE_PROTOCOL, ENTRY_POINT_HSP_TRACE, HSP_XTI_TRACE, "HSP trace entry point", "", FALSE)
           PROPERTY(PROPERTY_SUPPRESS_AUTOGEN_WARNINGS)
           MSG_BEGIN(AUTOGEN_NO_MESSAGE_ID, MESSAGE_NONE, "", "")
               PROPERTY(PROPERTY_SUPPRESS_AUTOGEN_WARNINGS)
               REFERENCE(8, BE, trace_group_id, "Trace Group ID", TRACE_GROUP_ID_HSP)
               PROPERTY(PROPERTY_SUPPRESS_AUTOGEN_WARNINGS)
               REFERENCE(8, BE, trace_id, "Trace ID", TRACE_ID_HSP)
               BLOCK_REF(BE, trc_data, "Trace data", BLOCK_PMD_ANCHOR, "HSP_TRACE_STRUCTURE", NULL, 0, REF_LENGTH_UNKNOWN)
           MSG_END
       RES_END
#endif /* AUTOGEN_INCLUDE_HSP_TRACES */

#ifdef AUTOGEN_INCLUDE_INVARIANT_TRACES
        PROPERTY(PROPERTY_PROTOCOL_HAS_NO_MESSAGES)
        PROPERTY(PROPERTY_PMD_PUBLIC)
        PROPERTY(PROPERTY_PMD_RESTRICTED)

        #define ENTRY_POINT_INVARIANT_TRACE PMD_ENTRY_POINT_INVARIANT_TRACE
        PROPERTY_VALUE(PROPERTY_PMD_PHONET_DEVICE_ID, AUTOGEN_DEVICE_GENERAL)
        RES_BEGIN(RESOURCE_PROTOCOL, ENTRY_POINT_INVARIANT_TRACE, INV_TRACE, "Invariant trace entry point", "", FALSE)
            PROPERTY(PROPERTY_SUPPRESS_AUTOGEN_WARNINGS)
            MSG_BEGIN(AUTOGEN_NO_MESSAGE_ID, MESSAGE_NONE, "", "")
                PROPERTY(PROPERTY_SUPPRESS_AUTOGEN_WARNINGS)
                REFERENCE(8, BE, trc_ent, "Trace entity", TRACE_ENTITY_ID_INVARIANT)
                PROPERTY(PROPERTY_SUPPRESS_AUTOGEN_WARNINGS)
                REFERENCE(8, BE, trc_grp, "Trace group", TRACE_GROUP_ID_INVARIANT)
                PROPERTY(PROPERTY_SUPPRESS_AUTOGEN_WARNINGS)
                REFERENCE(8, BE, trc_id, "Trace ID", TRACE_ID_INVARIANT)
                PROPERTY(PROPERTY_SUPPRESS_AUTOGEN_WARNINGS)
                REFERENCE(16, BE, trc_data_length, "Trace data length", TRACE_DATA_LENGTH)
                BLOCK_REF(BE, trc_data, "Trace data", BLOCK_PMD_ANCHOR, "INVARIANT_TRACE_STRUCTURE", NULL, 0, REF_AS_MANY_AS_POSSIBLE)
            MSG_END

        RES_END
#endif /* AUTOGEN_INCLUDE_INVARIANT_TRACES */ 

#ifdef AUTOGEN_INCLUDE_VENDOR_COMPONENT_TRACES
        PROPERTY(PROPERTY_PROTOCOL_HAS_NO_MESSAGES)

        #define ENTRY_POINT_VENDOR_COMPONENT_TRACE PMD_ENTRY_POINT_VENDOR_COMPONENT_TRACE
        PROPERTY_VALUE(PROPERTY_PMD_PHONET_DEVICE_ID, AUTOGEN_DEVICE_CURRENT)
        RES_BEGIN(RESOURCE_PROTOCOL, ENTRY_POINT_VENDOR_COMPONENT_TRACE, VENDOR_TRACE, "Vendor component trace entry point", "", FALSE)
            PROPERTY(PROPERTY_SUPPRESS_AUTOGEN_WARNINGS)
            MSG_BEGIN(AUTOGEN_NO_MESSAGE_ID, MESSAGE_NONE, "", "")
                PROPERTY(PROPERTY_SUPPRESS_AUTOGEN_WARNINGS)
                REFERENCE(8, BE, trc_ent, "Trace entity", TRACE_ENTITY_ID_VENDOR)
                PROPERTY(PROPERTY_SUPPRESS_AUTOGEN_WARNINGS)
                REFERENCE(8, BE, trc_grp, "Trace group", TRACE_GROUP_ID_VENDOR)
                PROPERTY(PROPERTY_SUPPRESS_AUTOGEN_WARNINGS)
                REFERENCE(8, BE, trc_id, "Trace ID", TRACE_ID_VENDOR)
                BLOCK_REF(BE, trc_data, "Trace data", BLOCK_PMD_ANCHOR, "VENDOR_COMPONENT_TRACE_STRUCTURE", NULL, 0, REF_AS_MANY_AS_POSSIBLE)
            MSG_END

        RES_END
#endif /* AUTOGEN_INCLUDE_VENDOR_COMPONENT_TRACES */ 

#ifdef AUTOGEN_INCLUDE_CDSP_TRACES
        #define ENTRY_POINT_CDSP5_TRACE PMD_ENTRY_POINT_CDSP5_TRACE
        PROPERTY_VALUE(PROPERTY_PMD_PHONET_DEVICE_ID, PN_DEV_DSP_MAIN)
        PROPERTY(PROPERTY_PROTOCOL_HAS_NO_MESSAGES)
        RES_BEGIN(RESOURCE_PROTOCOL, ENTRY_POINT_CDSP5_TRACE, CDSP5_TRACE, "CDSP5 trace entry point", "", FALSE)

            MSG_BEGIN(AUTOGEN_NO_MESSAGE_ID, MESSAGE_NONE, "", "")
                PROPERTY(PROPERTY_SUPPRESS_AUTOGEN_WARNINGS)
                REFERENCE(16, BE, trc_ent, "Trace entity", TRACE_ENTITY_ID_CDSP5)
                PROPERTY(PROPERTY_SUPPRESS_AUTOGEN_WARNINGS)
                REFERENCE(16, BE, trc_grp, "Trace group", TRACE_GROUP_ID_CDSP5)
                PROPERTY(PROPERTY_SUPPRESS_AUTOGEN_WARNINGS)
                REFERENCE(16, BE, trc_id, "Trace ID", TRACE_ID_CDSP5)
                BLOCK_REF(BE, trc_data, "Trace data", BLOCK_PMD_ANCHOR, "CDSP5_TRACE_STRUCTURE", NULL, 0, REF_AS_MANY_AS_POSSIBLE)
            MSG_END

        RES_END

        #define ENTRY_POINT_CDSP5_TRACE_OLD PMD_ENTRY_POINT_CDSP5_TRACE_OLD
        PROPERTY_VALUE(PROPERTY_PMD_PHONET_DEVICE_ID, PN_DEV_DSP_MAIN)
        PROPERTY(PROPERTY_PROTOCOL_HAS_NO_MESSAGES)
        RES_BEGIN(RESOURCE_PROTOCOL, ENTRY_POINT_CDSP5_TRACE_OLD, CDSP5_TRACE_OLD, "Old CDSP5 trace entry point", "", FALSE)
            PROPERTY(PROPERTY_SUPPRESS_AUTOGEN_WARNINGS)
            MSG_BEGIN(AUTOGEN_NO_MESSAGE_ID, MESSAGE_NONE, "", "")
                BLOCK_REF(BE, data, "Data", BLOCK_PMD_ANCHOR, 
                    "DSP5_TRACE_STRUCTURE", NULL, 0, REF_AS_MANY_AS_POSSIBLE)        
            MSG_END
        RES_END
#endif /* AUTOGEN_INCLUDE_CDSP_TRACES */ 

#ifdef AUTOGEN_INCLUDE_ADSP_TRACES
        #define ENTRY_POINT_ADSP5_TRACE PMD_ENTRY_POINT_ADSP5_TRACE
        PROPERTY_VALUE(PROPERTY_PMD_PHONET_DEVICE_ID, PN_DEV_DSP_AUX)
        PROPERTY(PROPERTY_PROTOCOL_HAS_NO_MESSAGES)
        RES_BEGIN(RESOURCE_PROTOCOL, ENTRY_POINT_ADSP5_TRACE, ADSP5_TRACE, "ADSP5 trace entry point", "", FALSE)

            MSG_BEGIN(AUTOGEN_NO_MESSAGE_ID, MESSAGE_NONE, "", "")
                PROPERTY(PROPERTY_SUPPRESS_AUTOGEN_WARNINGS)
                REFERENCE(16, BE, trc_ent, "Trace entity", TRACE_ENTITY_ID_ADSP5)
                PROPERTY(PROPERTY_SUPPRESS_AUTOGEN_WARNINGS)
                REFERENCE(16, BE, trc_grp, "Trace group", TRACE_GROUP_ID_ADSP5)
                PROPERTY(PROPERTY_SUPPRESS_AUTOGEN_WARNINGS)
                REFERENCE(16, BE, trc_id, "Trace ID", TRACE_ID_ADSP5)
                BLOCK_REF(BE, trc_data, "Trace data", BLOCK_PMD_ANCHOR, "ADSP5_TRACE_STRUCTURE", NULL, 0, REF_AS_MANY_AS_POSSIBLE)
            MSG_END

        RES_END

        #define ENTRY_POINT_ADSP5_TRACE_OLD PMD_ENTRY_POINT_ADSP5_TRACE_OLD
        PROPERTY_VALUE(PROPERTY_PMD_PHONET_DEVICE_ID, PN_DEV_DSP_AUX)
        PROPERTY(PROPERTY_PROTOCOL_HAS_NO_MESSAGES)
        RES_BEGIN(RESOURCE_PROTOCOL, ENTRY_POINT_ADSP5_TRACE_OLD, ADSP5_TRACE_OLD, "Old ADSP5 trace entry point", "", FALSE)
            PROPERTY(PROPERTY_SUPPRESS_AUTOGEN_WARNINGS)
            MSG_BEGIN(AUTOGEN_NO_MESSAGE_ID, MESSAGE_NONE, "", "")
                BLOCK_REF(BE, data, "Data", BLOCK_PMD_ANCHOR, "DSP5_ADSP_TRACE_STRUCTURE", NULL, 0, REF_AS_MANY_AS_POSSIBLE)        
            MSG_END
        RES_END
#endif /* AUTOGEN_INCLUDE_ADSP_TRACES */ 

#ifdef AUTOGEN_INCLUDE_SYMBIAN_TRACES
        #define ENTRY_POINT_SYMBIAN_TRACE PMD_ENTRY_POINT_SYMBIAN_TRACE
        PROPERTY_VALUE(PROPERTY_PMD_PHONET_DEVICE_ID, PN_DEV_SOS)
        PROPERTY(PROPERTY_PROTOCOL_HAS_NO_MESSAGES)
        RES_BEGIN(RESOURCE_PROTOCOL, ENTRY_POINT_SYMBIAN_TRACE, SYMBIAN_TRACE, "Symbian trace entry point", "", FALSE)
            PROPERTY(PROPERTY_SUPPRESS_AUTOGEN_WARNINGS)
            MSG_BEGIN(AUTOGEN_NO_MESSAGE_ID, MESSAGE_NONE, "", "")
                PROPERTY(PROPERTY_SUPPRESS_AUTOGEN_WARNINGS)
                REFERENCE(32, BE, trc_component_id, "Component ID", TRACE_ENTITY_ID_SYMBIAN)
                PROPERTY(PROPERTY_SUPPRESS_AUTOGEN_WARNINGS)
                REFERENCE(16, BE, trc_grp_id, "Trace Group ID", TRACE_GROUP_ID_SYMBIAN)
                PROPERTY(PROPERTY_SUPPRESS_AUTOGEN_WARNINGS)
                REFERENCE(16, BE, trc_id, "Trace ID", TRACE_ID_SYMBIAN)
                BLOCK_REF(BE, trc_data, "Trace data", BLOCK_PMD_ANCHOR, "SYMBIAN_TRACE_STRUCTURE", NULL, 0, REF_AS_MANY_AS_POSSIBLE)
            MSG_END

        RES_END
#endif /* AUTOGEN_INCLUDE_SYMBIAN_TRACES */


#endif /* _ENTRY_POINTS_H_ */

