/*
NOKIA
R&D Copenhagen
CoreSW/Corleone








                ti2grp.c
                ---------
                SW Module







Project:          autogen

%name:            ti2grp.c %
%version:         co1tss#27 %
%instance:        co1pctls_1 %
%derived_by:      eliasen %
%date_modified:   Fri Jan 07 16:24:11 2011 %

Copyright (c) Nokia. All rights reserved
*/


/* ============================================================================================= */
/* Abstract */
/* ============================================================================================= */

/*  This tool generates the file mon_trace_group_ids.h

*/


/* ============================================================================================= */
/* Includes */
/* ============================================================================================= */
#define AUTOGEN_DO_NOT_INCLUDE_ISI_MACROS
#include "autogen_def.h"
#undef AUTOGEN_DO_NOT_INCLUDE_ISI_MACROS

#include "autogen_init.h"

#include "isi_macros_empty.h"

#include "mcu_trace_conf.h"

#include <stdio.h>
#include <string.h>
#include <malloc.h>

#define TI_EXCLUDE_TRACE_DEFINITIONS

/* ============================================================================================= */
/* main function */
/* ============================================================================================= */

#define TRACE_GROUP_MAX 10000

int s_n_groups = 0;
const char* s_groups[TRACE_GROUP_MAX];

int s_n_groups_OFF = 0;
const char* s_groups_OFF[TRACE_GROUP_MAX];

int has_group(const char* grpname)
{
    int n;

    for (n = 0; n < s_n_groups; n++)
    {
        if (strcmp(s_groups[n], grpname) == 0) return TRUE;
    }

    for (n = 0; n < s_n_groups_OFF; n++)
    {
        if (strcmp(s_groups_OFF[n], grpname) == 0) return TRUE;
    }

    return FALSE;
}

void add_group(const char* grpname, int state)
{
    const char* new_grpname = grpname;

    /* change group name from MON_XXX_GRP to XXX */
    if (strlen(grpname) > 8 && !strncmp(grpname, "MON_", 4) && !strcmp(&grpname[strlen(grpname)-4], "_GRP"))
    {
        char* str_grp = (char*)malloc(strlen(grpname) - 7);
        memcpy(str_grp, &grpname[4], strlen(grpname) - 8);
        str_grp[strlen(grpname) - 8] = '\0';

        new_grpname = str_grp;
    }

    if (state == ON)
    {
        if (!has_group(new_grpname))
        {
            printf("   ,%s\n", new_grpname); 

            s_groups[s_n_groups++] = new_grpname;
        }
    }
    else
    {
        if (!has_group(new_grpname))
        {
            s_groups_OFF[s_n_groups_OFF++] = new_grpname;
        }
    }
}

/* macro expansions */

#undef  TRACE_GROUP_BEGIN
#define TRACE_GROUP_BEGIN(_grpname, _dectext, _state) \
    add_group(#_grpname, _state);

#undef  TRACE_GROUP_DECODER
#define TRACE_GROUP_DECODER(_grpname, _dllname, _dllfunc, _flags, _state) \
    add_group(#_grpname, _state);

#undef  MCU_TRACE_GROUP_BEGIN
#define MCU_TRACE_GROUP_BEGIN(_grpname, _dectext, _state) \
    add_group(#_grpname, _state);

#ifdef AUTOGEN_MCU_TRACE_SUPPORT_OLD_CONCEPT

 #undef  MON_TRACE_ID_TBL_BEGIN
 #define MON_TRACE_ID_TBL_BEGIN(_varname, _grpname) \
    add_group(#_grpname, ON);

 #undef  MON_TRACE_GROUP_BEGIN
 #define MON_TRACE_GROUP_BEGIN(_varname, _grpname, _dectext) \
    add_group(#_grpname, ON);

 #undef  MON_TRACE_DEFINE_GROUP_DECODER
 #define MON_TRACE_DEFINE_GROUP_DECODER(_grpname, _dllname, _dllfunc, _flags) \
    add_group(#_grpname, ON);

 #undef  MON_TRACE_DEFINE_GROUP_ID
 #define MON_TRACE_DEFINE_GROUP_ID(_grpname, _text) \
    add_group(#_grpname, ON);

#endif /* AUTOGEN_MCU_TRACE_SUPPORT_OLD_CONCEPT */

int main()
{
    int n;

    printf("/* This file is autogenerated using ti2grp tool (coresw/coretools/autogen)\n");
    printf("   - Please do not change the file manually...\n");
    printf("*/\n\n");
    printf("#ifndef _MON_TRACE_GROUP_IDS_H_\n");
    printf("#define _MON_TRACE_GROUP_IDS_H_\n\n");

    printf("enum trc_grp_tbl\n");
    printf("{\n");
    printf("    DUMMY_TRA = 0\n");

    /* Hard code 1st group */
    s_groups[s_n_groups++] = "DUMMY_TRA";

    /* Generate enums */
#ifdef AUTOGEN_INCLUDE_MCU_TRACES_CORE
    #include "mcu_trace_core.h"
#endif

#if (SIMULATION_ENVIRONMENT == G_SIMULATION_ENVIRONMENT_NONE)
#ifdef AUTOGEN_INCLUDE_MCU_TRACES_PROTOCOL
    #include "mcu_trace_protocol.h"
#endif
#endif

#ifdef AUTOGEN_INCLUDE_VENDOR_TRACES
    #include "chipset_vendor_trace_mon.ti"
#endif

#ifdef AUTOGEN_INCLUDE_MCU_TRACES_ISA_UI
    #include "mcu_trace_isa_ui.h"
#endif

#ifdef AUTOGEN_INCLUDE_MCU_TRACES_MISC
    #include "mcu_trace_misc.h"
#endif

#ifdef AUTOGEN_MCU_TRACE_SUPPORT_OLD_CONCEPT

    #include "autogen_ti_conf.h"
    
    printf("/* Trace groups which have no PMD decoding support...*/\n");
    #include "mon_grp.ti"

#endif /* AUTOGEN_MCU_TRACE_SUPPORT_OLD_CONCEPT */

    printf("};\n\n");


    /* Generate trace group definitions for disabled groups (that are OFF) */
    if (s_n_groups_OFF > 0)
    {
        printf("/* Trace groups which are OFF in the build...*/\n");
        printf("enum tra_tbl_grp_off\n");
        printf("{\n");
        printf("    DUMMY_TRA_OFF\n");
        for (n = 0; n < s_n_groups_OFF; n++)
        {
            printf("   ,%s=0x0000\n", s_groups_OFF[n]);
        }
        printf("};\n");
        printf("\n");
    }

    /* Generate MON_XXX_GRP constants (for compatibility) */
    printf("/* Definitions for backward compatibility */\n");
    for (n = 1; n < s_n_groups; n++)
    {
        printf("#define MON_%s_GRP %s\n", s_groups[n], s_groups[n]);
    }
    printf("/* Definitions for backward compatibility (groups that are OFF) */\n");
    for (n = 0; n < s_n_groups_OFF; n++)
    {
        printf("#define MON_%s_GRP %s\n", s_groups_OFF[n], s_groups_OFF[n]);
    }
    printf("\n\n");


    printf("#define MCU_TRACE_GROUPS_MAX  %d\n", s_n_groups);

    /* Calculate bitmap length - use minimum 96 bytes, which has been default value in example_mon_conf.h */
    printf("#define MON_TRACE_BITMAP_LEN  %d", ((s_n_groups >> 3)<96 ? 96 : ((s_n_groups >> 3)+1)));

    printf("\n\n");
    printf("#endif /* _MON_TRACE_GROUP_IDS_H_ */\n\n");

    return 0;
}
